/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from "zod";
import { githubComDomicileappDomicileInternalDbRecipeIngredientSchema } from "./githubComDomicileappDomicileInternalDb/recipeIngredientSchema";
import { internalRecipesCreateIngredientRequestSchema } from "./internalRecipes/createIngredientRequestSchema";

export const createRecipeIngredientPathIdSchema = z.int().describe("Recipe ID");

export const createRecipeIngredientStatus201Schema =
  githubComDomicileappDomicileInternalDbRecipeIngredientSchema;

export const createRecipeIngredientResponseSchema = createRecipeIngredientStatus201Schema;

export const createRecipeIngredientBodySchema = z
  .union([z.object({}).strict(), internalRecipesCreateIngredientRequestSchema.strict()])
  .describe("Ingredient data");
