/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from "zod";
import { githubComDomicileappDomicileInternalDbRecipeSchema } from "./githubComDomicileappDomicileInternalDb/recipeSchema";
import { internalRecipesCreateRecipeRequestSchema } from "./internalRecipes/createRecipeRequestSchema";

export const createRecipeStatus200Schema = githubComDomicileappDomicileInternalDbRecipeSchema;

export const createRecipeResponseSchema = createRecipeStatus200Schema;

export const createRecipeBodySchema = z
  .union([z.object({}).strict(), internalRecipesCreateRecipeRequestSchema.strict()])
  .describe("Recipe data");
