/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from "zod";
import { githubComDomicileappDomicileInternalDbRecipeInstructionSchema } from "./githubComDomicileappDomicileInternalDb/recipeInstructionSchema";
import { internalRecipesCreateInstructionRequestSchema } from "./internalRecipes/createInstructionRequestSchema";

export const createRecipeInstructionPathIdSchema = z.int().describe("Recipe ID");

export const createRecipeInstructionStatus201Schema =
  githubComDomicileappDomicileInternalDbRecipeInstructionSchema;

export const createRecipeInstructionResponseSchema = createRecipeInstructionStatus201Schema;

export const createRecipeInstructionBodySchema = z
  .union([z.object({}).strict(), internalRecipesCreateInstructionRequestSchema.strict()])
  .describe("Instruction data");
