/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from "zod";
import { githubComDomicileappDomicileInternalDbRecipeSchema } from "./githubComDomicileappDomicileInternalDb/recipeSchema";

export const deleteApiV1RecipesIdIngredientPathIdSchema = z.int().describe("Recipe ID");

export const deleteApiV1RecipesIdIngredientStatus204Schema =
  githubComDomicileappDomicileInternalDbRecipeSchema;

export const deleteApiV1RecipesIdIngredientResponseSchema =
  deleteApiV1RecipesIdIngredientStatus204Schema;

export const deleteApiV1RecipesIdIngredientBodySchema = z.object({}).optional();
