/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from "zod";

export const deleteApiV1RecipesPathIdSchema = z.int().describe("Recipe ID");

export const deleteApiV1RecipesStatus204Schema = z.unknown();

export const deleteApiV1RecipesResponseSchema = deleteApiV1RecipesStatus204Schema;

export const deleteApiV1RecipesBodySchema = z.object({}).optional();
