/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from "zod";

export const deleteRecipePathIdSchema = z.int().describe("Recipe ID");

export const deleteRecipeStatus204Schema = z.unknown();

export const deleteRecipeResponseSchema = deleteRecipeStatus204Schema;

export const deleteRecipeBodySchema = z.object({}).optional();
