/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from "zod";
import { githubComDomicileappDomicileInternalDbRecipeSchema } from "./githubComDomicileappDomicileInternalDb/recipeSchema";

export const deleteRecipeInstructionPathIdSchema = z.int().describe("Recipe ID");

export const deleteRecipeInstructionStatus204Schema =
  githubComDomicileappDomicileInternalDbRecipeSchema;

export const deleteRecipeInstructionResponseSchema = deleteRecipeInstructionStatus204Schema;

export const deleteRecipeInstructionBodySchema = z.object({}).optional();
