/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from "zod";
import { githubComDomicileappDomicileInternalDbRecipeSchema } from "./githubComDomicileappDomicileInternalDb/recipeSchema";

export const deleteApiV1RecipesIdInstructionPathIdSchema = z.int().describe("Recipe ID");

export const deleteApiV1RecipesIdInstructionStatus204Schema =
  githubComDomicileappDomicileInternalDbRecipeSchema;

export const deleteApiV1RecipesIdInstructionResponseSchema =
  deleteApiV1RecipesIdInstructionStatus204Schema;

export const deleteApiV1RecipesIdInstructionBodySchema = z.object({}).optional();
