/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from "zod";
import { internalRecipesRecipeResponseSchema } from "./internalRecipes/recipeResponseSchema";

export const getApiV1RecipesIdPathIdSchema = z.int().describe("Recipe ID");

export const getApiV1RecipesIdStatus200Schema = internalRecipesRecipeResponseSchema;

export const getApiV1RecipesIdResponseSchema = getApiV1RecipesIdStatus200Schema;

export const getApiV1RecipesIdBodySchema = z.object({}).optional();
