/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from "zod";
import { internalRecipesRecipeResponseSchema } from "./internalRecipes/recipeResponseSchema";

export const getRecipePathIdSchema = z.int().describe("Recipe ID");

export const getRecipeStatus200Schema = internalRecipesRecipeResponseSchema;

export const getRecipeResponseSchema = getRecipeStatus200Schema;

export const getRecipeBodySchema = z.object({}).optional();
