/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from "zod";
import { githubComDomicileappDomicileInternalDbRecipeSchema } from "./githubComDomicileappDomicileInternalDb/recipeSchema";

export const listRecipesStatus200Schema = z.array(
  githubComDomicileappDomicileInternalDbRecipeSchema,
);

export const listRecipesResponseSchema = listRecipesStatus200Schema;

export const listRecipesBodySchema = z.object({}).optional();
