/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from "zod";
import { githubComDomicileappDomicileInternalDbRecipeIngredientSchema } from "./githubComDomicileappDomicileInternalDb/recipeIngredientSchema";
import { internalRecipesCreateIngredientRequestSchema } from "./internalRecipes/createIngredientRequestSchema";

export const postApiV1RecipesIdIngredientsPathIdSchema = z.int().describe("Recipe ID");

export const postApiV1RecipesIdIngredientsStatus201Schema =
  githubComDomicileappDomicileInternalDbRecipeIngredientSchema;

export const postApiV1RecipesIdIngredientsResponseSchema =
  postApiV1RecipesIdIngredientsStatus201Schema;

export const postApiV1RecipesIdIngredientsBodySchema = z
  .union([z.object({}).strict(), internalRecipesCreateIngredientRequestSchema.strict()])
  .describe("Ingredient data");
