/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from "zod";
import { githubComDomicileappDomicileInternalDbRecipeInstructionSchema } from "./githubComDomicileappDomicileInternalDb/recipeInstructionSchema";
import { internalRecipesCreateInstructionRequestSchema } from "./internalRecipes/createInstructionRequestSchema";

export const postApiV1RecipesIdInstructionsPathIdSchema = z.int().describe("Recipe ID");

export const postApiV1RecipesIdInstructionsStatus201Schema =
  githubComDomicileappDomicileInternalDbRecipeInstructionSchema;

export const postApiV1RecipesIdInstructionsResponseSchema =
  postApiV1RecipesIdInstructionsStatus201Schema;

export const postApiV1RecipesIdInstructionsBodySchema = z
  .union([z.object({}).strict(), internalRecipesCreateInstructionRequestSchema.strict()])
  .describe("Instruction data");
