/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from "zod";
import { githubComDomicileappDomicileInternalDbRecipeSchema } from "./githubComDomicileappDomicileInternalDb/recipeSchema";
import { internalRecipesCreateRecipeRequestSchema } from "./internalRecipes/createRecipeRequestSchema";

export const postApiV1RecipesStatus200Schema = githubComDomicileappDomicileInternalDbRecipeSchema;

export const postApiV1RecipesResponseSchema = postApiV1RecipesStatus200Schema;

export const postApiV1RecipesBodySchema = z
  .union([z.object({}).strict(), internalRecipesCreateRecipeRequestSchema.strict()])
  .describe("Recipe data");
