/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from "zod";
import { githubComDomicileappDomicileInternalDbRecipeSchema } from "./githubComDomicileappDomicileInternalDb/recipeSchema";
import { internalRecipesUpdateRecipeRequestSchema } from "./internalRecipes/updateRecipeRequestSchema";

export const putApiV1RecipesIdStatus204Schema = githubComDomicileappDomicileInternalDbRecipeSchema;

export const putApiV1RecipesIdResponseSchema = putApiV1RecipesIdStatus204Schema;

export const putApiV1RecipesIdBodySchema = z
  .union([z.object({}).strict(), internalRecipesUpdateRecipeRequestSchema.strict()])
  .describe("Recipe data");
