/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from "zod";
import { githubComDomicileappDomicileInternalDbRecipeSchema } from "./githubComDomicileappDomicileInternalDb/recipeSchema";
import { internalRecipesUpdateIngredientRequestSchema } from "./internalRecipes/updateIngredientRequestSchema";

export const putApiV1RecipesIdIngredientPathIdSchema = z.int().describe("Recipe ID");

export const putApiV1RecipesIdIngredientStatus201Schema =
  githubComDomicileappDomicileInternalDbRecipeSchema;

export const putApiV1RecipesIdIngredientResponseSchema = putApiV1RecipesIdIngredientStatus201Schema;

export const putApiV1RecipesIdIngredientBodySchema = z
  .union([z.object({}).strict(), internalRecipesUpdateIngredientRequestSchema.strict()])
  .describe("Ingredient data");
