/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from "zod";
import { githubComDomicileappDomicileInternalDbRecipeSchema } from "./githubComDomicileappDomicileInternalDb/recipeSchema";
import { internalRecipesUpdateInstructionRequestSchema } from "./internalRecipes/updateInstructionRequestSchema";

export const putApiV1RecipesIdInstructionPathIdSchema = z.int().describe("Recipe ID");

export const putApiV1RecipesIdInstructionStatus201Schema =
  githubComDomicileappDomicileInternalDbRecipeSchema;

export const putApiV1RecipesIdInstructionResponseSchema =
  putApiV1RecipesIdInstructionStatus201Schema;

export const putApiV1RecipesIdInstructionBodySchema = z
  .union([z.object({}).strict(), internalRecipesUpdateInstructionRequestSchema.strict()])
  .describe("Instruction data");
