/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from "zod";
import { githubComDomicileappDomicileInternalDbRecipeSchema } from "./githubComDomicileappDomicileInternalDb/recipeSchema";
import { internalRecipesUpdateInstructionRequestSchema } from "./internalRecipes/updateInstructionRequestSchema";

export const updateRecipeInstructionPathIdSchema = z.int().describe("Recipe ID");

export const updateRecipeInstructionStatus201Schema =
  githubComDomicileappDomicileInternalDbRecipeSchema;

export const updateRecipeInstructionResponseSchema = updateRecipeInstructionStatus201Schema;

export const updateRecipeInstructionBodySchema = z
  .union([z.object({}).strict(), internalRecipesUpdateInstructionRequestSchema.strict()])
  .describe("Instruction data");
