/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from "zod";
import { githubComDomicileappDomicileInternalDbRecipeSchema } from "./githubComDomicileappDomicileInternalDb/recipeSchema";
import { internalRecipesUpdateRecipeRequestSchema } from "./internalRecipes/updateRecipeRequestSchema";

export const updateRecipeStatus204Schema = githubComDomicileappDomicileInternalDbRecipeSchema;

export const updateRecipeResponseSchema = updateRecipeStatus204Schema;

export const updateRecipeBodySchema = z
  .union([z.object({}).strict(), internalRecipesUpdateRecipeRequestSchema.strict()])
  .describe("Recipe data");
