/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from "zod";
import { githubComDomicileappDomicileInternalDbRecipeSchema } from "./githubComDomicileappDomicileInternalDb/recipeSchema";
import { internalRecipesUpdateIngredientRequestSchema } from "./internalRecipes/updateIngredientRequestSchema";

export const updateRecipeIngredientPathIdSchema = z.int().describe("Recipe ID");

export const updateRecipeIngredientStatus201Schema =
  githubComDomicileappDomicileInternalDbRecipeSchema;

export const updateRecipeIngredientResponseSchema = updateRecipeIngredientStatus201Schema;

export const updateRecipeIngredientBodySchema = z
  .union([z.object({}).strict(), internalRecipesUpdateIngredientRequestSchema.strict()])
  .describe("Ingredient data");
