version: 2
updates:
  - package-ecosystem: "npm"
    target-branch: "dev"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    target-branch: "dev"
    directory: "/api"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    target-branch: "dev"
    directory: "/app"
    schedule:
      interval: "daily"
