version: 2
updates:
  - package-ecosystem: 'npm'
    target-branch: 'next'
    directory: '/'
    schedule:
      interval: 'daily'
    commit-message:
      include: scope
      prefix: chore
    labels:
      - 'category/deps'
