// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package recipes

import (
	"context"
	"github.com/domicileapp/domicile/internal/db"
	"sync"
)

// Ensure, that RecipeStoreMock does implement RecipeStore.
// If this is not the case, regenerate this file with moq.
var _ RecipeStore = &RecipeStoreMock{}

// RecipeStoreMock is a mock implementation of RecipeStore.
//
//	func TestSomethingThatUsesRecipeStore(t *testing.T) {
//
//		// make and configure a mocked RecipeStore
//		mockedRecipeStore := &RecipeStoreMock{
//			CountRecipesFunc: func(ctx context.Context) (int64, error) {
//				panic("mock out the CountRecipes method")
//			},
//			CreateRecipeFunc: func(ctx context.Context, params createRecipeRequest) (db.Recipe, error) {
//				panic("mock out the CreateRecipe method")
//			},
//			CreateRecipeIngredientFunc: func(ctx context.Context, recipeID int64, params createIngredientRequest) (db.RecipeIngredient, error) {
//				panic("mock out the CreateRecipeIngredient method")
//			},
//			CreateRecipeInstructionFunc: func(ctx context.Context, recipeID int64, params createInstructionRequest) (db.RecipeInstruction, error) {
//				panic("mock out the CreateRecipeInstruction method")
//			},
//			DeleteRecipeFunc: func(ctx context.Context, id int64) error {
//				panic("mock out the DeleteRecipe method")
//			},
//			DeleteRecipeIngredientFunc: func(ctx context.Context, id int64) error {
//				panic("mock out the DeleteRecipeIngredient method")
//			},
//			DeleteRecipeInstructionFunc: func(ctx context.Context, id int64) error {
//				panic("mock out the DeleteRecipeInstruction method")
//			},
//			GetRecipeFunc: func(ctx context.Context, id int64) (db.Recipe, error) {
//				panic("mock out the GetRecipe method")
//			},
//			ListRecipeIngredientsFunc: func(ctx context.Context, recipeIDs []int64) ([]db.ListRecipeIngredientsRow, error) {
//				panic("mock out the ListRecipeIngredients method")
//			},
//			ListRecipeInstructionsFunc: func(ctx context.Context, recipeIDs []int64) ([]db.ListRecipeInstructionsRow, error) {
//				panic("mock out the ListRecipeInstructions method")
//			},
//			ListRecipesFunc: func(ctx context.Context, limit int32, offset int32) ([]db.ListRecipesRow, error) {
//				panic("mock out the ListRecipes method")
//			},
//			UpdateRecipeFunc: func(ctx context.Context, id int64, params updateRecipeRequest) (db.Recipe, error) {
//				panic("mock out the UpdateRecipe method")
//			},
//			UpdateRecipeIngredientFunc: func(ctx context.Context, id int64, params updateIngredientRequest) error {
//				panic("mock out the UpdateRecipeIngredient method")
//			},
//			UpdateRecipeInstructionFunc: func(ctx context.Context, id int64, params updateInstructionRequest) error {
//				panic("mock out the UpdateRecipeInstruction method")
//			},
//		}
//
//		// use mockedRecipeStore in code that requires RecipeStore
//		// and then make assertions.
//
//	}
type RecipeStoreMock struct {
	// CountRecipesFunc mocks the CountRecipes method.
	CountRecipesFunc func(ctx context.Context) (int64, error)

	// CreateRecipeFunc mocks the CreateRecipe method.
	CreateRecipeFunc func(ctx context.Context, params createRecipeRequest) (db.Recipe, error)

	// CreateRecipeIngredientFunc mocks the CreateRecipeIngredient method.
	CreateRecipeIngredientFunc func(ctx context.Context, recipeID int64, params createIngredientRequest) (db.RecipeIngredient, error)

	// CreateRecipeInstructionFunc mocks the CreateRecipeInstruction method.
	CreateRecipeInstructionFunc func(ctx context.Context, recipeID int64, params createInstructionRequest) (db.RecipeInstruction, error)

	// DeleteRecipeFunc mocks the DeleteRecipe method.
	DeleteRecipeFunc func(ctx context.Context, id int64) error

	// DeleteRecipeIngredientFunc mocks the DeleteRecipeIngredient method.
	DeleteRecipeIngredientFunc func(ctx context.Context, id int64) error

	// DeleteRecipeInstructionFunc mocks the DeleteRecipeInstruction method.
	DeleteRecipeInstructionFunc func(ctx context.Context, id int64) error

	// GetRecipeFunc mocks the GetRecipe method.
	GetRecipeFunc func(ctx context.Context, id int64) (db.Recipe, error)

	// ListRecipeIngredientsFunc mocks the ListRecipeIngredients method.
	ListRecipeIngredientsFunc func(ctx context.Context, recipeIDs []int64) ([]db.ListRecipeIngredientsRow, error)

	// ListRecipeInstructionsFunc mocks the ListRecipeInstructions method.
	ListRecipeInstructionsFunc func(ctx context.Context, recipeIDs []int64) ([]db.ListRecipeInstructionsRow, error)

	// ListRecipesFunc mocks the ListRecipes method.
	ListRecipesFunc func(ctx context.Context, limit int32, offset int32) ([]db.ListRecipesRow, error)

	// UpdateRecipeFunc mocks the UpdateRecipe method.
	UpdateRecipeFunc func(ctx context.Context, id int64, params updateRecipeRequest) (db.Recipe, error)

	// UpdateRecipeIngredientFunc mocks the UpdateRecipeIngredient method.
	UpdateRecipeIngredientFunc func(ctx context.Context, id int64, params updateIngredientRequest) error

	// UpdateRecipeInstructionFunc mocks the UpdateRecipeInstruction method.
	UpdateRecipeInstructionFunc func(ctx context.Context, id int64, params updateInstructionRequest) error

	// calls tracks calls to the methods.
	calls struct {
		// CountRecipes holds details about calls to the CountRecipes method.
		CountRecipes []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// CreateRecipe holds details about calls to the CreateRecipe method.
		CreateRecipe []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Params is the params argument value.
			Params createRecipeRequest
		}
		// CreateRecipeIngredient holds details about calls to the CreateRecipeIngredient method.
		CreateRecipeIngredient []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// RecipeID is the recipeID argument value.
			RecipeID int64
			// Params is the params argument value.
			Params createIngredientRequest
		}
		// CreateRecipeInstruction holds details about calls to the CreateRecipeInstruction method.
		CreateRecipeInstruction []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// RecipeID is the recipeID argument value.
			RecipeID int64
			// Params is the params argument value.
			Params createInstructionRequest
		}
		// DeleteRecipe holds details about calls to the DeleteRecipe method.
		DeleteRecipe []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int64
		}
		// DeleteRecipeIngredient holds details about calls to the DeleteRecipeIngredient method.
		DeleteRecipeIngredient []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int64
		}
		// DeleteRecipeInstruction holds details about calls to the DeleteRecipeInstruction method.
		DeleteRecipeInstruction []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int64
		}
		// GetRecipe holds details about calls to the GetRecipe method.
		GetRecipe []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int64
		}
		// ListRecipeIngredients holds details about calls to the ListRecipeIngredients method.
		ListRecipeIngredients []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// RecipeIDs is the recipeIDs argument value.
			RecipeIDs []int64
		}
		// ListRecipeInstructions holds details about calls to the ListRecipeInstructions method.
		ListRecipeInstructions []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// RecipeIDs is the recipeIDs argument value.
			RecipeIDs []int64
		}
		// ListRecipes holds details about calls to the ListRecipes method.
		ListRecipes []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Limit is the limit argument value.
			Limit int32
			// Offset is the offset argument value.
			Offset int32
		}
		// UpdateRecipe holds details about calls to the UpdateRecipe method.
		UpdateRecipe []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int64
			// Params is the params argument value.
			Params updateRecipeRequest
		}
		// UpdateRecipeIngredient holds details about calls to the UpdateRecipeIngredient method.
		UpdateRecipeIngredient []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int64
			// Params is the params argument value.
			Params updateIngredientRequest
		}
		// UpdateRecipeInstruction holds details about calls to the UpdateRecipeInstruction method.
		UpdateRecipeInstruction []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int64
			// Params is the params argument value.
			Params updateInstructionRequest
		}
	}
	lockCountRecipes            sync.RWMutex
	lockCreateRecipe            sync.RWMutex
	lockCreateRecipeIngredient  sync.RWMutex
	lockCreateRecipeInstruction sync.RWMutex
	lockDeleteRecipe            sync.RWMutex
	lockDeleteRecipeIngredient  sync.RWMutex
	lockDeleteRecipeInstruction sync.RWMutex
	lockGetRecipe               sync.RWMutex
	lockListRecipeIngredients   sync.RWMutex
	lockListRecipeInstructions  sync.RWMutex
	lockListRecipes             sync.RWMutex
	lockUpdateRecipe            sync.RWMutex
	lockUpdateRecipeIngredient  sync.RWMutex
	lockUpdateRecipeInstruction sync.RWMutex
}

// CountRecipes calls CountRecipesFunc.
func (mock *RecipeStoreMock) CountRecipes(ctx context.Context) (int64, error) {
	if mock.CountRecipesFunc == nil {
		panic("RecipeStoreMock.CountRecipesFunc: method is nil but RecipeStore.CountRecipes was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockCountRecipes.Lock()
	mock.calls.CountRecipes = append(mock.calls.CountRecipes, callInfo)
	mock.lockCountRecipes.Unlock()
	return mock.CountRecipesFunc(ctx)
}

// CountRecipesCalls gets all the calls that were made to CountRecipes.
// Check the length with:
//
//	len(mockedRecipeStore.CountRecipesCalls())
func (mock *RecipeStoreMock) CountRecipesCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockCountRecipes.RLock()
	calls = mock.calls.CountRecipes
	mock.lockCountRecipes.RUnlock()
	return calls
}

// CreateRecipe calls CreateRecipeFunc.
func (mock *RecipeStoreMock) CreateRecipe(ctx context.Context, params createRecipeRequest) (db.Recipe, error) {
	if mock.CreateRecipeFunc == nil {
		panic("RecipeStoreMock.CreateRecipeFunc: method is nil but RecipeStore.CreateRecipe was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Params createRecipeRequest
	}{
		Ctx:    ctx,
		Params: params,
	}
	mock.lockCreateRecipe.Lock()
	mock.calls.CreateRecipe = append(mock.calls.CreateRecipe, callInfo)
	mock.lockCreateRecipe.Unlock()
	return mock.CreateRecipeFunc(ctx, params)
}

// CreateRecipeCalls gets all the calls that were made to CreateRecipe.
// Check the length with:
//
//	len(mockedRecipeStore.CreateRecipeCalls())
func (mock *RecipeStoreMock) CreateRecipeCalls() []struct {
	Ctx    context.Context
	Params createRecipeRequest
} {
	var calls []struct {
		Ctx    context.Context
		Params createRecipeRequest
	}
	mock.lockCreateRecipe.RLock()
	calls = mock.calls.CreateRecipe
	mock.lockCreateRecipe.RUnlock()
	return calls
}

// CreateRecipeIngredient calls CreateRecipeIngredientFunc.
func (mock *RecipeStoreMock) CreateRecipeIngredient(ctx context.Context, recipeID int64, params createIngredientRequest) (db.RecipeIngredient, error) {
	if mock.CreateRecipeIngredientFunc == nil {
		panic("RecipeStoreMock.CreateRecipeIngredientFunc: method is nil but RecipeStore.CreateRecipeIngredient was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		RecipeID int64
		Params   createIngredientRequest
	}{
		Ctx:      ctx,
		RecipeID: recipeID,
		Params:   params,
	}
	mock.lockCreateRecipeIngredient.Lock()
	mock.calls.CreateRecipeIngredient = append(mock.calls.CreateRecipeIngredient, callInfo)
	mock.lockCreateRecipeIngredient.Unlock()
	return mock.CreateRecipeIngredientFunc(ctx, recipeID, params)
}

// CreateRecipeIngredientCalls gets all the calls that were made to CreateRecipeIngredient.
// Check the length with:
//
//	len(mockedRecipeStore.CreateRecipeIngredientCalls())
func (mock *RecipeStoreMock) CreateRecipeIngredientCalls() []struct {
	Ctx      context.Context
	RecipeID int64
	Params   createIngredientRequest
} {
	var calls []struct {
		Ctx      context.Context
		RecipeID int64
		Params   createIngredientRequest
	}
	mock.lockCreateRecipeIngredient.RLock()
	calls = mock.calls.CreateRecipeIngredient
	mock.lockCreateRecipeIngredient.RUnlock()
	return calls
}

// CreateRecipeInstruction calls CreateRecipeInstructionFunc.
func (mock *RecipeStoreMock) CreateRecipeInstruction(ctx context.Context, recipeID int64, params createInstructionRequest) (db.RecipeInstruction, error) {
	if mock.CreateRecipeInstructionFunc == nil {
		panic("RecipeStoreMock.CreateRecipeInstructionFunc: method is nil but RecipeStore.CreateRecipeInstruction was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		RecipeID int64
		Params   createInstructionRequest
	}{
		Ctx:      ctx,
		RecipeID: recipeID,
		Params:   params,
	}
	mock.lockCreateRecipeInstruction.Lock()
	mock.calls.CreateRecipeInstruction = append(mock.calls.CreateRecipeInstruction, callInfo)
	mock.lockCreateRecipeInstruction.Unlock()
	return mock.CreateRecipeInstructionFunc(ctx, recipeID, params)
}

// CreateRecipeInstructionCalls gets all the calls that were made to CreateRecipeInstruction.
// Check the length with:
//
//	len(mockedRecipeStore.CreateRecipeInstructionCalls())
func (mock *RecipeStoreMock) CreateRecipeInstructionCalls() []struct {
	Ctx      context.Context
	RecipeID int64
	Params   createInstructionRequest
} {
	var calls []struct {
		Ctx      context.Context
		RecipeID int64
		Params   createInstructionRequest
	}
	mock.lockCreateRecipeInstruction.RLock()
	calls = mock.calls.CreateRecipeInstruction
	mock.lockCreateRecipeInstruction.RUnlock()
	return calls
}

// DeleteRecipe calls DeleteRecipeFunc.
func (mock *RecipeStoreMock) DeleteRecipe(ctx context.Context, id int64) error {
	if mock.DeleteRecipeFunc == nil {
		panic("RecipeStoreMock.DeleteRecipeFunc: method is nil but RecipeStore.DeleteRecipe was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  int64
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockDeleteRecipe.Lock()
	mock.calls.DeleteRecipe = append(mock.calls.DeleteRecipe, callInfo)
	mock.lockDeleteRecipe.Unlock()
	return mock.DeleteRecipeFunc(ctx, id)
}

// DeleteRecipeCalls gets all the calls that were made to DeleteRecipe.
// Check the length with:
//
//	len(mockedRecipeStore.DeleteRecipeCalls())
func (mock *RecipeStoreMock) DeleteRecipeCalls() []struct {
	Ctx context.Context
	ID  int64
} {
	var calls []struct {
		Ctx context.Context
		ID  int64
	}
	mock.lockDeleteRecipe.RLock()
	calls = mock.calls.DeleteRecipe
	mock.lockDeleteRecipe.RUnlock()
	return calls
}

// DeleteRecipeIngredient calls DeleteRecipeIngredientFunc.
func (mock *RecipeStoreMock) DeleteRecipeIngredient(ctx context.Context, id int64) error {
	if mock.DeleteRecipeIngredientFunc == nil {
		panic("RecipeStoreMock.DeleteRecipeIngredientFunc: method is nil but RecipeStore.DeleteRecipeIngredient was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  int64
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockDeleteRecipeIngredient.Lock()
	mock.calls.DeleteRecipeIngredient = append(mock.calls.DeleteRecipeIngredient, callInfo)
	mock.lockDeleteRecipeIngredient.Unlock()
	return mock.DeleteRecipeIngredientFunc(ctx, id)
}

// DeleteRecipeIngredientCalls gets all the calls that were made to DeleteRecipeIngredient.
// Check the length with:
//
//	len(mockedRecipeStore.DeleteRecipeIngredientCalls())
func (mock *RecipeStoreMock) DeleteRecipeIngredientCalls() []struct {
	Ctx context.Context
	ID  int64
} {
	var calls []struct {
		Ctx context.Context
		ID  int64
	}
	mock.lockDeleteRecipeIngredient.RLock()
	calls = mock.calls.DeleteRecipeIngredient
	mock.lockDeleteRecipeIngredient.RUnlock()
	return calls
}

// DeleteRecipeInstruction calls DeleteRecipeInstructionFunc.
func (mock *RecipeStoreMock) DeleteRecipeInstruction(ctx context.Context, id int64) error {
	if mock.DeleteRecipeInstructionFunc == nil {
		panic("RecipeStoreMock.DeleteRecipeInstructionFunc: method is nil but RecipeStore.DeleteRecipeInstruction was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  int64
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockDeleteRecipeInstruction.Lock()
	mock.calls.DeleteRecipeInstruction = append(mock.calls.DeleteRecipeInstruction, callInfo)
	mock.lockDeleteRecipeInstruction.Unlock()
	return mock.DeleteRecipeInstructionFunc(ctx, id)
}

// DeleteRecipeInstructionCalls gets all the calls that were made to DeleteRecipeInstruction.
// Check the length with:
//
//	len(mockedRecipeStore.DeleteRecipeInstructionCalls())
func (mock *RecipeStoreMock) DeleteRecipeInstructionCalls() []struct {
	Ctx context.Context
	ID  int64
} {
	var calls []struct {
		Ctx context.Context
		ID  int64
	}
	mock.lockDeleteRecipeInstruction.RLock()
	calls = mock.calls.DeleteRecipeInstruction
	mock.lockDeleteRecipeInstruction.RUnlock()
	return calls
}

// GetRecipe calls GetRecipeFunc.
func (mock *RecipeStoreMock) GetRecipe(ctx context.Context, id int64) (db.Recipe, error) {
	if mock.GetRecipeFunc == nil {
		panic("RecipeStoreMock.GetRecipeFunc: method is nil but RecipeStore.GetRecipe was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  int64
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGetRecipe.Lock()
	mock.calls.GetRecipe = append(mock.calls.GetRecipe, callInfo)
	mock.lockGetRecipe.Unlock()
	return mock.GetRecipeFunc(ctx, id)
}

// GetRecipeCalls gets all the calls that were made to GetRecipe.
// Check the length with:
//
//	len(mockedRecipeStore.GetRecipeCalls())
func (mock *RecipeStoreMock) GetRecipeCalls() []struct {
	Ctx context.Context
	ID  int64
} {
	var calls []struct {
		Ctx context.Context
		ID  int64
	}
	mock.lockGetRecipe.RLock()
	calls = mock.calls.GetRecipe
	mock.lockGetRecipe.RUnlock()
	return calls
}

// ListRecipeIngredients calls ListRecipeIngredientsFunc.
func (mock *RecipeStoreMock) ListRecipeIngredients(ctx context.Context, recipeIDs []int64) ([]db.ListRecipeIngredientsRow, error) {
	if mock.ListRecipeIngredientsFunc == nil {
		panic("RecipeStoreMock.ListRecipeIngredientsFunc: method is nil but RecipeStore.ListRecipeIngredients was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		RecipeIDs []int64
	}{
		Ctx:       ctx,
		RecipeIDs: recipeIDs,
	}
	mock.lockListRecipeIngredients.Lock()
	mock.calls.ListRecipeIngredients = append(mock.calls.ListRecipeIngredients, callInfo)
	mock.lockListRecipeIngredients.Unlock()
	return mock.ListRecipeIngredientsFunc(ctx, recipeIDs)
}

// ListRecipeIngredientsCalls gets all the calls that were made to ListRecipeIngredients.
// Check the length with:
//
//	len(mockedRecipeStore.ListRecipeIngredientsCalls())
func (mock *RecipeStoreMock) ListRecipeIngredientsCalls() []struct {
	Ctx       context.Context
	RecipeIDs []int64
} {
	var calls []struct {
		Ctx       context.Context
		RecipeIDs []int64
	}
	mock.lockListRecipeIngredients.RLock()
	calls = mock.calls.ListRecipeIngredients
	mock.lockListRecipeIngredients.RUnlock()
	return calls
}

// ListRecipeInstructions calls ListRecipeInstructionsFunc.
func (mock *RecipeStoreMock) ListRecipeInstructions(ctx context.Context, recipeIDs []int64) ([]db.ListRecipeInstructionsRow, error) {
	if mock.ListRecipeInstructionsFunc == nil {
		panic("RecipeStoreMock.ListRecipeInstructionsFunc: method is nil but RecipeStore.ListRecipeInstructions was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		RecipeIDs []int64
	}{
		Ctx:       ctx,
		RecipeIDs: recipeIDs,
	}
	mock.lockListRecipeInstructions.Lock()
	mock.calls.ListRecipeInstructions = append(mock.calls.ListRecipeInstructions, callInfo)
	mock.lockListRecipeInstructions.Unlock()
	return mock.ListRecipeInstructionsFunc(ctx, recipeIDs)
}

// ListRecipeInstructionsCalls gets all the calls that were made to ListRecipeInstructions.
// Check the length with:
//
//	len(mockedRecipeStore.ListRecipeInstructionsCalls())
func (mock *RecipeStoreMock) ListRecipeInstructionsCalls() []struct {
	Ctx       context.Context
	RecipeIDs []int64
} {
	var calls []struct {
		Ctx       context.Context
		RecipeIDs []int64
	}
	mock.lockListRecipeInstructions.RLock()
	calls = mock.calls.ListRecipeInstructions
	mock.lockListRecipeInstructions.RUnlock()
	return calls
}

// ListRecipes calls ListRecipesFunc.
func (mock *RecipeStoreMock) ListRecipes(ctx context.Context, limit int32, offset int32) ([]db.ListRecipesRow, error) {
	if mock.ListRecipesFunc == nil {
		panic("RecipeStoreMock.ListRecipesFunc: method is nil but RecipeStore.ListRecipes was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Limit  int32
		Offset int32
	}{
		Ctx:    ctx,
		Limit:  limit,
		Offset: offset,
	}
	mock.lockListRecipes.Lock()
	mock.calls.ListRecipes = append(mock.calls.ListRecipes, callInfo)
	mock.lockListRecipes.Unlock()
	return mock.ListRecipesFunc(ctx, limit, offset)
}

// ListRecipesCalls gets all the calls that were made to ListRecipes.
// Check the length with:
//
//	len(mockedRecipeStore.ListRecipesCalls())
func (mock *RecipeStoreMock) ListRecipesCalls() []struct {
	Ctx    context.Context
	Limit  int32
	Offset int32
} {
	var calls []struct {
		Ctx    context.Context
		Limit  int32
		Offset int32
	}
	mock.lockListRecipes.RLock()
	calls = mock.calls.ListRecipes
	mock.lockListRecipes.RUnlock()
	return calls
}

// UpdateRecipe calls UpdateRecipeFunc.
func (mock *RecipeStoreMock) UpdateRecipe(ctx context.Context, id int64, params updateRecipeRequest) (db.Recipe, error) {
	if mock.UpdateRecipeFunc == nil {
		panic("RecipeStoreMock.UpdateRecipeFunc: method is nil but RecipeStore.UpdateRecipe was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		ID     int64
		Params updateRecipeRequest
	}{
		Ctx:    ctx,
		ID:     id,
		Params: params,
	}
	mock.lockUpdateRecipe.Lock()
	mock.calls.UpdateRecipe = append(mock.calls.UpdateRecipe, callInfo)
	mock.lockUpdateRecipe.Unlock()
	return mock.UpdateRecipeFunc(ctx, id, params)
}

// UpdateRecipeCalls gets all the calls that were made to UpdateRecipe.
// Check the length with:
//
//	len(mockedRecipeStore.UpdateRecipeCalls())
func (mock *RecipeStoreMock) UpdateRecipeCalls() []struct {
	Ctx    context.Context
	ID     int64
	Params updateRecipeRequest
} {
	var calls []struct {
		Ctx    context.Context
		ID     int64
		Params updateRecipeRequest
	}
	mock.lockUpdateRecipe.RLock()
	calls = mock.calls.UpdateRecipe
	mock.lockUpdateRecipe.RUnlock()
	return calls
}

// UpdateRecipeIngredient calls UpdateRecipeIngredientFunc.
func (mock *RecipeStoreMock) UpdateRecipeIngredient(ctx context.Context, id int64, params updateIngredientRequest) error {
	if mock.UpdateRecipeIngredientFunc == nil {
		panic("RecipeStoreMock.UpdateRecipeIngredientFunc: method is nil but RecipeStore.UpdateRecipeIngredient was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		ID     int64
		Params updateIngredientRequest
	}{
		Ctx:    ctx,
		ID:     id,
		Params: params,
	}
	mock.lockUpdateRecipeIngredient.Lock()
	mock.calls.UpdateRecipeIngredient = append(mock.calls.UpdateRecipeIngredient, callInfo)
	mock.lockUpdateRecipeIngredient.Unlock()
	return mock.UpdateRecipeIngredientFunc(ctx, id, params)
}

// UpdateRecipeIngredientCalls gets all the calls that were made to UpdateRecipeIngredient.
// Check the length with:
//
//	len(mockedRecipeStore.UpdateRecipeIngredientCalls())
func (mock *RecipeStoreMock) UpdateRecipeIngredientCalls() []struct {
	Ctx    context.Context
	ID     int64
	Params updateIngredientRequest
} {
	var calls []struct {
		Ctx    context.Context
		ID     int64
		Params updateIngredientRequest
	}
	mock.lockUpdateRecipeIngredient.RLock()
	calls = mock.calls.UpdateRecipeIngredient
	mock.lockUpdateRecipeIngredient.RUnlock()
	return calls
}

// UpdateRecipeInstruction calls UpdateRecipeInstructionFunc.
func (mock *RecipeStoreMock) UpdateRecipeInstruction(ctx context.Context, id int64, params updateInstructionRequest) error {
	if mock.UpdateRecipeInstructionFunc == nil {
		panic("RecipeStoreMock.UpdateRecipeInstructionFunc: method is nil but RecipeStore.UpdateRecipeInstruction was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		ID     int64
		Params updateInstructionRequest
	}{
		Ctx:    ctx,
		ID:     id,
		Params: params,
	}
	mock.lockUpdateRecipeInstruction.Lock()
	mock.calls.UpdateRecipeInstruction = append(mock.calls.UpdateRecipeInstruction, callInfo)
	mock.lockUpdateRecipeInstruction.Unlock()
	return mock.UpdateRecipeInstructionFunc(ctx, id, params)
}

// UpdateRecipeInstructionCalls gets all the calls that were made to UpdateRecipeInstruction.
// Check the length with:
//
//	len(mockedRecipeStore.UpdateRecipeInstructionCalls())
func (mock *RecipeStoreMock) UpdateRecipeInstructionCalls() []struct {
	Ctx    context.Context
	ID     int64
	Params updateInstructionRequest
} {
	var calls []struct {
		Ctx    context.Context
		ID     int64
		Params updateInstructionRequest
	}
	mock.lockUpdateRecipeInstruction.RLock()
	calls = mock.calls.UpdateRecipeInstruction
	mock.lockUpdateRecipeInstruction.RUnlock()
	return calls
}
