"""latest

Revision ID: 77d33a9580dc
Revises: d436502c142e
Create Date: 2023-07-29 12:18:27.351832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77d33a9580dc'
down_revision = 'd436502c142e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
