"""latest

Revision ID: d436502c142e
Revises: c77b3e866175
Create Date: 2023-07-29 12:13:45.301137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d436502c142e"
down_revision = "c77b3e866175"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_users_email", table_name="users")
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.create_index("ix_users_email", "users", ["email"], unique=False)
    # ### end Alembic commands ###
