"""latest

Revision ID: 66ab1f7ca347
Revises: 77d33a9580dc
Create Date: 2023-07-30 17:14:49.459020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "66ab1f7ca347"
down_revision = "77d33a9580dc"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
