"""users_first_last

Revision ID: c309234f0c07
Revises: 09aaaace6e7f
Create Date: 2023-07-28 19:28:22.541348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c309234f0c07"
down_revision = "09aaaace6e7f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("first_name", sa.String(), nullable=True))
    op.add_column("users", sa.Column("last_name", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "last_name")
    op.drop_column("users", "first_name")
    # ### end Alembic commands ###
