---
version: "3"

services:
  db:
    image: postgres:latest
    restart: 'no'
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: P@ssw0rd
      POSTGRES_USER: domicile
    networks:
      - main

networks:
  main:
    driver: bridge

volumes:
  domicile-db:
    external: true
