site_name: Domicile Documentation
theme:
  name: material
plugins:
  - search
  # - gen-files:
  #     scripts:
  #       - scripts/gen_ref_pages.py
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
  - section-index
