version: '3'

vars:
  DEV_DB_URL: postgres://domicile:password@localhost:31185/domicile_dev?sslmode=disable
  TEST_DB_URL: postgres://domicile:password@localhost:31185/domicile_test?sslmode=disable
  PROD_DB_URL: postgres://domicile:password@localhost:31185/domicile_prod?sslmode=disable

tasks:
  default:
    cmds:
      - task --list
    silent: true
  api:dev:
    desc: Run API in dev mode (hot reload)
    silent: false
    cmds:
      - export PYTHONPATH="${PYTHONPATH}:'{{.USER_WORKING_DIR}}'/api/app"
      - uvicorn app.main:app --reload --app-dir api
  db:init:
    dir: api
    desc: Initalize the database for development
    silent: false
    cmds:
      - export PYTHONPATH="${PYTHONPATH}:'{{.USER_WORKING_DIR}}'/api/app"
      - python ./app/prestart.py
      - alembic upgrade head
      - python app/init_data.py
