version: "3"
dotenv:
  - ".env"
  - "web/.env"
tasks:
  default:
    cmds:
      - task --list-all

  update:gha:
    cmds:
      - npx actions-up

  dev:setup:
    cmds:
      - go install github.com/sqlc-dev/sqlc/cmd/sqlc@latest
      - go install github.com/swaggo/swag/v2/cmd/swag@latest
      - go install github.com/pressly/goose/v3/cmd/goose@latest

  db:create-migration:
    requires:
      vars:
        - MIGRATION_NAME
    desc: Create a new migration file.
    cmds:
      - goose create "{{.MIGRATION_NAME}}" sql
    interactive: true

  db:up:
    cmds:
      - goose up
      - task: gen:sql

  db:down:
    cmds:
      - goose down
      - task: gen:sql

  gen:sql:diff:
    cmds:
      - task: dev:setup
      - sqlc diff

  gen:sql:
    cmds:
      - sqlc generate

  gen:docs:
    cmds:
      - task: dev:setup
      - task: gen:sql
      - swag fmt
      - swag init -g cmd/domicile/main.go --parseInternal --parseFuncBody --parseDependency --v3.1
      # https://github.com/swaggo/http-swagger/issues/132
      - |
        if [ "$(uname)" = "Darwin" ]; then
          sed -i '' 's|swag/v2|swag|' docs/docs.go
        else
          sed -i 's|swag/v2|swag|' docs/docs.go
        fi

  dev:db:
    cmds:
      - docker compose -f compose.dev.yml up -d

  dev:
    cmds:
      - task: dev:db
      - task: gen:docs
      - air
