version: '3'

tasks:
  default:
    cmds:
      - task --list
    silent: true
  api:dev:
    desc: Run API in dev mode (hot reload)
    silent: false
    cmds:
      - docker compose -f deploy/docker-compose.yml -f deploy/docker-compose.dev.yml --project-directory . up --build
