version: '3'

vars:
  DEV_DB_URL: postgres://domicile:password@localhost:31185/domicile_dev?sslmode=disable
  TEST_DB_URL: postgres://domicile:password@localhost:31185/domicile_test?sslmode=disable
  PROD_DB_URL: postgres://domicile:password@localhost:31185/domicile_prod?sslmode=disable

tasks:
  default:
    cmds:
      - task --list
  api:dev:
    desc: Run API in dev mode (hot reload)
    silent: false
    cmds:
      - uvicorn main:app --reload
