version: "3"
tasks:
  load-env:
    cmds:
      - source .env

  dev:setup:
    cmds:
      - go install github.com/sqlc-dev/sqlc/cmd/sqlc@latest
      - go install github.com/swaggo/swag/cmd/swag@latest

  gen:sql:
    cmds:
      - task: load-env
      - sqlc generate

  gen:docs:
    cmds:
      - task: gen:sql
      - swag fmt
      - swag init -g cmd/domicile/main.go --parseInternal --parseFuncBody --parseDependency
      - sed -i '' 's|swag/v2|swag|' docs/docs.go # https://github.com/swaggo/http-swagger/issues/132

  dev:db:
    cmds:
      - docker compose -f compose.dev.yml up -d

  dev:
    cmds:
      - task: dev:db
      - task: gen:docs
      - air
