/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type InternalRecipesCreateInstructionRequest = {
  content?: string;
  group_name?: string;
  sort_order?: number;
};
