/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { GithubComDomicileappDomicileInternalDbListRecipeIngredientsRow } from "../githubComDomicileappDomicileInternalDb/ListRecipeIngredientsRow";
import type { GithubComDomicileappDomicileInternalDbListRecipeInstructionsRow } from "../githubComDomicileappDomicileInternalDb/ListRecipeInstructionsRow";

export type InternalRecipesRecipeResponse = {
  cook_time?: string;
  created_at?: string;
  deleted_at?: string;
  id?: number;
  ingredients?: GithubComDomicileappDomicileInternalDbListRecipeIngredientsRow[];
  instructions?: GithubComDomicileappDomicileInternalDbListRecipeInstructionsRow[];
  name?: string;
  notes?: string;
  nutrition?: string;
  prep_time?: string;
  servings?: string;
  short_description?: string;
  source?: string;
  updated_at?: string;
};
