/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type InternalRecipesUpdateIngredientRequest = {
  group_name?: string;
  raw_text?: string;
  sort_order?: number;
};
