apiVersion: apps/v1
kind: Deployment
metadata:
  name: domicile-redis
spec:
  selector:
    matchLabels:
      app: domicile
  template:
    metadata:
      labels:
        app: domicile
    spec:
      containers:
        - name: redis
          image: redis:latest
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: domicile-redis-config
          volumeMounts:
            - mountPath: /var/lib/redis/data
              name: domicile-redis-volume
      volumes:
        - name: domicile-redis-volume
          persistentVolumeClaim:
            claimName: domicile-redis-pv-claim