/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { GithubComDomicileappDomicileInternalDbRecipeIngredient } from "./githubComDomicileappDomicileInternalDb/RecipeIngredient";
import type { InternalRecipesCreateIngredientRequest } from "./internalRecipes/CreateIngredientRequest";

export type CreateRecipeIngredientPath = {
  /**
   * @description Recipe ID
   * @type integer
   */
  id: number;
};

export type CreateRecipeIngredientStatus201 =
  GithubComDomicileappDomicileInternalDbRecipeIngredient;

/**
 * @description Ingredient data
 */
export type CreateRecipeIngredientBody = object | InternalRecipesCreateIngredientRequest;

export type CreateRecipeIngredientOptions = {
  body: CreateRecipeIngredientBody;
  path: CreateRecipeIngredientPath;
  query?: never;
  headers?: never;
};

export type CreateRecipeIngredientResponses = {
  "201": CreateRecipeIngredientStatus201;
};

/**
 * @description Union of all possible responses
 */
export type CreateRecipeIngredientResponse = CreateRecipeIngredientStatus201;
