/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { GithubComDomicileappDomicileInternalDbRecipeInstruction } from "./githubComDomicileappDomicileInternalDb/RecipeInstruction";
import type { InternalRecipesCreateInstructionRequest } from "./internalRecipes/CreateInstructionRequest";

export type CreateRecipeInstructionPath = {
  /**
   * @description Recipe ID
   * @type integer
   */
  id: number;
};

export type CreateRecipeInstructionStatus201 =
  GithubComDomicileappDomicileInternalDbRecipeInstruction;

/**
 * @description Instruction data
 */
export type CreateRecipeInstructionBody = object | InternalRecipesCreateInstructionRequest;

export type CreateRecipeInstructionOptions = {
  body: CreateRecipeInstructionBody;
  path: CreateRecipeInstructionPath;
  query?: never;
  headers?: never;
};

export type CreateRecipeInstructionResponses = {
  "201": CreateRecipeInstructionStatus201;
};

/**
 * @description Union of all possible responses
 */
export type CreateRecipeInstructionResponse = CreateRecipeInstructionStatus201;
