/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { GithubComDomicileappDomicileInternalDbRecipe } from "./githubComDomicileappDomicileInternalDb/Recipe";
import type { InternalRecipesCreateRecipeRequest } from "./internalRecipes/CreateRecipeRequest";

export type CreateRecipeStatus200 = GithubComDomicileappDomicileInternalDbRecipe;

/**
 * @description Recipe data
 */
export type CreateRecipeBody = object | InternalRecipesCreateRecipeRequest;

export type CreateRecipeOptions = {
  body: CreateRecipeBody;
  path?: never;
  query?: never;
  headers?: never;
};

export type CreateRecipeResponses = {
  "200": CreateRecipeStatus200;
};

/**
 * @description Union of all possible responses
 */
export type CreateRecipeResponse = CreateRecipeStatus200;
