/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { GithubComDomicileappDomicileInternalDbRecipe } from "./githubComDomicileappDomicileInternalDb/Recipe";

export type DeleteRecipeInstructionPath = {
  /**
   * @description Recipe ID
   * @type integer
   */
  id: number;
};

export type DeleteRecipeInstructionStatus204 = GithubComDomicileappDomicileInternalDbRecipe;

export type DeleteRecipeInstructionBody = object | undefined;

export type DeleteRecipeInstructionOptions = {
  body: DeleteRecipeInstructionBody;
  path: DeleteRecipeInstructionPath;
  query?: never;
  headers?: never;
};

export type DeleteRecipeInstructionResponses = {
  "204": DeleteRecipeInstructionStatus204;
};

/**
 * @description Union of all possible responses
 */
export type DeleteRecipeInstructionResponse = DeleteRecipeInstructionStatus204;
