/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type DeleteApiV1RecipesPath = {
  /**
   * @description Recipe ID
   * @type integer
   */
  id: number;
};

export type DeleteApiV1RecipesStatus204 = unknown;

export type DeleteApiV1RecipesBody = object | undefined;

export type DeleteApiV1RecipesOptions = {
  body: DeleteApiV1RecipesBody;
  path: DeleteApiV1RecipesPath;
  query?: never;
  headers?: never;
};

export type DeleteApiV1RecipesResponses = {
  "204": DeleteApiV1RecipesStatus204;
};

/**
 * @description Union of all possible responses
 */
export type DeleteApiV1RecipesResponse = DeleteApiV1RecipesStatus204;
