/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type DeleteRecipePath = {
  /**
   * @description Recipe ID
   * @type integer
   */
  id: number;
};

export type DeleteRecipeStatus204 = unknown;

export type DeleteRecipeBody = object | undefined;

export type DeleteRecipeOptions = {
  body: DeleteRecipeBody;
  path: DeleteRecipePath;
  query?: never;
  headers?: never;
};

export type DeleteRecipeResponses = {
  "204": DeleteRecipeStatus204;
};

/**
 * @description Union of all possible responses
 */
export type DeleteRecipeResponse = DeleteRecipeStatus204;
