/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { GithubComDomicileappDomicileInternalDbRecipe } from "./githubComDomicileappDomicileInternalDb/Recipe";

export type DeleteApiV1RecipesIdIngredientPath = {
  /**
   * @description Recipe ID
   * @type integer
   */
  id: number;
};

export type DeleteApiV1RecipesIdIngredientStatus204 = GithubComDomicileappDomicileInternalDbRecipe;

export type DeleteApiV1RecipesIdIngredientBody = object | undefined;

export type DeleteApiV1RecipesIdIngredientOptions = {
  body: DeleteApiV1RecipesIdIngredientBody;
  path: DeleteApiV1RecipesIdIngredientPath;
  query?: never;
  headers?: never;
};

export type DeleteApiV1RecipesIdIngredientResponses = {
  "204": DeleteApiV1RecipesIdIngredientStatus204;
};

/**
 * @description Union of all possible responses
 */
export type DeleteApiV1RecipesIdIngredientResponse = DeleteApiV1RecipesIdIngredientStatus204;
