/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { GithubComDomicileappDomicileInternalDbRecipe } from "./githubComDomicileappDomicileInternalDb/Recipe";

export type DeleteApiV1RecipesIdInstructionPath = {
  /**
   * @description Recipe ID
   * @type integer
   */
  id: number;
};

export type DeleteApiV1RecipesIdInstructionStatus204 = GithubComDomicileappDomicileInternalDbRecipe;

export type DeleteApiV1RecipesIdInstructionBody = object | undefined;

export type DeleteApiV1RecipesIdInstructionOptions = {
  body: DeleteApiV1RecipesIdInstructionBody;
  path: DeleteApiV1RecipesIdInstructionPath;
  query?: never;
  headers?: never;
};

export type DeleteApiV1RecipesIdInstructionResponses = {
  "204": DeleteApiV1RecipesIdInstructionStatus204;
};

/**
 * @description Union of all possible responses
 */
export type DeleteApiV1RecipesIdInstructionResponse = DeleteApiV1RecipesIdInstructionStatus204;
