/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { InternalRecipesRecipeResponse } from "./internalRecipes/RecipeResponse";

export type GetApiV1RecipesIdPath = {
  /**
   * @description Recipe ID
   * @type integer
   */
  id: number;
};

export type GetApiV1RecipesIdStatus200 = InternalRecipesRecipeResponse;

export type GetApiV1RecipesIdBody = object | undefined;

export type GetApiV1RecipesIdOptions = {
  body: GetApiV1RecipesIdBody;
  path: GetApiV1RecipesIdPath;
  query?: never;
  headers?: never;
};

export type GetApiV1RecipesIdResponses = {
  "200": GetApiV1RecipesIdStatus200;
};

/**
 * @description Union of all possible responses
 */
export type GetApiV1RecipesIdResponse = GetApiV1RecipesIdStatus200;
