/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { InternalRecipesRecipeResponse } from "./internalRecipes/RecipeResponse";

export type GetRecipePath = {
  /**
   * @description Recipe ID
   * @type integer
   */
  id: number;
};

export type GetRecipeStatus200 = InternalRecipesRecipeResponse;

export type GetRecipeBody = object | undefined;

export type GetRecipeOptions = {
  body: GetRecipeBody;
  path: GetRecipePath;
  query?: never;
  headers?: never;
};

export type GetRecipeResponses = {
  "200": GetRecipeStatus200;
};

/**
 * @description Union of all possible responses
 */
export type GetRecipeResponse = GetRecipeStatus200;
