/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { GithubComDomicileappDomicileInternalDbRecipe } from "./githubComDomicileappDomicileInternalDb/Recipe";

export type ListRecipesStatus200 = GithubComDomicileappDomicileInternalDbRecipe[];

export type ListRecipesBody = object | undefined;

export type ListRecipesOptions = {
  body: ListRecipesBody;
  path?: never;
  query?: never;
  headers?: never;
};

export type ListRecipesResponses = {
  "200": ListRecipesStatus200;
};

/**
 * @description Union of all possible responses
 */
export type ListRecipesResponse = ListRecipesStatus200;
