/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { GithubComDomicileappDomicileInternalDbRecipeInstruction } from "./githubComDomicileappDomicileInternalDb/RecipeInstruction";
import type { InternalRecipesCreateInstructionRequest } from "./internalRecipes/CreateInstructionRequest";

export type PostApiV1RecipesIdInstructionsPath = {
  /**
   * @description Recipe ID
   * @type integer
   */
  id: number;
};

export type PostApiV1RecipesIdInstructionsStatus201 =
  GithubComDomicileappDomicileInternalDbRecipeInstruction;

/**
 * @description Instruction data
 */
export type PostApiV1RecipesIdInstructionsBody = object | InternalRecipesCreateInstructionRequest;

export type PostApiV1RecipesIdInstructionsOptions = {
  body: PostApiV1RecipesIdInstructionsBody;
  path: PostApiV1RecipesIdInstructionsPath;
  query?: never;
  headers?: never;
};

export type PostApiV1RecipesIdInstructionsResponses = {
  "201": PostApiV1RecipesIdInstructionsStatus201;
};

/**
 * @description Union of all possible responses
 */
export type PostApiV1RecipesIdInstructionsResponse = PostApiV1RecipesIdInstructionsStatus201;
