/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { GithubComDomicileappDomicileInternalDbRecipe } from "./githubComDomicileappDomicileInternalDb/Recipe";
import type { InternalRecipesCreateRecipeRequest } from "./internalRecipes/CreateRecipeRequest";

export type PostApiV1RecipesStatus200 = GithubComDomicileappDomicileInternalDbRecipe;

/**
 * @description Recipe data
 */
export type PostApiV1RecipesBody = object | InternalRecipesCreateRecipeRequest;

export type PostApiV1RecipesOptions = {
  body: PostApiV1RecipesBody;
  path?: never;
  query?: never;
  headers?: never;
};

export type PostApiV1RecipesResponses = {
  "200": PostApiV1RecipesStatus200;
};

/**
 * @description Union of all possible responses
 */
export type PostApiV1RecipesResponse = PostApiV1RecipesStatus200;
