/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { GithubComDomicileappDomicileInternalDbRecipeIngredient } from "./githubComDomicileappDomicileInternalDb/RecipeIngredient";
import type { InternalRecipesCreateIngredientRequest } from "./internalRecipes/CreateIngredientRequest";

export type PostApiV1RecipesIdIngredientsPath = {
  /**
   * @description Recipe ID
   * @type integer
   */
  id: number;
};

export type PostApiV1RecipesIdIngredientsStatus201 =
  GithubComDomicileappDomicileInternalDbRecipeIngredient;

/**
 * @description Ingredient data
 */
export type PostApiV1RecipesIdIngredientsBody = object | InternalRecipesCreateIngredientRequest;

export type PostApiV1RecipesIdIngredientsOptions = {
  body: PostApiV1RecipesIdIngredientsBody;
  path: PostApiV1RecipesIdIngredientsPath;
  query?: never;
  headers?: never;
};

export type PostApiV1RecipesIdIngredientsResponses = {
  "201": PostApiV1RecipesIdIngredientsStatus201;
};

/**
 * @description Union of all possible responses
 */
export type PostApiV1RecipesIdIngredientsResponse = PostApiV1RecipesIdIngredientsStatus201;
