/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { GithubComDomicileappDomicileInternalDbRecipe } from "./githubComDomicileappDomicileInternalDb/Recipe";
import type { InternalRecipesUpdateRecipeRequest } from "./internalRecipes/UpdateRecipeRequest";

export type PutApiV1RecipesIdStatus204 = GithubComDomicileappDomicileInternalDbRecipe;

/**
 * @description Recipe data
 */
export type PutApiV1RecipesIdBody = object | InternalRecipesUpdateRecipeRequest;

export type PutApiV1RecipesIdOptions = {
  body: PutApiV1RecipesIdBody;
  path?: never;
  query?: never;
  headers?: never;
};

export type PutApiV1RecipesIdResponses = {
  "204": PutApiV1RecipesIdStatus204;
};

/**
 * @description Union of all possible responses
 */
export type PutApiV1RecipesIdResponse = PutApiV1RecipesIdStatus204;
