/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { GithubComDomicileappDomicileInternalDbRecipe } from "./githubComDomicileappDomicileInternalDb/Recipe";
import type { InternalRecipesUpdateIngredientRequest } from "./internalRecipes/UpdateIngredientRequest";

export type PutApiV1RecipesIdIngredientPath = {
  /**
   * @description Recipe ID
   * @type integer
   */
  id: number;
};

export type PutApiV1RecipesIdIngredientStatus201 = GithubComDomicileappDomicileInternalDbRecipe;

/**
 * @description Ingredient data
 */
export type PutApiV1RecipesIdIngredientBody = object | InternalRecipesUpdateIngredientRequest;

export type PutApiV1RecipesIdIngredientOptions = {
  body: PutApiV1RecipesIdIngredientBody;
  path: PutApiV1RecipesIdIngredientPath;
  query?: never;
  headers?: never;
};

export type PutApiV1RecipesIdIngredientResponses = {
  "201": PutApiV1RecipesIdIngredientStatus201;
};

/**
 * @description Union of all possible responses
 */
export type PutApiV1RecipesIdIngredientResponse = PutApiV1RecipesIdIngredientStatus201;
