/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { GithubComDomicileappDomicileInternalDbRecipe } from "./githubComDomicileappDomicileInternalDb/Recipe";
import type { InternalRecipesUpdateInstructionRequest } from "./internalRecipes/UpdateInstructionRequest";

export type PutApiV1RecipesIdInstructionPath = {
  /**
   * @description Recipe ID
   * @type integer
   */
  id: number;
};

export type PutApiV1RecipesIdInstructionStatus201 = GithubComDomicileappDomicileInternalDbRecipe;

/**
 * @description Instruction data
 */
export type PutApiV1RecipesIdInstructionBody = object | InternalRecipesUpdateInstructionRequest;

export type PutApiV1RecipesIdInstructionOptions = {
  body: PutApiV1RecipesIdInstructionBody;
  path: PutApiV1RecipesIdInstructionPath;
  query?: never;
  headers?: never;
};

export type PutApiV1RecipesIdInstructionResponses = {
  "201": PutApiV1RecipesIdInstructionStatus201;
};

/**
 * @description Union of all possible responses
 */
export type PutApiV1RecipesIdInstructionResponse = PutApiV1RecipesIdInstructionStatus201;
