/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { GithubComDomicileappDomicileInternalDbRecipe } from "./githubComDomicileappDomicileInternalDb/Recipe";
import type { InternalRecipesUpdateInstructionRequest } from "./internalRecipes/UpdateInstructionRequest";

export type UpdateRecipeInstructionPath = {
  /**
   * @description Recipe ID
   * @type integer
   */
  id: number;
};

export type UpdateRecipeInstructionStatus201 = GithubComDomicileappDomicileInternalDbRecipe;

/**
 * @description Instruction data
 */
export type UpdateRecipeInstructionBody = object | InternalRecipesUpdateInstructionRequest;

export type UpdateRecipeInstructionOptions = {
  body: UpdateRecipeInstructionBody;
  path: UpdateRecipeInstructionPath;
  query?: never;
  headers?: never;
};

export type UpdateRecipeInstructionResponses = {
  "201": UpdateRecipeInstructionStatus201;
};

/**
 * @description Union of all possible responses
 */
export type UpdateRecipeInstructionResponse = UpdateRecipeInstructionStatus201;
