/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { GithubComDomicileappDomicileInternalDbRecipe } from "./githubComDomicileappDomicileInternalDb/Recipe";
import type { InternalRecipesUpdateIngredientRequest } from "./internalRecipes/UpdateIngredientRequest";

export type UpdateRecipeIngredientPath = {
  /**
   * @description Recipe ID
   * @type integer
   */
  id: number;
};

export type UpdateRecipeIngredientStatus201 = GithubComDomicileappDomicileInternalDbRecipe;

/**
 * @description Ingredient data
 */
export type UpdateRecipeIngredientBody = object | InternalRecipesUpdateIngredientRequest;

export type UpdateRecipeIngredientOptions = {
  body: UpdateRecipeIngredientBody;
  path: UpdateRecipeIngredientPath;
  query?: never;
  headers?: never;
};

export type UpdateRecipeIngredientResponses = {
  "201": UpdateRecipeIngredientStatus201;
};

/**
 * @description Union of all possible responses
 */
export type UpdateRecipeIngredientResponse = UpdateRecipeIngredientStatus201;
