/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { GithubComDomicileappDomicileInternalDbRecipe } from "./githubComDomicileappDomicileInternalDb/Recipe";
import type { InternalRecipesUpdateRecipeRequest } from "./internalRecipes/UpdateRecipeRequest";

export type UpdateRecipeStatus204 = GithubComDomicileappDomicileInternalDbRecipe;

/**
 * @description Recipe data
 */
export type UpdateRecipeBody = object | InternalRecipesUpdateRecipeRequest;

export type UpdateRecipeOptions = {
  body: UpdateRecipeBody;
  path?: never;
  query?: never;
  headers?: never;
};

export type UpdateRecipeResponses = {
  "204": UpdateRecipeStatus204;
};

/**
 * @description Union of all possible responses
 */
export type UpdateRecipeResponse = UpdateRecipeStatus204;
