/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from "zod";

export const internalRecipesCreateInstructionRequestSchema = z.object({
  content: z.string().optional(),
  group_name: z.string().optional(),
  sort_order: z.number().optional(),
});
