/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from "zod";

export const internalRecipesUpdateRecipeRequestSchema = z.object({
  name: z.string().optional(),
  short_description: z.string().optional(),
});
