/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from "zod";

export const internalRecipesUpdateIngredientRequestSchema = z.object({
  raw_text: z.string().optional(),
  sort_order: z.number().optional(),
});
