/**
 * Generated by Orval
 * Do not edit manually.
 * Domicile API
 * Domicile's REST API
 */
import type { RecipesCreateInstructionRequest } from './recipesCreateInstructionRequest.ts';

export type CreateRecipeInstructionBody = { [key: string]: unknown } | RecipesCreateInstructionRequest;
