/**
 * Generated by Orval
 * Do not edit manually.
 * Domicile API
 * Domicile's REST API
 */
import type { RecipesCreateRecipeRequest } from './recipesCreateRecipeRequest.ts';

export type CreateRecipeBody = { [key: string]: unknown } | RecipesCreateRecipeRequest;
