/**
 * Generated by Orval
 * Do not edit manually.
 * Domicile API
 * Domicile's REST API
 */
import type { RecipesCreateIngredientRequest } from './recipesCreateIngredientRequest.ts';

export type CreateRecipeIngredientBody = { [key: string]: unknown } | RecipesCreateIngredientRequest;
