/**
 * Generated by Orval
 * Do not edit manually.
 * Domicile API
 * Domicile's REST API
 */

export interface GithubComDomicileappDomicileInternalDbListRecipeIngredientsRow {
  group_name?: string;
  id?: number;
  ingredient_name?: string;
  parse_status?: string;
  preparation?: string;
  quantity?: number;
  raw_text?: string;
  recipe_id?: number;
  sort_order?: number;
  unit?: string;
}
