/**
 * Generated by Orval
 * Do not edit manually.
 * Domicile API
 * Domicile's REST API
 */

export interface GithubComDomicileappDomicileInternalDbListRecipeInstructionsRow {
  content?: string;
  group_name?: string;
  id?: number;
  recipe_id?: number;
  sort_order?: number;
}
