/**
 * Generated by Orval
 * Do not edit manually.
 * Domicile API
 * Domicile's REST API
 */

export interface GithubComDomicileappDomicileInternalDbRecipeInstruction {
  content?: string;
  created_at?: string;
  group_name?: string;
  id?: number;
  recipe_id?: number;
  sort_order?: number;
  updated_at?: string;
}
