/**
 * Generated by Orval
 * Do not edit manually.
 * Domicile API
 * Domicile's REST API
 */

export interface GithubComDomicileappDomicileInternalDbRecipe {
  cook_time?: string;
  created_at?: string;
  deleted_at?: string;
  id?: number;
  name?: string;
  notes?: string;
  nutrition?: string;
  photo_url?: string;
  prep_time?: string;
  servings?: string;
  short_description?: string;
  source?: string;
  updated_at?: string;
}
