/**
 * Generated by Orval
 * Do not edit manually.
 * Domicile API
 * Domicile's REST API
 */
import type { RecipesImportRecipeRequest } from './recipesImportRecipeRequest.ts';

export type ImportRecipeBody = { [key: string]: unknown } | RecipesImportRecipeRequest;
