/**
 * Generated by Orval
 * Do not edit manually.
 * Domicile API
 * Domicile's REST API
 */

export type ListRecipesParams = {
/**
 * Page number (default: 1)
 */
page?: number;
/**
 * Page size (default: 12)
 */
size?: number;
/**
 * Search params
 */
search?: number;
/**
 * Sort field
 */
sort?: number;
/**
 * Sort direction
 */
direction?: number;
};
