/**
 * Generated by Orval
 * Do not edit manually.
 * Domicile API
 * Domicile's REST API
 */

export type ListRecipesDirection = typeof ListRecipesDirection[keyof typeof ListRecipesDirection];


export const ListRecipesDirection = {
  asc: 'asc',
  desc: 'desc',
} as const;
