/**
 * Generated by Orval
 * Do not edit manually.
 * Domicile API
 * Domicile's REST API
 */

export type ListRecipesSort = typeof ListRecipesSort[keyof typeof ListRecipesSort];


export const ListRecipesSort = {
  id: 'id',
  name: 'name',
  created_at: 'created_at',
  updated_at: 'updated_at',
} as const;
