/**
 * Generated by Orval
 * Do not edit manually.
 * Domicile API
 * Domicile's REST API
 */
import type { GithubComDomicileappDomicileInternalDbListRecipesRow } from './githubComDomicileappDomicileInternalDbListRecipesRow.ts';

export interface RecipesPaginatedResponse {
  items?: GithubComDomicileappDomicileInternalDbListRecipesRow[];
  page?: number;
  size?: number;
  total_items?: number;
  total_pages?: number;
}
