/**
 * Generated by Orval
 * Do not edit manually.
 * Domicile API
 * Domicile's REST API
 */

export interface RecipesUpdateIngredientRequest {
  group_name?: string;
  raw_text?: string;
  sort_order?: number;
}
