/**
 * Generated by Orval
 * Do not edit manually.
 * Domicile API
 * Domicile's REST API
 */

export interface RecipesCreateInstructionRequest {
  content?: string;
  group_name?: string;
  sort_order?: number;
}
