/**
 * Generated by Orval
 * Do not edit manually.
 * Domicile API
 * Domicile's REST API
 */

export interface RecipesCreateRecipeRequest {
  name?: string;
  photo_url?: string;
  short_description?: string;
}
