/**
 * Generated by Orval
 * Do not edit manually.
 * Domicile API
 * Domicile's REST API
 */
import type { RecipesUpdateIngredientRequest } from './recipesUpdateIngredientRequest.ts';

export type UpdateRecipeIngredientBody = { [key: string]: unknown } | RecipesUpdateIngredientRequest;
