/**
 * Generated by Orval
 * Do not edit manually.
 * Domicile API
 * Domicile's REST API
 */
import type { RecipesUpdateRecipeRequest } from './recipesUpdateRecipeRequest.ts';

export type UpdateRecipeBody = { [key: string]: unknown } | RecipesUpdateRecipeRequest;
