/**
 * Generated by Orval
 * Do not edit manually.
 * Domicile API
 * Domicile's REST API
 */
import type { RecipesUpdateInstructionRequest } from './recipesUpdateInstructionRequest.ts';

export type UpdateRecipeInstructionBody = { [key: string]: unknown } | RecipesUpdateInstructionRequest;
