/**
 * Generated by Orval
 * Do not edit manually.
 * Domicile API
 * Domicile's REST API
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateRecipeBody,
  CreateRecipeIngredientBody,
  CreateRecipeInstructionBody,
  DeleteApiV1RecipesIdIngredientBody,
  DeleteRecipeBody,
  DeleteRecipeInstructionBody,
  GetRecipeBody,
  GithubComDomicileappDomicileInternalDbRecipe,
  GithubComDomicileappDomicileInternalDbRecipeIngredient,
  GithubComDomicileappDomicileInternalDbRecipeInstruction,
  ListRecipesBody,
  ListRecipesParams,
  RecipesPaginatedResponse,
  RecipesRecipeResponse,
  UpdateRecipeBody,
  UpdateRecipeIngredientBody,
  UpdateRecipeInstructionBody
} from '../../schemas';





const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type listRecipesResponse200 = {
  data: RecipesPaginatedResponse
  status: 200
}

export type listRecipesResponseSuccess = (listRecipesResponse200) & {
  headers: Headers;
};
;

export type listRecipesResponse = (listRecipesResponseSuccess)

export const getListRecipesUrl = (params?: ListRecipesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/recipes?${stringifiedParams}` : `/api/v1/recipes`
}

/**
 * Get list of all recipes
 * @summary List recipes
 */
export const listRecipes = async (listRecipesBody?: ListRecipesBody,
    params?: ListRecipesParams, options?: RequestInit): Promise<listRecipesResponse> => {

  const res = await fetch(getListRecipesUrl(params),
  {
    ...options,
    method: 'GET',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(listRecipesBody)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: listRecipesResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as listRecipesResponse
}





export const getListRecipesQueryKey = (listRecipesBody?: ListRecipesBody,
    params?: ListRecipesParams,) => {
    return [
    `/api/v1/recipes`, ...(params ? [params] : []), listRecipesBody
    ] as const;
    }


export const getListRecipesQueryOptions = <TData = Awaited<ReturnType<typeof listRecipes>>, TError = unknown>(listRecipesBody?: ListRecipesBody,
    params?: ListRecipesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listRecipes>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListRecipesQueryKey(listRecipesBody,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listRecipes>>> = ({ signal }) => listRecipes(listRecipesBody,params, { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listRecipes>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListRecipesQueryResult = NonNullable<Awaited<ReturnType<typeof listRecipes>>>
export type ListRecipesQueryError = unknown


export function useListRecipes<TData = Awaited<ReturnType<typeof listRecipes>>, TError = unknown>(
 listRecipesBody: undefined |  ListRecipesBody,
    params: undefined |  ListRecipesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listRecipes>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listRecipes>>,
          TError,
          Awaited<ReturnType<typeof listRecipes>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListRecipes<TData = Awaited<ReturnType<typeof listRecipes>>, TError = unknown>(
 listRecipesBody?: ListRecipesBody,
    params?: ListRecipesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listRecipes>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listRecipes>>,
          TError,
          Awaited<ReturnType<typeof listRecipes>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListRecipes<TData = Awaited<ReturnType<typeof listRecipes>>, TError = unknown>(
 listRecipesBody?: ListRecipesBody,
    params?: ListRecipesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listRecipes>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List recipes
 */

export function useListRecipes<TData = Awaited<ReturnType<typeof listRecipes>>, TError = unknown>(
 listRecipesBody?: ListRecipesBody,
    params?: ListRecipesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listRecipes>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListRecipesQueryOptions(listRecipesBody,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type createRecipeResponse200 = {
  data: GithubComDomicileappDomicileInternalDbRecipe
  status: 200
}

export type createRecipeResponseSuccess = (createRecipeResponse200) & {
  headers: Headers;
};
;

export type createRecipeResponse = (createRecipeResponseSuccess)

export const getCreateRecipeUrl = () => {




  return `/api/v1/recipes`
}

/**
 * @summary Create recipe
 */
export const createRecipe = async (createRecipeBody: CreateRecipeBody, options?: RequestInit): Promise<createRecipeResponse> => {

  const res = await fetch(getCreateRecipeUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createRecipeBody)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: createRecipeResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as createRecipeResponse
}





export const getCreateRecipeMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createRecipe>>, TError,{data: CreateRecipeBody}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof createRecipe>>, TError,{data: CreateRecipeBody}, TContext> => {

const mutationKey = ['createRecipe'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createRecipe>>, {data: CreateRecipeBody}> = (props) => {
          const {data} = props ?? {};

          return  createRecipe(data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateRecipeMutationResult = NonNullable<Awaited<ReturnType<typeof createRecipe>>>
    export type CreateRecipeMutationBody = CreateRecipeBody
    export type CreateRecipeMutationError = unknown

    /**
 * @summary Create recipe
 */
export const useCreateRecipe = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createRecipe>>, TError,{data: CreateRecipeBody}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createRecipe>>,
        TError,
        {data: CreateRecipeBody},
        TContext
      > => {
      return useMutation(getCreateRecipeMutationOptions(options), queryClient);
    }
    export type deleteRecipeResponse204 = {
  data: void
  status: 204
}

export type deleteRecipeResponseSuccess = (deleteRecipeResponse204) & {
  headers: Headers;
};
;

export type deleteRecipeResponse = (deleteRecipeResponseSuccess)

export const getDeleteRecipeUrl = (id: number,) => {




  return `/api/v1/recipes/${encodeURIComponent(String(id))}`
}

/**
 * @summary Delete recipe
 */
export const deleteRecipe = async (id: number,
    deleteRecipeBody?: DeleteRecipeBody, options?: RequestInit): Promise<deleteRecipeResponse> => {

  const res = await fetch(getDeleteRecipeUrl(id),
  {
    ...options,
    method: 'DELETE',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(deleteRecipeBody)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: deleteRecipeResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as deleteRecipeResponse
}





export const getDeleteRecipeMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteRecipe>>, TError,{id: number;data?: DeleteRecipeBody}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof deleteRecipe>>, TError,{id: number;data?: DeleteRecipeBody}, TContext> => {

const mutationKey = ['deleteRecipe'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteRecipe>>, {id: number;data?: DeleteRecipeBody}> = (props) => {
          const {id,data} = props ?? {};

          return  deleteRecipe(id,data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteRecipeMutationResult = NonNullable<Awaited<ReturnType<typeof deleteRecipe>>>
    export type DeleteRecipeMutationBody = DeleteRecipeBody | undefined
    export type DeleteRecipeMutationError = unknown

    /**
 * @summary Delete recipe
 */
export const useDeleteRecipe = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteRecipe>>, TError,{id: number;data?: DeleteRecipeBody}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteRecipe>>,
        TError,
        {id: number;data?: DeleteRecipeBody},
        TContext
      > => {
      return useMutation(getDeleteRecipeMutationOptions(options), queryClient);
    }
    export type getRecipeResponse200 = {
  data: RecipesRecipeResponse
  status: 200
}

export type getRecipeResponseSuccess = (getRecipeResponse200) & {
  headers: Headers;
};
;

export type getRecipeResponse = (getRecipeResponseSuccess)

export const getGetRecipeUrl = (id: number,) => {




  return `/api/v1/recipes/${encodeURIComponent(String(id))}`
}

/**
 * @summary Get recipe by ID
 */
export const getRecipe = async (id: number,
    getRecipeBody?: GetRecipeBody, options?: RequestInit): Promise<getRecipeResponse> => {

  const res = await fetch(getGetRecipeUrl(id),
  {
    ...options,
    method: 'GET',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(getRecipeBody)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getRecipeResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getRecipeResponse
}





export const getGetRecipeQueryKey = (id: number,
    getRecipeBody?: GetRecipeBody,) => {
    return [
    `/api/v1/recipes/${id}`, getRecipeBody
    ] as const;
    }


export const getGetRecipeQueryOptions = <TData = Awaited<ReturnType<typeof getRecipe>>, TError = unknown>(id: number,
    getRecipeBody?: GetRecipeBody, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRecipe>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetRecipeQueryKey(id,getRecipeBody);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getRecipe>>> = ({ signal }) => getRecipe(id,getRecipeBody, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getRecipe>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetRecipeQueryResult = NonNullable<Awaited<ReturnType<typeof getRecipe>>>
export type GetRecipeQueryError = unknown


export function useGetRecipe<TData = Awaited<ReturnType<typeof getRecipe>>, TError = unknown>(
 id: number,
    getRecipeBody: undefined |  GetRecipeBody, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRecipe>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRecipe>>,
          TError,
          Awaited<ReturnType<typeof getRecipe>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetRecipe<TData = Awaited<ReturnType<typeof getRecipe>>, TError = unknown>(
 id: number,
    getRecipeBody?: GetRecipeBody, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRecipe>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRecipe>>,
          TError,
          Awaited<ReturnType<typeof getRecipe>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetRecipe<TData = Awaited<ReturnType<typeof getRecipe>>, TError = unknown>(
 id: number,
    getRecipeBody?: GetRecipeBody, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRecipe>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get recipe by ID
 */

export function useGetRecipe<TData = Awaited<ReturnType<typeof getRecipe>>, TError = unknown>(
 id: number,
    getRecipeBody?: GetRecipeBody, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRecipe>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetRecipeQueryOptions(id,getRecipeBody,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type updateRecipeResponse204 = {
  data: GithubComDomicileappDomicileInternalDbRecipe
  status: 204
}

export type updateRecipeResponseSuccess = (updateRecipeResponse204) & {
  headers: Headers;
};
;

export type updateRecipeResponse = (updateRecipeResponseSuccess)

export const getUpdateRecipeUrl = (id: number,) => {




  return `/api/v1/recipes/${encodeURIComponent(String(id))}`
}

/**
 * @summary Update recipe
 */
export const updateRecipe = async (id: number,
    updateRecipeBody: UpdateRecipeBody, options?: RequestInit): Promise<updateRecipeResponse> => {

  const res = await fetch(getUpdateRecipeUrl(id),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateRecipeBody)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: updateRecipeResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as updateRecipeResponse
}





export const getUpdateRecipeMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateRecipe>>, TError,{id: number;data: UpdateRecipeBody}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof updateRecipe>>, TError,{id: number;data: UpdateRecipeBody}, TContext> => {

const mutationKey = ['updateRecipe'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateRecipe>>, {id: number;data: UpdateRecipeBody}> = (props) => {
          const {id,data} = props ?? {};

          return  updateRecipe(id,data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateRecipeMutationResult = NonNullable<Awaited<ReturnType<typeof updateRecipe>>>
    export type UpdateRecipeMutationBody = UpdateRecipeBody
    export type UpdateRecipeMutationError = unknown

    /**
 * @summary Update recipe
 */
export const useUpdateRecipe = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateRecipe>>, TError,{id: number;data: UpdateRecipeBody}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateRecipe>>,
        TError,
        {id: number;data: UpdateRecipeBody},
        TContext
      > => {
      return useMutation(getUpdateRecipeMutationOptions(options), queryClient);
    }
    export type deleteApiV1RecipesIdIngredientResponse204 = {
  data: GithubComDomicileappDomicileInternalDbRecipe
  status: 204
}

export type deleteApiV1RecipesIdIngredientResponseSuccess = (deleteApiV1RecipesIdIngredientResponse204) & {
  headers: Headers;
};
;

export type deleteApiV1RecipesIdIngredientResponse = (deleteApiV1RecipesIdIngredientResponseSuccess)

export const getDeleteApiV1RecipesIdIngredientUrl = (id: number,) => {




  return `/api/v1/recipes/${encodeURIComponent(String(id))}/ingredient`
}

/**
 * @summary Delete recipe ingredient
 */
export const deleteApiV1RecipesIdIngredient = async (id: number,
    deleteApiV1RecipesIdIngredientBody?: DeleteApiV1RecipesIdIngredientBody, options?: RequestInit): Promise<deleteApiV1RecipesIdIngredientResponse> => {

  const res = await fetch(getDeleteApiV1RecipesIdIngredientUrl(id),
  {
    ...options,
    method: 'DELETE',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(deleteApiV1RecipesIdIngredientBody)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: deleteApiV1RecipesIdIngredientResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as deleteApiV1RecipesIdIngredientResponse
}





export const getDeleteApiV1RecipesIdIngredientMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1RecipesIdIngredient>>, TError,{id: number;data?: DeleteApiV1RecipesIdIngredientBody}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1RecipesIdIngredient>>, TError,{id: number;data?: DeleteApiV1RecipesIdIngredientBody}, TContext> => {

const mutationKey = ['deleteApiV1RecipesIdIngredient'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiV1RecipesIdIngredient>>, {id: number;data?: DeleteApiV1RecipesIdIngredientBody}> = (props) => {
          const {id,data} = props ?? {};

          return  deleteApiV1RecipesIdIngredient(id,data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiV1RecipesIdIngredientMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiV1RecipesIdIngredient>>>
    export type DeleteApiV1RecipesIdIngredientMutationBody = DeleteApiV1RecipesIdIngredientBody | undefined
    export type DeleteApiV1RecipesIdIngredientMutationError = unknown

    /**
 * @summary Delete recipe ingredient
 */
export const useDeleteApiV1RecipesIdIngredient = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1RecipesIdIngredient>>, TError,{id: number;data?: DeleteApiV1RecipesIdIngredientBody}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiV1RecipesIdIngredient>>,
        TError,
        {id: number;data?: DeleteApiV1RecipesIdIngredientBody},
        TContext
      > => {
      return useMutation(getDeleteApiV1RecipesIdIngredientMutationOptions(options), queryClient);
    }
    export type updateRecipeIngredientResponse201 = {
  data: GithubComDomicileappDomicileInternalDbRecipe
  status: 201
}

export type updateRecipeIngredientResponseSuccess = (updateRecipeIngredientResponse201) & {
  headers: Headers;
};
;

export type updateRecipeIngredientResponse = (updateRecipeIngredientResponseSuccess)

export const getUpdateRecipeIngredientUrl = (id: number,) => {




  return `/api/v1/recipes/${encodeURIComponent(String(id))}/ingredient`
}

/**
 * @summary Update recipe ingredient
 */
export const updateRecipeIngredient = async (id: number,
    updateRecipeIngredientBody: UpdateRecipeIngredientBody, options?: RequestInit): Promise<updateRecipeIngredientResponse> => {

  const res = await fetch(getUpdateRecipeIngredientUrl(id),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateRecipeIngredientBody)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: updateRecipeIngredientResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as updateRecipeIngredientResponse
}





export const getUpdateRecipeIngredientMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateRecipeIngredient>>, TError,{id: number;data: UpdateRecipeIngredientBody}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof updateRecipeIngredient>>, TError,{id: number;data: UpdateRecipeIngredientBody}, TContext> => {

const mutationKey = ['updateRecipeIngredient'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateRecipeIngredient>>, {id: number;data: UpdateRecipeIngredientBody}> = (props) => {
          const {id,data} = props ?? {};

          return  updateRecipeIngredient(id,data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateRecipeIngredientMutationResult = NonNullable<Awaited<ReturnType<typeof updateRecipeIngredient>>>
    export type UpdateRecipeIngredientMutationBody = UpdateRecipeIngredientBody
    export type UpdateRecipeIngredientMutationError = unknown

    /**
 * @summary Update recipe ingredient
 */
export const useUpdateRecipeIngredient = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateRecipeIngredient>>, TError,{id: number;data: UpdateRecipeIngredientBody}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateRecipeIngredient>>,
        TError,
        {id: number;data: UpdateRecipeIngredientBody},
        TContext
      > => {
      return useMutation(getUpdateRecipeIngredientMutationOptions(options), queryClient);
    }
    export type createRecipeIngredientResponse201 = {
  data: GithubComDomicileappDomicileInternalDbRecipeIngredient
  status: 201
}

export type createRecipeIngredientResponseSuccess = (createRecipeIngredientResponse201) & {
  headers: Headers;
};
;

export type createRecipeIngredientResponse = (createRecipeIngredientResponseSuccess)

export const getCreateRecipeIngredientUrl = (id: number,) => {




  return `/api/v1/recipes/${encodeURIComponent(String(id))}/ingredients`
}

/**
 * @summary Create recipe ingredient
 */
export const createRecipeIngredient = async (id: number,
    createRecipeIngredientBody: CreateRecipeIngredientBody, options?: RequestInit): Promise<createRecipeIngredientResponse> => {

  const res = await fetch(getCreateRecipeIngredientUrl(id),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createRecipeIngredientBody)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: createRecipeIngredientResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as createRecipeIngredientResponse
}





export const getCreateRecipeIngredientMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createRecipeIngredient>>, TError,{id: number;data: CreateRecipeIngredientBody}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof createRecipeIngredient>>, TError,{id: number;data: CreateRecipeIngredientBody}, TContext> => {

const mutationKey = ['createRecipeIngredient'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createRecipeIngredient>>, {id: number;data: CreateRecipeIngredientBody}> = (props) => {
          const {id,data} = props ?? {};

          return  createRecipeIngredient(id,data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateRecipeIngredientMutationResult = NonNullable<Awaited<ReturnType<typeof createRecipeIngredient>>>
    export type CreateRecipeIngredientMutationBody = CreateRecipeIngredientBody
    export type CreateRecipeIngredientMutationError = unknown

    /**
 * @summary Create recipe ingredient
 */
export const useCreateRecipeIngredient = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createRecipeIngredient>>, TError,{id: number;data: CreateRecipeIngredientBody}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createRecipeIngredient>>,
        TError,
        {id: number;data: CreateRecipeIngredientBody},
        TContext
      > => {
      return useMutation(getCreateRecipeIngredientMutationOptions(options), queryClient);
    }
    export type deleteRecipeInstructionResponse204 = {
  data: GithubComDomicileappDomicileInternalDbRecipe
  status: 204
}

export type deleteRecipeInstructionResponseSuccess = (deleteRecipeInstructionResponse204) & {
  headers: Headers;
};
;

export type deleteRecipeInstructionResponse = (deleteRecipeInstructionResponseSuccess)

export const getDeleteRecipeInstructionUrl = (id: number,) => {




  return `/api/v1/recipes/${encodeURIComponent(String(id))}/instruction`
}

/**
 * @summary Delete recipe instruction
 */
export const deleteRecipeInstruction = async (id: number,
    deleteRecipeInstructionBody?: DeleteRecipeInstructionBody, options?: RequestInit): Promise<deleteRecipeInstructionResponse> => {

  const res = await fetch(getDeleteRecipeInstructionUrl(id),
  {
    ...options,
    method: 'DELETE',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(deleteRecipeInstructionBody)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: deleteRecipeInstructionResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as deleteRecipeInstructionResponse
}





export const getDeleteRecipeInstructionMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteRecipeInstruction>>, TError,{id: number;data?: DeleteRecipeInstructionBody}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof deleteRecipeInstruction>>, TError,{id: number;data?: DeleteRecipeInstructionBody}, TContext> => {

const mutationKey = ['deleteRecipeInstruction'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteRecipeInstruction>>, {id: number;data?: DeleteRecipeInstructionBody}> = (props) => {
          const {id,data} = props ?? {};

          return  deleteRecipeInstruction(id,data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteRecipeInstructionMutationResult = NonNullable<Awaited<ReturnType<typeof deleteRecipeInstruction>>>
    export type DeleteRecipeInstructionMutationBody = DeleteRecipeInstructionBody | undefined
    export type DeleteRecipeInstructionMutationError = unknown

    /**
 * @summary Delete recipe instruction
 */
export const useDeleteRecipeInstruction = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteRecipeInstruction>>, TError,{id: number;data?: DeleteRecipeInstructionBody}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteRecipeInstruction>>,
        TError,
        {id: number;data?: DeleteRecipeInstructionBody},
        TContext
      > => {
      return useMutation(getDeleteRecipeInstructionMutationOptions(options), queryClient);
    }
    export type updateRecipeInstructionResponse201 = {
  data: GithubComDomicileappDomicileInternalDbRecipe
  status: 201
}

export type updateRecipeInstructionResponseSuccess = (updateRecipeInstructionResponse201) & {
  headers: Headers;
};
;

export type updateRecipeInstructionResponse = (updateRecipeInstructionResponseSuccess)

export const getUpdateRecipeInstructionUrl = (id: number,) => {




  return `/api/v1/recipes/${encodeURIComponent(String(id))}/instruction`
}

/**
 * @summary Update recipe instruction
 */
export const updateRecipeInstruction = async (id: number,
    updateRecipeInstructionBody: UpdateRecipeInstructionBody, options?: RequestInit): Promise<updateRecipeInstructionResponse> => {

  const res = await fetch(getUpdateRecipeInstructionUrl(id),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateRecipeInstructionBody)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: updateRecipeInstructionResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as updateRecipeInstructionResponse
}





export const getUpdateRecipeInstructionMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateRecipeInstruction>>, TError,{id: number;data: UpdateRecipeInstructionBody}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof updateRecipeInstruction>>, TError,{id: number;data: UpdateRecipeInstructionBody}, TContext> => {

const mutationKey = ['updateRecipeInstruction'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateRecipeInstruction>>, {id: number;data: UpdateRecipeInstructionBody}> = (props) => {
          const {id,data} = props ?? {};

          return  updateRecipeInstruction(id,data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateRecipeInstructionMutationResult = NonNullable<Awaited<ReturnType<typeof updateRecipeInstruction>>>
    export type UpdateRecipeInstructionMutationBody = UpdateRecipeInstructionBody
    export type UpdateRecipeInstructionMutationError = unknown

    /**
 * @summary Update recipe instruction
 */
export const useUpdateRecipeInstruction = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateRecipeInstruction>>, TError,{id: number;data: UpdateRecipeInstructionBody}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateRecipeInstruction>>,
        TError,
        {id: number;data: UpdateRecipeInstructionBody},
        TContext
      > => {
      return useMutation(getUpdateRecipeInstructionMutationOptions(options), queryClient);
    }
    export type createRecipeInstructionResponse201 = {
  data: GithubComDomicileappDomicileInternalDbRecipeInstruction
  status: 201
}

export type createRecipeInstructionResponseSuccess = (createRecipeInstructionResponse201) & {
  headers: Headers;
};
;

export type createRecipeInstructionResponse = (createRecipeInstructionResponseSuccess)

export const getCreateRecipeInstructionUrl = (id: number,) => {




  return `/api/v1/recipes/${encodeURIComponent(String(id))}/instructions`
}

/**
 * @summary Create recipe instruction
 */
export const createRecipeInstruction = async (id: number,
    createRecipeInstructionBody: CreateRecipeInstructionBody, options?: RequestInit): Promise<createRecipeInstructionResponse> => {

  const res = await fetch(getCreateRecipeInstructionUrl(id),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createRecipeInstructionBody)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: createRecipeInstructionResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as createRecipeInstructionResponse
}





export const getCreateRecipeInstructionMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createRecipeInstruction>>, TError,{id: number;data: CreateRecipeInstructionBody}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof createRecipeInstruction>>, TError,{id: number;data: CreateRecipeInstructionBody}, TContext> => {

const mutationKey = ['createRecipeInstruction'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createRecipeInstruction>>, {id: number;data: CreateRecipeInstructionBody}> = (props) => {
          const {id,data} = props ?? {};

          return  createRecipeInstruction(id,data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateRecipeInstructionMutationResult = NonNullable<Awaited<ReturnType<typeof createRecipeInstruction>>>
    export type CreateRecipeInstructionMutationBody = CreateRecipeInstructionBody
    export type CreateRecipeInstructionMutationError = unknown

    /**
 * @summary Create recipe instruction
 */
export const useCreateRecipeInstruction = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createRecipeInstruction>>, TError,{id: number;data: CreateRecipeInstructionBody}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createRecipeInstruction>>,
        TError,
        {id: number;data: CreateRecipeInstructionBody},
        TContext
      > => {
      return useMutation(getCreateRecipeInstructionMutationOptions(options), queryClient);
    }
