/**
 * Generated by Orval
 * Do not edit manually.
 * Domicile API
 * Domicile's REST API
 */
import {
  HttpResponse,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  GithubComDomicileappDomicileInternalDbRecipe,
  GithubComDomicileappDomicileInternalDbRecipeIngredient,
  GithubComDomicileappDomicileInternalDbRecipeInstruction,
  RecipesPaginatedResponse,
  RecipesRecipeResponse
} from '../../schemas';

import {
  getCreateRecipeIngredientResponseMock,
  getCreateRecipeInstructionResponseMock,
  getCreateRecipeResponseMock,
  getDeleteApiV1RecipesIdIngredientResponseMock,
  getDeleteRecipeInstructionResponseMock,
  getGetRecipeResponseMock,
  getImportRecipeResponseMock,
  getListRecipesResponseMock,
  getUpdateRecipeIngredientResponseMock,
  getUpdateRecipeInstructionResponseMock,
  getUpdateRecipeResponseMock
} from './recipes.faker.ts';

export { getListRecipesResponseMock, getCreateRecipeResponseMock, getImportRecipeResponseMock, getGetRecipeResponseMock, getUpdateRecipeResponseMock, getDeleteApiV1RecipesIdIngredientResponseMock, getUpdateRecipeIngredientResponseMock, getCreateRecipeIngredientResponseMock, getDeleteRecipeInstructionResponseMock, getUpdateRecipeInstructionResponseMock, getCreateRecipeInstructionResponseMock } from './recipes.faker.ts';


export const getListRecipesMockHandler = (overrideResponse?: RecipesPaginatedResponse | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<RecipesPaginatedResponse> | RecipesPaginatedResponse), options?: RequestHandlerOptions) => {
  return http.get('*/api/v1/recipes', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getListRecipesResponseMock(),
      { status: 200
      })
  }, options)
}

export const getCreateRecipeMockHandler = (overrideResponse?: GithubComDomicileappDomicileInternalDbRecipe | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<GithubComDomicileappDomicileInternalDbRecipe> | GithubComDomicileappDomicileInternalDbRecipe), options?: RequestHandlerOptions) => {
  return http.post('*/api/v1/recipes', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getCreateRecipeResponseMock(),
      { status: 200
      })
  }, options)
}

export const getImportRecipeMockHandler = (overrideResponse?: RecipesRecipeResponse | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<RecipesRecipeResponse> | RecipesRecipeResponse), options?: RequestHandlerOptions) => {
  return http.post('*/api/v1/recipes/import', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getImportRecipeResponseMock(),
      { status: 201
      })
  }, options)
}

export const getDeleteRecipeMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.delete('*/api/v1/recipes/:id', async (info: Parameters<Parameters<typeof http.delete>[1]>[0]) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }

    return new HttpResponse(null,
      { status: 204
      })
  }, options)
}

export const getGetRecipeMockHandler = (overrideResponse?: RecipesRecipeResponse | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<RecipesRecipeResponse> | RecipesRecipeResponse), options?: RequestHandlerOptions) => {
  return http.get('*/api/v1/recipes/:id', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetRecipeResponseMock(),
      { status: 200
      })
  }, options)
}

export const getUpdateRecipeMockHandler = (overrideResponse?: GithubComDomicileappDomicileInternalDbRecipe | ((info: Parameters<Parameters<typeof http.put>[1]>[0]) => Promise<GithubComDomicileappDomicileInternalDbRecipe> | GithubComDomicileappDomicileInternalDbRecipe), options?: RequestHandlerOptions) => {
  return http.put('*/api/v1/recipes/:id', async (info: Parameters<Parameters<typeof http.put>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getUpdateRecipeResponseMock(),
      { status: 204
      })
  }, options)
}

export const getDeleteApiV1RecipesIdIngredientMockHandler = (overrideResponse?: GithubComDomicileappDomicileInternalDbRecipe | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<GithubComDomicileappDomicileInternalDbRecipe> | GithubComDomicileappDomicileInternalDbRecipe), options?: RequestHandlerOptions) => {
  return http.delete('*/api/v1/recipes/:id/ingredient', async (info: Parameters<Parameters<typeof http.delete>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getDeleteApiV1RecipesIdIngredientResponseMock(),
      { status: 204
      })
  }, options)
}

export const getUpdateRecipeIngredientMockHandler = (overrideResponse?: GithubComDomicileappDomicileInternalDbRecipe | ((info: Parameters<Parameters<typeof http.put>[1]>[0]) => Promise<GithubComDomicileappDomicileInternalDbRecipe> | GithubComDomicileappDomicileInternalDbRecipe), options?: RequestHandlerOptions) => {
  return http.put('*/api/v1/recipes/:id/ingredient', async (info: Parameters<Parameters<typeof http.put>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getUpdateRecipeIngredientResponseMock(),
      { status: 201
      })
  }, options)
}

export const getCreateRecipeIngredientMockHandler = (overrideResponse?: GithubComDomicileappDomicileInternalDbRecipeIngredient | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<GithubComDomicileappDomicileInternalDbRecipeIngredient> | GithubComDomicileappDomicileInternalDbRecipeIngredient), options?: RequestHandlerOptions) => {
  return http.post('*/api/v1/recipes/:id/ingredients', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getCreateRecipeIngredientResponseMock(),
      { status: 201
      })
  }, options)
}

export const getDeleteRecipeInstructionMockHandler = (overrideResponse?: GithubComDomicileappDomicileInternalDbRecipe | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<GithubComDomicileappDomicileInternalDbRecipe> | GithubComDomicileappDomicileInternalDbRecipe), options?: RequestHandlerOptions) => {
  return http.delete('*/api/v1/recipes/:id/instruction', async (info: Parameters<Parameters<typeof http.delete>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getDeleteRecipeInstructionResponseMock(),
      { status: 204
      })
  }, options)
}

export const getUpdateRecipeInstructionMockHandler = (overrideResponse?: GithubComDomicileappDomicileInternalDbRecipe | ((info: Parameters<Parameters<typeof http.put>[1]>[0]) => Promise<GithubComDomicileappDomicileInternalDbRecipe> | GithubComDomicileappDomicileInternalDbRecipe), options?: RequestHandlerOptions) => {
  return http.put('*/api/v1/recipes/:id/instruction', async (info: Parameters<Parameters<typeof http.put>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getUpdateRecipeInstructionResponseMock(),
      { status: 201
      })
  }, options)
}

export const getCreateRecipeInstructionMockHandler = (overrideResponse?: GithubComDomicileappDomicileInternalDbRecipeInstruction | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<GithubComDomicileappDomicileInternalDbRecipeInstruction> | GithubComDomicileappDomicileInternalDbRecipeInstruction), options?: RequestHandlerOptions) => {
  return http.post('*/api/v1/recipes/:id/instructions', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getCreateRecipeInstructionResponseMock(),
      { status: 201
      })
  }, options)
}
export const getRecipesMock = () => [
  getListRecipesMockHandler(),
  getCreateRecipeMockHandler(),
  getImportRecipeMockHandler(),
  getDeleteRecipeMockHandler(),
  getGetRecipeMockHandler(),
  getUpdateRecipeMockHandler(),
  getDeleteApiV1RecipesIdIngredientMockHandler(),
  getUpdateRecipeIngredientMockHandler(),
  getCreateRecipeIngredientMockHandler(),
  getDeleteRecipeInstructionMockHandler(),
  getUpdateRecipeInstructionMockHandler(),
  getCreateRecipeInstructionMockHandler()
]
