/**
 * Generated by Orval
 * Do not edit manually.
 * Domicile API
 * Domicile's REST API
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  CreateRecipeBody,
  CreateRecipeIngredientBody,
  CreateRecipeInstructionBody,
  DeleteApiV1RecipesIdIngredientBody,
  DeleteRecipeBody,
  DeleteRecipeInstructionBody,
  GetRecipeBody,
  GithubComDomicileappDomicileInternalDbRecipe,
  GithubComDomicileappDomicileInternalDbRecipeIngredient,
  GithubComDomicileappDomicileInternalDbRecipeInstruction,
  ListRecipesBody,
  ListRecipesParams,
  RecipesErrorResponse,
  RecipesPaginatedResponse,
  RecipesRecipeResponse,
  UpdateRecipeBody,
  UpdateRecipeIngredientBody,
  UpdateRecipeInstructionBody
} from '../../schemas';





const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

/**
 * Get list of all recipes
 * @summary List recipes
 */
export const listRecipes = (
    listRecipesBody?: ListRecipesBody,
    params?: ListRecipesParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<RecipesPaginatedResponse>> => {


    return axios.get(
      `/api/v1/recipes`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }




export const getListRecipesQueryKey = (listRecipesBody?: ListRecipesBody,
    params?: ListRecipesParams,) => {
    return [
    `/api/v1/recipes`, ...(params ? [params] : []), listRecipesBody
    ] as const;
    }


export const getListRecipesQueryOptions = <TData = Awaited<ReturnType<typeof listRecipes>>, TError = AxiosError<RecipesErrorResponse>>(listRecipesBody?: ListRecipesBody,
    params?: ListRecipesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listRecipes>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListRecipesQueryKey(listRecipesBody,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listRecipes>>> = ({ signal }) => listRecipes(listRecipesBody,params, { signal, ...axiosOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listRecipes>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListRecipesQueryResult = NonNullable<Awaited<ReturnType<typeof listRecipes>>>
export type ListRecipesQueryError = AxiosError<RecipesErrorResponse>


export function useListRecipes<TData = Awaited<ReturnType<typeof listRecipes>>, TError = AxiosError<RecipesErrorResponse>>(
 listRecipesBody: undefined |  ListRecipesBody,
    params: undefined |  ListRecipesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listRecipes>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listRecipes>>,
          TError,
          Awaited<ReturnType<typeof listRecipes>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListRecipes<TData = Awaited<ReturnType<typeof listRecipes>>, TError = AxiosError<RecipesErrorResponse>>(
 listRecipesBody?: ListRecipesBody,
    params?: ListRecipesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listRecipes>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listRecipes>>,
          TError,
          Awaited<ReturnType<typeof listRecipes>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListRecipes<TData = Awaited<ReturnType<typeof listRecipes>>, TError = AxiosError<RecipesErrorResponse>>(
 listRecipesBody?: ListRecipesBody,
    params?: ListRecipesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listRecipes>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List recipes
 */

export function useListRecipes<TData = Awaited<ReturnType<typeof listRecipes>>, TError = AxiosError<RecipesErrorResponse>>(
 listRecipesBody?: ListRecipesBody,
    params?: ListRecipesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listRecipes>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListRecipesQueryOptions(listRecipesBody,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






/**
 * @summary Create recipe
 */
export const createRecipe = (
    createRecipeBody: CreateRecipeBody, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<GithubComDomicileappDomicileInternalDbRecipe>> => {


    return axios.post(
      `/api/v1/recipes`,
      createRecipeBody,options
    );
  }




export const getCreateRecipeMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createRecipe>>, TError,{data: CreateRecipeBody}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof createRecipe>>, TError,{data: CreateRecipeBody}, TContext> => {

const mutationKey = ['createRecipe'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createRecipe>>, {data: CreateRecipeBody}> = (props) => {
          const {data} = props ?? {};

          return  createRecipe(data,axiosOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateRecipeMutationResult = NonNullable<Awaited<ReturnType<typeof createRecipe>>>
    export type CreateRecipeMutationBody = CreateRecipeBody
    export type CreateRecipeMutationError = AxiosError<unknown>

    /**
 * @summary Create recipe
 */
export const useCreateRecipe = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createRecipe>>, TError,{data: CreateRecipeBody}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createRecipe>>,
        TError,
        {data: CreateRecipeBody},
        TContext
      > => {
      return useMutation(getCreateRecipeMutationOptions(options), queryClient);
    }
    /**
 * @summary Delete recipe
 */
export const deleteRecipe = (
    id: number,
    deleteRecipeBody?: DeleteRecipeBody, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {


    return axios.delete(
      `/api/v1/recipes/${encodeURIComponent(String(id))}`,{data: deleteRecipeBody,...options}
    );
  }




export const getDeleteRecipeMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteRecipe>>, TError,{id: number;data?: DeleteRecipeBody}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof deleteRecipe>>, TError,{id: number;data?: DeleteRecipeBody}, TContext> => {

const mutationKey = ['deleteRecipe'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteRecipe>>, {id: number;data?: DeleteRecipeBody}> = (props) => {
          const {id,data} = props ?? {};

          return  deleteRecipe(id,data,axiosOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteRecipeMutationResult = NonNullable<Awaited<ReturnType<typeof deleteRecipe>>>
    export type DeleteRecipeMutationBody = DeleteRecipeBody | undefined
    export type DeleteRecipeMutationError = AxiosError<unknown>

    /**
 * @summary Delete recipe
 */
export const useDeleteRecipe = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteRecipe>>, TError,{id: number;data?: DeleteRecipeBody}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteRecipe>>,
        TError,
        {id: number;data?: DeleteRecipeBody},
        TContext
      > => {
      return useMutation(getDeleteRecipeMutationOptions(options), queryClient);
    }
    /**
 * @summary Get recipe by ID
 */
export const getRecipe = (
    id: number,
    getRecipeBody?: GetRecipeBody, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<RecipesRecipeResponse>> => {


    return axios.get(
      `/api/v1/recipes/${encodeURIComponent(String(id))}`,options
    );
  }




export const getGetRecipeQueryKey = (id: number,
    getRecipeBody?: GetRecipeBody,) => {
    return [
    `/api/v1/recipes/${id}`, getRecipeBody
    ] as const;
    }


export const getGetRecipeQueryOptions = <TData = Awaited<ReturnType<typeof getRecipe>>, TError = AxiosError<unknown>>(id: number,
    getRecipeBody?: GetRecipeBody, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRecipe>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetRecipeQueryKey(id,getRecipeBody);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getRecipe>>> = ({ signal }) => getRecipe(id,getRecipeBody, { signal, ...axiosOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getRecipe>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetRecipeQueryResult = NonNullable<Awaited<ReturnType<typeof getRecipe>>>
export type GetRecipeQueryError = AxiosError<unknown>


export function useGetRecipe<TData = Awaited<ReturnType<typeof getRecipe>>, TError = AxiosError<unknown>>(
 id: number,
    getRecipeBody: undefined |  GetRecipeBody, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRecipe>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRecipe>>,
          TError,
          Awaited<ReturnType<typeof getRecipe>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetRecipe<TData = Awaited<ReturnType<typeof getRecipe>>, TError = AxiosError<unknown>>(
 id: number,
    getRecipeBody?: GetRecipeBody, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRecipe>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRecipe>>,
          TError,
          Awaited<ReturnType<typeof getRecipe>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetRecipe<TData = Awaited<ReturnType<typeof getRecipe>>, TError = AxiosError<unknown>>(
 id: number,
    getRecipeBody?: GetRecipeBody, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRecipe>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get recipe by ID
 */

export function useGetRecipe<TData = Awaited<ReturnType<typeof getRecipe>>, TError = AxiosError<unknown>>(
 id: number,
    getRecipeBody?: GetRecipeBody, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRecipe>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetRecipeQueryOptions(id,getRecipeBody,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






/**
 * @summary Update recipe
 */
export const updateRecipe = (
    id: number,
    updateRecipeBody: UpdateRecipeBody, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<GithubComDomicileappDomicileInternalDbRecipe>> => {


    return axios.put(
      `/api/v1/recipes/${encodeURIComponent(String(id))}`,
      updateRecipeBody,options
    );
  }




export const getUpdateRecipeMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateRecipe>>, TError,{id: number;data: UpdateRecipeBody}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof updateRecipe>>, TError,{id: number;data: UpdateRecipeBody}, TContext> => {

const mutationKey = ['updateRecipe'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateRecipe>>, {id: number;data: UpdateRecipeBody}> = (props) => {
          const {id,data} = props ?? {};

          return  updateRecipe(id,data,axiosOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateRecipeMutationResult = NonNullable<Awaited<ReturnType<typeof updateRecipe>>>
    export type UpdateRecipeMutationBody = UpdateRecipeBody
    export type UpdateRecipeMutationError = AxiosError<unknown>

    /**
 * @summary Update recipe
 */
export const useUpdateRecipe = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateRecipe>>, TError,{id: number;data: UpdateRecipeBody}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateRecipe>>,
        TError,
        {id: number;data: UpdateRecipeBody},
        TContext
      > => {
      return useMutation(getUpdateRecipeMutationOptions(options), queryClient);
    }
    /**
 * @summary Delete recipe ingredient
 */
export const deleteApiV1RecipesIdIngredient = (
    id: number,
    deleteApiV1RecipesIdIngredientBody?: DeleteApiV1RecipesIdIngredientBody, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<GithubComDomicileappDomicileInternalDbRecipe>> => {


    return axios.delete(
      `/api/v1/recipes/${encodeURIComponent(String(id))}/ingredient`,{data: deleteApiV1RecipesIdIngredientBody,...options}
    );
  }




export const getDeleteApiV1RecipesIdIngredientMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1RecipesIdIngredient>>, TError,{id: number;data?: DeleteApiV1RecipesIdIngredientBody}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1RecipesIdIngredient>>, TError,{id: number;data?: DeleteApiV1RecipesIdIngredientBody}, TContext> => {

const mutationKey = ['deleteApiV1RecipesIdIngredient'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiV1RecipesIdIngredient>>, {id: number;data?: DeleteApiV1RecipesIdIngredientBody}> = (props) => {
          const {id,data} = props ?? {};

          return  deleteApiV1RecipesIdIngredient(id,data,axiosOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiV1RecipesIdIngredientMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiV1RecipesIdIngredient>>>
    export type DeleteApiV1RecipesIdIngredientMutationBody = DeleteApiV1RecipesIdIngredientBody | undefined
    export type DeleteApiV1RecipesIdIngredientMutationError = AxiosError<unknown>

    /**
 * @summary Delete recipe ingredient
 */
export const useDeleteApiV1RecipesIdIngredient = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1RecipesIdIngredient>>, TError,{id: number;data?: DeleteApiV1RecipesIdIngredientBody}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiV1RecipesIdIngredient>>,
        TError,
        {id: number;data?: DeleteApiV1RecipesIdIngredientBody},
        TContext
      > => {
      return useMutation(getDeleteApiV1RecipesIdIngredientMutationOptions(options), queryClient);
    }
    /**
 * @summary Update recipe ingredient
 */
export const updateRecipeIngredient = (
    id: number,
    updateRecipeIngredientBody: UpdateRecipeIngredientBody, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<GithubComDomicileappDomicileInternalDbRecipe>> => {


    return axios.put(
      `/api/v1/recipes/${encodeURIComponent(String(id))}/ingredient`,
      updateRecipeIngredientBody,options
    );
  }




export const getUpdateRecipeIngredientMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateRecipeIngredient>>, TError,{id: number;data: UpdateRecipeIngredientBody}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof updateRecipeIngredient>>, TError,{id: number;data: UpdateRecipeIngredientBody}, TContext> => {

const mutationKey = ['updateRecipeIngredient'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateRecipeIngredient>>, {id: number;data: UpdateRecipeIngredientBody}> = (props) => {
          const {id,data} = props ?? {};

          return  updateRecipeIngredient(id,data,axiosOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateRecipeIngredientMutationResult = NonNullable<Awaited<ReturnType<typeof updateRecipeIngredient>>>
    export type UpdateRecipeIngredientMutationBody = UpdateRecipeIngredientBody
    export type UpdateRecipeIngredientMutationError = AxiosError<unknown>

    /**
 * @summary Update recipe ingredient
 */
export const useUpdateRecipeIngredient = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateRecipeIngredient>>, TError,{id: number;data: UpdateRecipeIngredientBody}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateRecipeIngredient>>,
        TError,
        {id: number;data: UpdateRecipeIngredientBody},
        TContext
      > => {
      return useMutation(getUpdateRecipeIngredientMutationOptions(options), queryClient);
    }
    /**
 * @summary Create recipe ingredient
 */
export const createRecipeIngredient = (
    id: number,
    createRecipeIngredientBody: CreateRecipeIngredientBody, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<GithubComDomicileappDomicileInternalDbRecipeIngredient>> => {


    return axios.post(
      `/api/v1/recipes/${encodeURIComponent(String(id))}/ingredients`,
      createRecipeIngredientBody,options
    );
  }




export const getCreateRecipeIngredientMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createRecipeIngredient>>, TError,{id: number;data: CreateRecipeIngredientBody}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof createRecipeIngredient>>, TError,{id: number;data: CreateRecipeIngredientBody}, TContext> => {

const mutationKey = ['createRecipeIngredient'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createRecipeIngredient>>, {id: number;data: CreateRecipeIngredientBody}> = (props) => {
          const {id,data} = props ?? {};

          return  createRecipeIngredient(id,data,axiosOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateRecipeIngredientMutationResult = NonNullable<Awaited<ReturnType<typeof createRecipeIngredient>>>
    export type CreateRecipeIngredientMutationBody = CreateRecipeIngredientBody
    export type CreateRecipeIngredientMutationError = AxiosError<unknown>

    /**
 * @summary Create recipe ingredient
 */
export const useCreateRecipeIngredient = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createRecipeIngredient>>, TError,{id: number;data: CreateRecipeIngredientBody}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createRecipeIngredient>>,
        TError,
        {id: number;data: CreateRecipeIngredientBody},
        TContext
      > => {
      return useMutation(getCreateRecipeIngredientMutationOptions(options), queryClient);
    }
    /**
 * @summary Delete recipe instruction
 */
export const deleteRecipeInstruction = (
    id: number,
    deleteRecipeInstructionBody?: DeleteRecipeInstructionBody, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<GithubComDomicileappDomicileInternalDbRecipe>> => {


    return axios.delete(
      `/api/v1/recipes/${encodeURIComponent(String(id))}/instruction`,{data: deleteRecipeInstructionBody,...options}
    );
  }




export const getDeleteRecipeInstructionMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteRecipeInstruction>>, TError,{id: number;data?: DeleteRecipeInstructionBody}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof deleteRecipeInstruction>>, TError,{id: number;data?: DeleteRecipeInstructionBody}, TContext> => {

const mutationKey = ['deleteRecipeInstruction'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteRecipeInstruction>>, {id: number;data?: DeleteRecipeInstructionBody}> = (props) => {
          const {id,data} = props ?? {};

          return  deleteRecipeInstruction(id,data,axiosOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteRecipeInstructionMutationResult = NonNullable<Awaited<ReturnType<typeof deleteRecipeInstruction>>>
    export type DeleteRecipeInstructionMutationBody = DeleteRecipeInstructionBody | undefined
    export type DeleteRecipeInstructionMutationError = AxiosError<unknown>

    /**
 * @summary Delete recipe instruction
 */
export const useDeleteRecipeInstruction = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteRecipeInstruction>>, TError,{id: number;data?: DeleteRecipeInstructionBody}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteRecipeInstruction>>,
        TError,
        {id: number;data?: DeleteRecipeInstructionBody},
        TContext
      > => {
      return useMutation(getDeleteRecipeInstructionMutationOptions(options), queryClient);
    }
    /**
 * @summary Update recipe instruction
 */
export const updateRecipeInstruction = (
    id: number,
    updateRecipeInstructionBody: UpdateRecipeInstructionBody, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<GithubComDomicileappDomicileInternalDbRecipe>> => {


    return axios.put(
      `/api/v1/recipes/${encodeURIComponent(String(id))}/instruction`,
      updateRecipeInstructionBody,options
    );
  }




export const getUpdateRecipeInstructionMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateRecipeInstruction>>, TError,{id: number;data: UpdateRecipeInstructionBody}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof updateRecipeInstruction>>, TError,{id: number;data: UpdateRecipeInstructionBody}, TContext> => {

const mutationKey = ['updateRecipeInstruction'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateRecipeInstruction>>, {id: number;data: UpdateRecipeInstructionBody}> = (props) => {
          const {id,data} = props ?? {};

          return  updateRecipeInstruction(id,data,axiosOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateRecipeInstructionMutationResult = NonNullable<Awaited<ReturnType<typeof updateRecipeInstruction>>>
    export type UpdateRecipeInstructionMutationBody = UpdateRecipeInstructionBody
    export type UpdateRecipeInstructionMutationError = AxiosError<unknown>

    /**
 * @summary Update recipe instruction
 */
export const useUpdateRecipeInstruction = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateRecipeInstruction>>, TError,{id: number;data: UpdateRecipeInstructionBody}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateRecipeInstruction>>,
        TError,
        {id: number;data: UpdateRecipeInstructionBody},
        TContext
      > => {
      return useMutation(getUpdateRecipeInstructionMutationOptions(options), queryClient);
    }
    /**
 * @summary Create recipe instruction
 */
export const createRecipeInstruction = (
    id: number,
    createRecipeInstructionBody: CreateRecipeInstructionBody, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<GithubComDomicileappDomicileInternalDbRecipeInstruction>> => {


    return axios.post(
      `/api/v1/recipes/${encodeURIComponent(String(id))}/instructions`,
      createRecipeInstructionBody,options
    );
  }




export const getCreateRecipeInstructionMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createRecipeInstruction>>, TError,{id: number;data: CreateRecipeInstructionBody}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof createRecipeInstruction>>, TError,{id: number;data: CreateRecipeInstructionBody}, TContext> => {

const mutationKey = ['createRecipeInstruction'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createRecipeInstruction>>, {id: number;data: CreateRecipeInstructionBody}> = (props) => {
          const {id,data} = props ?? {};

          return  createRecipeInstruction(id,data,axiosOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateRecipeInstructionMutationResult = NonNullable<Awaited<ReturnType<typeof createRecipeInstruction>>>
    export type CreateRecipeInstructionMutationBody = CreateRecipeInstructionBody
    export type CreateRecipeInstructionMutationError = AxiosError<unknown>

    /**
 * @summary Create recipe instruction
 */
export const useCreateRecipeInstruction = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createRecipeInstruction>>, TError,{id: number;data: CreateRecipeInstructionBody}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createRecipeInstruction>>,
        TError,
        {id: number;data: CreateRecipeInstructionBody},
        TContext
      > => {
      return useMutation(getCreateRecipeInstructionMutationOptions(options), queryClient);
    }
