"""test

Revision ID: 6e7d9ba6a049
Revises: e943543f88b7
Create Date: 2023-08-17 20:44:38.095577

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "6e7d9ba6a049"
down_revision = "e943543f88b7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
