/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { RequestConfig, ResponseErrorConfig } from "../.kubb/client";
import type {
  CreateRecipeIngredientOptions,
  CreateRecipeIngredientStatus201,
} from "../types/CreateRecipeIngredient";
import { createRecipeIngredient } from "../clients/createRecipeIngredient";
import { mutationOptions } from "@tanstack/react-query";

export const createRecipeIngredientMutationKey = () =>
  [{ url: "/api/v1/recipes/:id/ingredients" }] as const;

export function createRecipeIngredientMutationOptions<TContext = unknown>(
  config: Partial<Omit<RequestConfig, "path" | "query" | "body" | "headers" | "url">> = {},
) {
  const mutationKey = createRecipeIngredientMutationKey();
  return mutationOptions<
    CreateRecipeIngredientStatus201,
    ResponseErrorConfig<Error>,
    CreateRecipeIngredientOptions,
    TContext
  >({
    mutationKey,
    mutationFn: async ({ path, body }) => {
      const { data } = await createRecipeIngredient({ ...config, path, body, throwOnError: true });
      return data;
    },
  });
}
