/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { RequestConfig, ResponseErrorConfig } from "../.kubb/client";
import type {
  CreateRecipeInstructionOptions,
  CreateRecipeInstructionStatus201,
} from "../types/CreateRecipeInstruction";
import { createRecipeInstruction } from "../clients/createRecipeInstruction";
import { mutationOptions } from "@tanstack/react-query";

export const createRecipeInstructionMutationKey = () =>
  [{ url: "/api/v1/recipes/:id/instructions" }] as const;

export function createRecipeInstructionMutationOptions<TContext = unknown>(
  config: Partial<Omit<RequestConfig, "path" | "query" | "body" | "headers" | "url">> = {},
) {
  const mutationKey = createRecipeInstructionMutationKey();
  return mutationOptions<
    CreateRecipeInstructionStatus201,
    ResponseErrorConfig<Error>,
    CreateRecipeInstructionOptions,
    TContext
  >({
    mutationKey,
    mutationFn: async ({ path, body }) => {
      const { data } = await createRecipeInstruction({ ...config, path, body, throwOnError: true });
      return data;
    },
  });
}
