/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { RequestConfig, ResponseErrorConfig } from "../.kubb/client";
import type { CreateRecipeOptions, CreateRecipeStatus200 } from "../types/CreateRecipe";
import { createRecipe } from "../clients/createRecipe";
import { mutationOptions } from "@tanstack/react-query";

export const createRecipeMutationKey = () => [{ url: "/api/v1/recipes" }] as const;

export function createRecipeMutationOptions<TContext = unknown>(
  config: Partial<Omit<RequestConfig, "path" | "query" | "body" | "headers" | "url">> = {},
) {
  const mutationKey = createRecipeMutationKey();
  return mutationOptions<
    CreateRecipeStatus200,
    ResponseErrorConfig<Error>,
    CreateRecipeOptions,
    TContext
  >({
    mutationKey,
    mutationFn: async ({ body }) => {
      const { data } = await createRecipe({ ...config, body, throwOnError: true });
      return data;
    },
  });
}
