/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { RequestConfig, ResponseErrorConfig } from "../.kubb/client";
import type {
  DeleteRecipeInstructionOptions,
  DeleteRecipeInstructionStatus204,
} from "../types/DeleteRecipeInstruction";
import { deleteRecipeInstruction } from "../clients/deleteRecipeInstruction";
import { mutationOptions } from "@tanstack/react-query";

export const deleteRecipeInstructionMutationKey = () =>
  [{ url: "/api/v1/recipes/:id/instruction" }] as const;

export function deleteRecipeInstructionMutationOptions<TContext = unknown>(
  config: Partial<Omit<RequestConfig, "path" | "query" | "body" | "headers" | "url">> = {},
) {
  const mutationKey = deleteRecipeInstructionMutationKey();
  return mutationOptions<
    DeleteRecipeInstructionStatus204,
    ResponseErrorConfig<Error>,
    DeleteRecipeInstructionOptions,
    TContext
  >({
    mutationKey,
    mutationFn: async ({ path, body }) => {
      const { data } = await deleteRecipeInstruction({ ...config, path, body, throwOnError: true });
      return data;
    },
  });
}
