/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { RequestConfig, ResponseErrorConfig } from "../.kubb/client";
import type { DeleteRecipeOptions, DeleteRecipeStatus204 } from "../types/DeleteRecipe";
import { deleteRecipe } from "../clients/deleteRecipe";
import { mutationOptions } from "@tanstack/react-query";

export const deleteRecipeMutationKey = () => [{ url: "/api/v1/recipes" }] as const;

export function deleteRecipeMutationOptions<TContext = unknown>(
  config: Partial<Omit<RequestConfig, "path" | "query" | "body" | "headers" | "url">> = {},
) {
  const mutationKey = deleteRecipeMutationKey();
  return mutationOptions<
    DeleteRecipeStatus204,
    ResponseErrorConfig<Error>,
    DeleteRecipeOptions,
    TContext
  >({
    mutationKey,
    mutationFn: async ({ path, body }) => {
      const { data } = await deleteRecipe({ ...config, path, body, throwOnError: true });
      return data;
    },
  });
}
