/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { RequestConfig, ResponseErrorConfig } from "../.kubb/client";
import type {
  DeleteApiV1RecipesOptions,
  DeleteApiV1RecipesStatus204,
} from "../types/DeleteApiV1Recipes";
import { deleteApiV1Recipes } from "../clients/deleteApiV1Recipes";
import { mutationOptions } from "@tanstack/react-query";

export const deleteApiV1RecipesMutationKey = () => [{ url: "/api/v1/recipes" }] as const;

export function deleteApiV1RecipesMutationOptions<TContext = unknown>(
  config: Partial<Omit<RequestConfig, "path" | "query" | "body" | "headers" | "url">> = {},
) {
  const mutationKey = deleteApiV1RecipesMutationKey();
  return mutationOptions<
    DeleteApiV1RecipesStatus204,
    ResponseErrorConfig<Error>,
    DeleteApiV1RecipesOptions,
    TContext
  >({
    mutationKey,
    mutationFn: async ({ path, body }) => {
      const { data } = await deleteApiV1Recipes({ ...config, path, body, throwOnError: true });
      return data;
    },
  });
}
