/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { RequestConfig, ResponseErrorConfig } from "../.kubb/client";
import type {
  DeleteApiV1RecipesIdIngredientOptions,
  DeleteApiV1RecipesIdIngredientStatus204,
} from "../types/DeleteApiV1RecipesIdIngredient";
import { deleteApiV1RecipesIdIngredient } from "../clients/deleteApiV1RecipesIdIngredient";
import { mutationOptions } from "@tanstack/react-query";

export const deleteApiV1RecipesIdIngredientMutationKey = () =>
  [{ url: "/api/v1/recipes/:id/ingredient" }] as const;

export function deleteApiV1RecipesIdIngredientMutationOptions<TContext = unknown>(
  config: Partial<Omit<RequestConfig, "path" | "query" | "body" | "headers" | "url">> = {},
) {
  const mutationKey = deleteApiV1RecipesIdIngredientMutationKey();
  return mutationOptions<
    DeleteApiV1RecipesIdIngredientStatus204,
    ResponseErrorConfig<Error>,
    DeleteApiV1RecipesIdIngredientOptions,
    TContext
  >({
    mutationKey,
    mutationFn: async ({ path, body }) => {
      const { data } = await deleteApiV1RecipesIdIngredient({
        ...config,
        path,
        body,
        throwOnError: true,
      });
      return data;
    },
  });
}
