/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { RequestConfig, ResponseErrorConfig } from "../.kubb/client";
import type {
  DeleteApiV1RecipesIdInstructionOptions,
  DeleteApiV1RecipesIdInstructionStatus204,
} from "../types/DeleteApiV1RecipesIdInstruction";
import { deleteApiV1RecipesIdInstruction } from "../clients/deleteApiV1RecipesIdInstruction";
import { mutationOptions } from "@tanstack/react-query";

export const deleteApiV1RecipesIdInstructionMutationKey = () =>
  [{ url: "/api/v1/recipes/:id/instruction" }] as const;

export function deleteApiV1RecipesIdInstructionMutationOptions<TContext = unknown>(
  config: Partial<Omit<RequestConfig, "path" | "query" | "body" | "headers" | "url">> = {},
) {
  const mutationKey = deleteApiV1RecipesIdInstructionMutationKey();
  return mutationOptions<
    DeleteApiV1RecipesIdInstructionStatus204,
    ResponseErrorConfig<Error>,
    DeleteApiV1RecipesIdInstructionOptions,
    TContext
  >({
    mutationKey,
    mutationFn: async ({ path, body }) => {
      const { data } = await deleteApiV1RecipesIdInstruction({
        ...config,
        path,
        body,
        throwOnError: true,
      });
      return data;
    },
  });
}
