/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { RequestConfig, ResponseErrorConfig } from "../.kubb/client";
import type {
  GetApiV1RecipesIdOptions,
  GetApiV1RecipesIdStatus200,
} from "../types/GetApiV1RecipesId";
import { getApiV1RecipesId } from "../clients/getApiV1RecipesId";
import { queryOptions } from "@tanstack/react-query";

export const getApiV1RecipesIdQueryKey = ({
  path,
  body,
}: Omit<GetApiV1RecipesIdOptions, "headers">) =>
  [{ url: "/api/v1/recipes/:id", params: path }, ...(body ? [body] : [])] as const;

type GetApiV1RecipesIdQueryKey = ReturnType<typeof getApiV1RecipesIdQueryKey>;

export function getApiV1RecipesIdQueryOptions(
  { path, body }: GetApiV1RecipesIdOptions,
  config: Partial<Omit<RequestConfig, "path" | "query" | "body" | "headers" | "url">> = {},
) {
  const queryKey = getApiV1RecipesIdQueryKey({ path, body });
  return queryOptions<
    GetApiV1RecipesIdStatus200,
    ResponseErrorConfig<Error>,
    GetApiV1RecipesIdStatus200,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      const { data } = await getApiV1RecipesId({
        ...config,
        path,
        body,
        signal: config.signal ?? signal,
        throwOnError: true,
      });
      return data;
    },
  });
}
