/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { RequestConfig, ResponseErrorConfig } from "../.kubb/client";
import type { GetRecipeOptions, GetRecipeStatus200 } from "../types/GetRecipe";
import { getRecipe } from "../clients/getRecipe";
import { queryOptions } from "@tanstack/react-query";

export const getRecipeQueryKey = ({ path, body }: Omit<GetRecipeOptions, "headers">) =>
  [{ url: "/api/v1/recipes/:id", params: path }, ...(body ? [body] : [])] as const;

type GetRecipeQueryKey = ReturnType<typeof getRecipeQueryKey>;

export function getRecipeQueryOptions(
  { path, body }: GetRecipeOptions,
  config: Partial<Omit<RequestConfig, "path" | "query" | "body" | "headers" | "url">> = {},
) {
  const queryKey = getRecipeQueryKey({ path, body });
  return queryOptions<
    GetRecipeStatus200,
    ResponseErrorConfig<Error>,
    GetRecipeStatus200,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      const { data } = await getRecipe({
        ...config,
        path,
        body,
        signal: config.signal ?? signal,
        throwOnError: true,
      });
      return data;
    },
  });
}
