/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { RequestConfig, ResponseErrorConfig } from "../.kubb/client";
import type { ListRecipesOptions, ListRecipesStatus200 } from "../types/ListRecipes";
import { listRecipes } from "../clients/listRecipes";
import { queryOptions } from "@tanstack/react-query";

export const listRecipesQueryKey = ({ body }: Omit<ListRecipesOptions, "headers">) =>
  [{ url: "/api/v1/recipes" }, ...(body ? [body] : [])] as const;

type ListRecipesQueryKey = ReturnType<typeof listRecipesQueryKey>;

export function listRecipesQueryOptions(
  { body }: ListRecipesOptions,
  config: Partial<Omit<RequestConfig, "path" | "query" | "body" | "headers" | "url">> = {},
) {
  const queryKey = listRecipesQueryKey({ body });
  return queryOptions<
    ListRecipesStatus200,
    ResponseErrorConfig<Error>,
    ListRecipesStatus200,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      const { data } = await listRecipes({
        ...config,
        body,
        signal: config.signal ?? signal,
        throwOnError: true,
      });
      return data;
    },
  });
}
