/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { RequestConfig, ResponseErrorConfig } from "../.kubb/client";
import type {
  PostApiV1RecipesIdIngredientsOptions,
  PostApiV1RecipesIdIngredientsStatus201,
} from "../types/PostApiV1RecipesIdIngredients";
import { postApiV1RecipesIdIngredients } from "../clients/postApiV1RecipesIdIngredients";
import { mutationOptions } from "@tanstack/react-query";

export const postApiV1RecipesIdIngredientsMutationKey = () =>
  [{ url: "/api/v1/recipes/:id/ingredients" }] as const;

export function postApiV1RecipesIdIngredientsMutationOptions<TContext = unknown>(
  config: Partial<Omit<RequestConfig, "path" | "query" | "body" | "headers" | "url">> = {},
) {
  const mutationKey = postApiV1RecipesIdIngredientsMutationKey();
  return mutationOptions<
    PostApiV1RecipesIdIngredientsStatus201,
    ResponseErrorConfig<Error>,
    PostApiV1RecipesIdIngredientsOptions,
    TContext
  >({
    mutationKey,
    mutationFn: async ({ path, body }) => {
      const { data } = await postApiV1RecipesIdIngredients({
        ...config,
        path,
        body,
        throwOnError: true,
      });
      return data;
    },
  });
}
