/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { RequestConfig, ResponseErrorConfig } from "../.kubb/client";
import type {
  PutApiV1RecipesIdOptions,
  PutApiV1RecipesIdStatus204,
} from "../types/PutApiV1RecipesId";
import { putApiV1RecipesId } from "../clients/putApiV1RecipesId";
import { mutationOptions } from "@tanstack/react-query";

export const putApiV1RecipesIdMutationKey = () => [{ url: "/api/v1/recipes/:id" }] as const;

export function putApiV1RecipesIdMutationOptions<TContext = unknown>(
  config: Partial<Omit<RequestConfig, "path" | "query" | "body" | "headers" | "url">> = {},
) {
  const mutationKey = putApiV1RecipesIdMutationKey();
  return mutationOptions<
    PutApiV1RecipesIdStatus204,
    ResponseErrorConfig<Error>,
    PutApiV1RecipesIdOptions,
    TContext
  >({
    mutationKey,
    mutationFn: async ({ body }) => {
      const { data } = await putApiV1RecipesId({ ...config, body, throwOnError: true });
      return data;
    },
  });
}
