/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { RequestConfig, ResponseErrorConfig } from "../.kubb/client";
import type { PostApiV1RecipesOptions, PostApiV1RecipesStatus200 } from "../types/PostApiV1Recipes";
import { postApiV1Recipes } from "../clients/postApiV1Recipes";
import { mutationOptions } from "@tanstack/react-query";

export const postApiV1RecipesMutationKey = () => [{ url: "/api/v1/recipes" }] as const;

export function postApiV1RecipesMutationOptions<TContext = unknown>(
  config: Partial<Omit<RequestConfig, "path" | "query" | "body" | "headers" | "url">> = {},
) {
  const mutationKey = postApiV1RecipesMutationKey();
  return mutationOptions<
    PostApiV1RecipesStatus200,
    ResponseErrorConfig<Error>,
    PostApiV1RecipesOptions,
    TContext
  >({
    mutationKey,
    mutationFn: async ({ body }) => {
      const { data } = await postApiV1Recipes({ ...config, body, throwOnError: true });
      return data;
    },
  });
}
