/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { RequestConfig, ResponseErrorConfig } from "../.kubb/client";
import type {
  PutApiV1RecipesIdInstructionOptions,
  PutApiV1RecipesIdInstructionStatus201,
} from "../types/PutApiV1RecipesIdInstruction";
import { putApiV1RecipesIdInstruction } from "../clients/putApiV1RecipesIdInstruction";
import { mutationOptions } from "@tanstack/react-query";

export const putApiV1RecipesIdInstructionMutationKey = () =>
  [{ url: "/api/v1/recipes/:id/instruction" }] as const;

export function putApiV1RecipesIdInstructionMutationOptions<TContext = unknown>(
  config: Partial<Omit<RequestConfig, "path" | "query" | "body" | "headers" | "url">> = {},
) {
  const mutationKey = putApiV1RecipesIdInstructionMutationKey();
  return mutationOptions<
    PutApiV1RecipesIdInstructionStatus201,
    ResponseErrorConfig<Error>,
    PutApiV1RecipesIdInstructionOptions,
    TContext
  >({
    mutationKey,
    mutationFn: async ({ path, body }) => {
      const { data } = await putApiV1RecipesIdInstruction({
        ...config,
        path,
        body,
        throwOnError: true,
      });
      return data;
    },
  });
}
