/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { RequestConfig, ResponseErrorConfig } from "../.kubb/client";
import type {
  PostApiV1RecipesIdInstructionsOptions,
  PostApiV1RecipesIdInstructionsStatus201,
} from "../types/PostApiV1RecipesIdInstructions";
import { postApiV1RecipesIdInstructions } from "../clients/postApiV1RecipesIdInstructions";
import { mutationOptions } from "@tanstack/react-query";

export const postApiV1RecipesIdInstructionsMutationKey = () =>
  [{ url: "/api/v1/recipes/:id/instructions" }] as const;

export function postApiV1RecipesIdInstructionsMutationOptions<TContext = unknown>(
  config: Partial<Omit<RequestConfig, "path" | "query" | "body" | "headers" | "url">> = {},
) {
  const mutationKey = postApiV1RecipesIdInstructionsMutationKey();
  return mutationOptions<
    PostApiV1RecipesIdInstructionsStatus201,
    ResponseErrorConfig<Error>,
    PostApiV1RecipesIdInstructionsOptions,
    TContext
  >({
    mutationKey,
    mutationFn: async ({ path, body }) => {
      const { data } = await postApiV1RecipesIdInstructions({
        ...config,
        path,
        body,
        throwOnError: true,
      });
      return data;
    },
  });
}
