/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { RequestConfig, ResponseErrorConfig } from "../.kubb/client";
import type {
  PutApiV1RecipesIdIngredientOptions,
  PutApiV1RecipesIdIngredientStatus201,
} from "../types/PutApiV1RecipesIdIngredient";
import { putApiV1RecipesIdIngredient } from "../clients/putApiV1RecipesIdIngredient";
import { mutationOptions } from "@tanstack/react-query";

export const putApiV1RecipesIdIngredientMutationKey = () =>
  [{ url: "/api/v1/recipes/:id/ingredient" }] as const;

export function putApiV1RecipesIdIngredientMutationOptions<TContext = unknown>(
  config: Partial<Omit<RequestConfig, "path" | "query" | "body" | "headers" | "url">> = {},
) {
  const mutationKey = putApiV1RecipesIdIngredientMutationKey();
  return mutationOptions<
    PutApiV1RecipesIdIngredientStatus201,
    ResponseErrorConfig<Error>,
    PutApiV1RecipesIdIngredientOptions,
    TContext
  >({
    mutationKey,
    mutationFn: async ({ path, body }) => {
      const { data } = await putApiV1RecipesIdIngredient({
        ...config,
        path,
        body,
        throwOnError: true,
      });
      return data;
    },
  });
}
