/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { RequestConfig, ResponseErrorConfig } from "../.kubb/client";
import type {
  UpdateRecipeIngredientOptions,
  UpdateRecipeIngredientStatus201,
} from "../types/UpdateRecipeIngredient";
import { updateRecipeIngredient } from "../clients/updateRecipeIngredient";
import { mutationOptions } from "@tanstack/react-query";

export const updateRecipeIngredientMutationKey = () =>
  [{ url: "/api/v1/recipes/:id/ingredient" }] as const;

export function updateRecipeIngredientMutationOptions<TContext = unknown>(
  config: Partial<Omit<RequestConfig, "path" | "query" | "body" | "headers" | "url">> = {},
) {
  const mutationKey = updateRecipeIngredientMutationKey();
  return mutationOptions<
    UpdateRecipeIngredientStatus201,
    ResponseErrorConfig<Error>,
    UpdateRecipeIngredientOptions,
    TContext
  >({
    mutationKey,
    mutationFn: async ({ path, body }) => {
      const { data } = await updateRecipeIngredient({ ...config, path, body, throwOnError: true });
      return data;
    },
  });
}
