/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { RequestConfig, ResponseErrorConfig } from "../.kubb/client";
import type { UpdateRecipeOptions, UpdateRecipeStatus204 } from "../types/UpdateRecipe";
import { updateRecipe } from "../clients/updateRecipe";
import { mutationOptions } from "@tanstack/react-query";

export const updateRecipeMutationKey = () => [{ url: "/api/v1/recipes/:id" }] as const;

export function updateRecipeMutationOptions<TContext = unknown>(
  config: Partial<Omit<RequestConfig, "path" | "query" | "body" | "headers" | "url">> = {},
) {
  const mutationKey = updateRecipeMutationKey();
  return mutationOptions<
    UpdateRecipeStatus204,
    ResponseErrorConfig<Error>,
    UpdateRecipeOptions,
    TContext
  >({
    mutationKey,
    mutationFn: async ({ body }) => {
      const { data } = await updateRecipe({ ...config, body, throwOnError: true });
      return data;
    },
  });
}
