/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { RequestConfig, ResponseErrorConfig } from "../.kubb/client";
import type {
  UpdateRecipeInstructionOptions,
  UpdateRecipeInstructionStatus201,
} from "../types/UpdateRecipeInstruction";
import { updateRecipeInstruction } from "../clients/updateRecipeInstruction";
import { mutationOptions } from "@tanstack/react-query";

export const updateRecipeInstructionMutationKey = () =>
  [{ url: "/api/v1/recipes/:id/instruction" }] as const;

export function updateRecipeInstructionMutationOptions<TContext = unknown>(
  config: Partial<Omit<RequestConfig, "path" | "query" | "body" | "headers" | "url">> = {},
) {
  const mutationKey = updateRecipeInstructionMutationKey();
  return mutationOptions<
    UpdateRecipeInstructionStatus201,
    ResponseErrorConfig<Error>,
    UpdateRecipeInstructionOptions,
    TContext
  >({
    mutationKey,
    mutationFn: async ({ path, body }) => {
      const { data } = await updateRecipeInstruction({ ...config, path, body, throwOnError: true });
      return data;
    },
  });
}
