/**
 * Generated by Orval
 * Do not edit manually.
 * Domicile API
 * Domicile's REST API
 */
import * as zod from 'zod';


/**
 * Get list of all recipes
 * @summary List recipes
 */

export const listRecipesQuerySizeMax = 120;

export const listRecipesQueryDirectionDefault = `desc`;

export const ListRecipesQueryParams = zod.object({
  "page": zod.int().min(1).optional().describe('Page number'),
  "size": zod.int().min(1).max(listRecipesQuerySizeMax).optional().describe('Page size'),
  "search": zod.string().optional().describe('Search params'),
  "sort": zod.enum(['id', 'name', 'created_at', 'updated_at']).optional().describe('Sort field'),
  "direction": zod.enum(['asc', 'desc']).default(listRecipesQueryDirectionDefault).describe('Sort direction')
})

export const ListRecipesBody = zod.looseObject({

})

export const ListRecipesResponse = zod.object({
  "items": zod.array(zod.object({
  "cook_time": zod.string().optional(),
  "created_at": zod.string().optional(),
  "id": zod.int().optional(),
  "name": zod.string().optional(),
  "notes": zod.string().optional(),
  "nutrition": zod.string().optional(),
  "photo_url": zod.string().optional(),
  "prep_time": zod.string().optional(),
  "servings": zod.string().optional(),
  "short_description": zod.string().optional(),
  "source": zod.string().optional(),
  "updated_at": zod.string().optional()
})).optional(),
  "page": zod.int().optional(),
  "size": zod.int().optional(),
  "total_items": zod.int().optional(),
  "total_pages": zod.int().optional()
})

/**
 * @summary Create recipe
 */
export const CreateRecipeBody = zod.union([zod.looseObject({

}),zod.object({
  "name": zod.string().optional(),
  "photo_url": zod.string().optional(),
  "short_description": zod.string().optional()
}).describe('Recipe data')])

export const CreateRecipeResponse = zod.object({
  "cook_time": zod.string().optional(),
  "created_at": zod.string().optional(),
  "deleted_at": zod.string().optional(),
  "id": zod.int().optional(),
  "name": zod.string().optional(),
  "notes": zod.string().optional(),
  "nutrition": zod.string().optional(),
  "photo_url": zod.string().optional(),
  "prep_time": zod.string().optional(),
  "servings": zod.string().optional(),
  "short_description": zod.string().optional(),
  "source": zod.string().optional(),
  "updated_at": zod.string().optional()
})

/**
 * Scrape a recipe from the given HTML via the scraper and persist it.
 * @summary Import a recipe from a webpage
 */
export const ImportRecipeBody = zod.union([zod.looseObject({

}),zod.object({
  "html": zod.string().optional(),
  "url": zod.string().optional()
}).describe('Page URL and HTML returned by the browser extension')])

export const ImportRecipeResponse = zod.object({
  "cook_time": zod.string().optional(),
  "created_at": zod.string().optional(),
  "deleted_at": zod.string().optional(),
  "id": zod.int().optional(),
  "ingredients": zod.array(zod.object({
  "group_name": zod.string().optional(),
  "id": zod.int().optional(),
  "ingredient_name": zod.string().optional(),
  "parse_status": zod.string().optional(),
  "preparation": zod.string().optional(),
  "quantity": zod.number().optional(),
  "raw_text": zod.string().optional(),
  "recipe_id": zod.int().optional(),
  "sort_order": zod.number().optional(),
  "unit": zod.string().optional()
})).optional(),
  "instructions": zod.array(zod.object({
  "content": zod.string().optional(),
  "group_name": zod.string().optional(),
  "id": zod.int().optional(),
  "recipe_id": zod.int().optional(),
  "sort_order": zod.number().optional()
})).optional(),
  "name": zod.string().optional(),
  "notes": zod.string().optional(),
  "nutrition": zod.string().optional(),
  "photo_url": zod.string().optional(),
  "prep_time": zod.string().optional(),
  "servings": zod.string().optional(),
  "short_description": zod.string().optional(),
  "source": zod.string().optional(),
  "updated_at": zod.string().optional()
})

/**
 * @summary Delete recipe
 */
export const DeleteRecipeParams = zod.object({
  "id": zod.int().describe('Recipe ID')
})

export const DeleteRecipeBody = zod.looseObject({

})

export const DeleteRecipeResponse = zod.void()

/**
 * @summary Get recipe by ID
 */
export const GetRecipeParams = zod.object({
  "id": zod.int().describe('Recipe ID')
})

export const GetRecipeBody = zod.looseObject({

})

export const GetRecipeResponse = zod.object({
  "cook_time": zod.string().optional(),
  "created_at": zod.string().optional(),
  "deleted_at": zod.string().optional(),
  "id": zod.int().optional(),
  "ingredients": zod.array(zod.object({
  "group_name": zod.string().optional(),
  "id": zod.int().optional(),
  "ingredient_name": zod.string().optional(),
  "parse_status": zod.string().optional(),
  "preparation": zod.string().optional(),
  "quantity": zod.number().optional(),
  "raw_text": zod.string().optional(),
  "recipe_id": zod.int().optional(),
  "sort_order": zod.number().optional(),
  "unit": zod.string().optional()
})).optional(),
  "instructions": zod.array(zod.object({
  "content": zod.string().optional(),
  "group_name": zod.string().optional(),
  "id": zod.int().optional(),
  "recipe_id": zod.int().optional(),
  "sort_order": zod.number().optional()
})).optional(),
  "name": zod.string().optional(),
  "notes": zod.string().optional(),
  "nutrition": zod.string().optional(),
  "photo_url": zod.string().optional(),
  "prep_time": zod.string().optional(),
  "servings": zod.string().optional(),
  "short_description": zod.string().optional(),
  "source": zod.string().optional(),
  "updated_at": zod.string().optional()
})

/**
 * @summary Update recipe
 */
export const UpdateRecipeParams = zod.object({
  "id": zod.int().describe('Recipe ID')
})

export const UpdateRecipeBody = zod.union([zod.looseObject({

}),zod.object({
  "name": zod.string().optional(),
  "short_description": zod.string().optional()
}).describe('Recipe data')])

export const UpdateRecipeResponse = zod.object({
  "cook_time": zod.string().optional(),
  "created_at": zod.string().optional(),
  "deleted_at": zod.string().optional(),
  "id": zod.int().optional(),
  "name": zod.string().optional(),
  "notes": zod.string().optional(),
  "nutrition": zod.string().optional(),
  "photo_url": zod.string().optional(),
  "prep_time": zod.string().optional(),
  "servings": zod.string().optional(),
  "short_description": zod.string().optional(),
  "source": zod.string().optional(),
  "updated_at": zod.string().optional()
})

/**
 * @summary Delete recipe ingredient
 */
export const DeleteApiV1RecipesIdIngredientParams = zod.object({
  "id": zod.int().describe('Recipe ID')
})

export const DeleteApiV1RecipesIdIngredientBody = zod.looseObject({

})

export const DeleteApiV1RecipesIdIngredientResponse = zod.object({
  "cook_time": zod.string().optional(),
  "created_at": zod.string().optional(),
  "deleted_at": zod.string().optional(),
  "id": zod.int().optional(),
  "name": zod.string().optional(),
  "notes": zod.string().optional(),
  "nutrition": zod.string().optional(),
  "photo_url": zod.string().optional(),
  "prep_time": zod.string().optional(),
  "servings": zod.string().optional(),
  "short_description": zod.string().optional(),
  "source": zod.string().optional(),
  "updated_at": zod.string().optional()
})

/**
 * @summary Update recipe ingredient
 */
export const UpdateRecipeIngredientParams = zod.object({
  "id": zod.int().describe('Recipe ID')
})

export const UpdateRecipeIngredientBody = zod.union([zod.looseObject({

}),zod.object({
  "group_name": zod.string().optional(),
  "raw_text": zod.string().optional(),
  "sort_order": zod.number().optional()
}).describe('Ingredient data')])

export const UpdateRecipeIngredientResponse = zod.object({
  "cook_time": zod.string().optional(),
  "created_at": zod.string().optional(),
  "deleted_at": zod.string().optional(),
  "id": zod.int().optional(),
  "name": zod.string().optional(),
  "notes": zod.string().optional(),
  "nutrition": zod.string().optional(),
  "photo_url": zod.string().optional(),
  "prep_time": zod.string().optional(),
  "servings": zod.string().optional(),
  "short_description": zod.string().optional(),
  "source": zod.string().optional(),
  "updated_at": zod.string().optional()
})

/**
 * @summary Create recipe ingredient
 */
export const CreateRecipeIngredientParams = zod.object({
  "id": zod.int().describe('Recipe ID')
})

export const CreateRecipeIngredientBody = zod.union([zod.looseObject({

}),zod.object({
  "group_name": zod.string().optional(),
  "raw_text": zod.string().optional(),
  "sort_order": zod.number().optional()
}).describe('Ingredient data')])

export const CreateRecipeIngredientResponse = zod.object({
  "created_at": zod.string().optional(),
  "group_name": zod.string().optional(),
  "id": zod.int().optional(),
  "ingredient_name": zod.string().optional(),
  "parse_status": zod.string().optional(),
  "parsed_at": zod.string().optional(),
  "preparation": zod.string().optional(),
  "quantity": zod.number().optional(),
  "raw_text": zod.string().optional(),
  "recipe_id": zod.int().optional(),
  "sort_order": zod.number().optional(),
  "unit": zod.string().optional(),
  "updated_at": zod.string().optional()
})

/**
 * @summary Delete recipe instruction
 */
export const DeleteRecipeInstructionParams = zod.object({
  "id": zod.int().describe('Recipe ID')
})

export const DeleteRecipeInstructionBody = zod.looseObject({

})

export const DeleteRecipeInstructionResponse = zod.object({
  "cook_time": zod.string().optional(),
  "created_at": zod.string().optional(),
  "deleted_at": zod.string().optional(),
  "id": zod.int().optional(),
  "name": zod.string().optional(),
  "notes": zod.string().optional(),
  "nutrition": zod.string().optional(),
  "photo_url": zod.string().optional(),
  "prep_time": zod.string().optional(),
  "servings": zod.string().optional(),
  "short_description": zod.string().optional(),
  "source": zod.string().optional(),
  "updated_at": zod.string().optional()
})

/**
 * @summary Update recipe instruction
 */
export const UpdateRecipeInstructionParams = zod.object({
  "id": zod.int().describe('Recipe ID')
})

export const UpdateRecipeInstructionBody = zod.union([zod.looseObject({

}),zod.object({
  "content": zod.string().optional(),
  "sort_order": zod.number().optional()
}).describe('Instruction data')])

export const UpdateRecipeInstructionResponse = zod.object({
  "cook_time": zod.string().optional(),
  "created_at": zod.string().optional(),
  "deleted_at": zod.string().optional(),
  "id": zod.int().optional(),
  "name": zod.string().optional(),
  "notes": zod.string().optional(),
  "nutrition": zod.string().optional(),
  "photo_url": zod.string().optional(),
  "prep_time": zod.string().optional(),
  "servings": zod.string().optional(),
  "short_description": zod.string().optional(),
  "source": zod.string().optional(),
  "updated_at": zod.string().optional()
})

/**
 * @summary Create recipe instruction
 */
export const CreateRecipeInstructionParams = zod.object({
  "id": zod.int().describe('Recipe ID')
})

export const CreateRecipeInstructionBody = zod.union([zod.looseObject({

}),zod.object({
  "content": zod.string().optional(),
  "group_name": zod.string().optional(),
  "sort_order": zod.number().optional()
}).describe('Instruction data')])

export const CreateRecipeInstructionResponse = zod.object({
  "content": zod.string().optional(),
  "created_at": zod.string().optional(),
  "group_name": zod.string().optional(),
  "id": zod.int().optional(),
  "recipe_id": zod.int().optional(),
  "sort_order": zod.number().optional(),
  "updated_at": zod.string().optional()
})

