/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type GithubComDomicileappDomicileInternalDbListRecipeInstructionsRow = {
  content?: string;
  group_name?: string;
  id?: number;
  recipe_id?: number;
  sort_order?: number;
};
