/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type GithubComDomicileappDomicileInternalDbListRecipeIngredientsRow = {
  group_name?: string;
  id?: number;
  ingredient_name?: string;
  parse_status?: string;
  preparation?: string;
  quantity?: number;
  raw_text?: string;
  recipe_id?: number;
  sort_order?: number;
  unit?: string;
};
