/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type GithubComDomicileappDomicileInternalDbRecipe = {
  cook_time?: string;
  created_at?: string;
  deleted_at?: string;
  id?: number;
  name?: string;
  notes?: string;
  nutrition?: string;
  photo_url?: string;
  prep_time?: string;
  servings?: string;
  short_description?: string;
  source?: string;
  updated_at?: string;
};
