/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type GithubComDomicileappDomicileInternalDbRecipeInstruction = {
  content?: string;
  created_at?: string;
  group_name?: string;
  id?: number;
  recipe_id?: number;
  sort_order?: number;
  updated_at?: string;
};
