apiVersion: v1
kind: PersistentVolume
metadata:
  name: domicile-db-pv
  labels:
    type: local
    app: domicile-db
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: '/mnt/data'
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: domicile-db-pv-claim
  labels:
    app: domicile-db
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
