/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Options, RequestResult } from "../.kubb/client";
import type {
  CreateRecipeIngredientOptions,
  CreateRecipeIngredientResponses,
} from "../types/CreateRecipeIngredient";
import { client } from "../.kubb/client";

/**
 * @summary Create recipe ingredient
 * {@link /api/v1/recipes/:id/ingredients}
 */
export function createRecipeIngredient<ThrowOnError extends boolean = true>(
  options: Options<CreateRecipeIngredientOptions, ThrowOnError>,
): Promise<RequestResult<CreateRecipeIngredientResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options;

  return request({ method: "POST", url: "/api/v1/recipes/{id}/ingredients", ...config }) as Promise<
    RequestResult<CreateRecipeIngredientResponses, ThrowOnError>
  >;
}
