/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Options, RequestResult } from "../.kubb/client";
import type {
  CreateRecipeInstructionOptions,
  CreateRecipeInstructionResponses,
} from "../types/CreateRecipeInstruction";
import { client } from "../.kubb/client";

/**
 * @summary Create recipe instruction
 * {@link /api/v1/recipes/:id/instructions}
 */
export function createRecipeInstruction<ThrowOnError extends boolean = true>(
  options: Options<CreateRecipeInstructionOptions, ThrowOnError>,
): Promise<RequestResult<CreateRecipeInstructionResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options;

  return request({
    method: "POST",
    url: "/api/v1/recipes/{id}/instructions",
    ...config,
  }) as Promise<RequestResult<CreateRecipeInstructionResponses, ThrowOnError>>;
}
