/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Options, RequestResult } from "../.kubb/client";
import type { CreateRecipeOptions, CreateRecipeResponses } from "../types/CreateRecipe";
import { client } from "../.kubb/client";

/**
 * @summary Create recipe
 * {@link /api/v1/recipes}
 */
export function createRecipe<ThrowOnError extends boolean = true>(
  options: Options<CreateRecipeOptions, ThrowOnError>,
): Promise<RequestResult<CreateRecipeResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options;

  return request({ method: "POST", url: "/api/v1/recipes", ...config }) as Promise<
    RequestResult<CreateRecipeResponses, ThrowOnError>
  >;
}
