/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Options, RequestResult } from "../.kubb/client";
import type {
  DeleteRecipeInstructionOptions,
  DeleteRecipeInstructionResponses,
} from "../types/DeleteRecipeInstruction";
import { client } from "../.kubb/client";

/**
 * @summary Delete recipe instruction
 * {@link /api/v1/recipes/:id/instruction}
 */
export function deleteRecipeInstruction<ThrowOnError extends boolean = true>(
  options: Options<DeleteRecipeInstructionOptions, ThrowOnError>,
): Promise<RequestResult<DeleteRecipeInstructionResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options;

  return request({
    method: "DELETE",
    url: "/api/v1/recipes/{id}/instruction",
    ...config,
  }) as Promise<RequestResult<DeleteRecipeInstructionResponses, ThrowOnError>>;
}
