/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Options, RequestResult } from "../.kubb/client";
import type {
  DeleteApiV1RecipesOptions,
  DeleteApiV1RecipesResponses,
} from "../types/DeleteApiV1Recipes";
import { client } from "../.kubb/client";

/**
 * @summary Delete recipe
 * {@link /api/v1/recipes}
 */
export function deleteApiV1Recipes<ThrowOnError extends boolean = true>(
  options: Options<DeleteApiV1RecipesOptions, ThrowOnError>,
): Promise<RequestResult<DeleteApiV1RecipesResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options;

  return request({ method: "DELETE", url: "/api/v1/recipes", ...config }) as Promise<
    RequestResult<DeleteApiV1RecipesResponses, ThrowOnError>
  >;
}
