/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Options, RequestResult } from "../.kubb/client";
import type {
  DeleteApiV1RecipesIdInstructionOptions,
  DeleteApiV1RecipesIdInstructionResponses,
} from "../types/DeleteApiV1RecipesIdInstruction";
import { client } from "../.kubb/client";

/**
 * @summary Delete recipe instruction
 * {@link /api/v1/recipes/:id/instruction}
 */
export function deleteApiV1RecipesIdInstruction<ThrowOnError extends boolean = true>(
  options: Options<DeleteApiV1RecipesIdInstructionOptions, ThrowOnError>,
): Promise<RequestResult<DeleteApiV1RecipesIdInstructionResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options;

  return request({
    method: "DELETE",
    url: "/api/v1/recipes/{id}/instruction",
    ...config,
  }) as Promise<RequestResult<DeleteApiV1RecipesIdInstructionResponses, ThrowOnError>>;
}
