/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Options, RequestResult } from "../.kubb/client";
import type { DeleteRecipeOptions, DeleteRecipeResponses } from "../types/DeleteRecipe";
import { client } from "../.kubb/client";

/**
 * @summary Delete recipe
 * {@link /api/v1/recipes}
 */
export function deleteRecipe<ThrowOnError extends boolean = true>(
  options: Options<DeleteRecipeOptions, ThrowOnError>,
): Promise<RequestResult<DeleteRecipeResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options;

  return request({ method: "DELETE", url: "/api/v1/recipes", ...config }) as Promise<
    RequestResult<DeleteRecipeResponses, ThrowOnError>
  >;
}
