/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Options, RequestResult } from "../.kubb/client";
import type {
  DeleteApiV1RecipesIdIngredientOptions,
  DeleteApiV1RecipesIdIngredientResponses,
} from "../types/DeleteApiV1RecipesIdIngredient";
import { client } from "../.kubb/client";

/**
 * @summary Delete recipe ingredient
 * {@link /api/v1/recipes/:id/ingredient}
 */
export function deleteApiV1RecipesIdIngredient<ThrowOnError extends boolean = true>(
  options: Options<DeleteApiV1RecipesIdIngredientOptions, ThrowOnError>,
): Promise<RequestResult<DeleteApiV1RecipesIdIngredientResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options;

  return request({
    method: "DELETE",
    url: "/api/v1/recipes/{id}/ingredient",
    ...config,
  }) as Promise<RequestResult<DeleteApiV1RecipesIdIngredientResponses, ThrowOnError>>;
}
