/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Options, RequestResult } from "../.kubb/client";
import type {
  GetApiV1RecipesIdOptions,
  GetApiV1RecipesIdResponses,
} from "../types/GetApiV1RecipesId";
import { client } from "../.kubb/client";

/**
 * @summary Get recipe by ID
 * {@link /api/v1/recipes/:id}
 */
export function getApiV1RecipesId<ThrowOnError extends boolean = true>(
  options: Options<GetApiV1RecipesIdOptions, ThrowOnError>,
): Promise<RequestResult<GetApiV1RecipesIdResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options;

  return request({ method: "GET", url: "/api/v1/recipes/{id}", ...config }) as Promise<
    RequestResult<GetApiV1RecipesIdResponses, ThrowOnError>
  >;
}
