/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Options, RequestResult } from "../.kubb/client";
import type { GetRecipeOptions, GetRecipeResponses } from "../types/GetRecipe";
import { client } from "../.kubb/client";

/**
 * @summary Get recipe by ID
 * {@link /api/v1/recipes/:id}
 */
export function getRecipe<ThrowOnError extends boolean = true>(
  options: Options<GetRecipeOptions, ThrowOnError>,
): Promise<RequestResult<GetRecipeResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options;

  return request({ method: "GET", url: "/api/v1/recipes/{id}", ...config }) as Promise<
    RequestResult<GetRecipeResponses, ThrowOnError>
  >;
}
