/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Options, RequestResult } from "../.kubb/client";
import type { ListRecipesOptions, ListRecipesResponses } from "../types/ListRecipes";
import { client } from "../.kubb/client";

/**
 * @description Get list of all recipes
 * @summary List recipes
 * {@link /api/v1/recipes}
 */
export function listRecipes<ThrowOnError extends boolean = true>(
  options: Options<ListRecipesOptions, ThrowOnError>,
): Promise<RequestResult<ListRecipesResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options;

  return request({ method: "GET", url: "/api/v1/recipes", ...config }) as Promise<
    RequestResult<ListRecipesResponses, ThrowOnError>
  >;
}
