/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Options, RequestResult } from "../.kubb/client";
import type {
  PostApiV1RecipesIdInstructionsOptions,
  PostApiV1RecipesIdInstructionsResponses,
} from "../types/PostApiV1RecipesIdInstructions";
import { client } from "../.kubb/client";

/**
 * @summary Create recipe instruction
 * {@link /api/v1/recipes/:id/instructions}
 */
export function postApiV1RecipesIdInstructions<ThrowOnError extends boolean = true>(
  options: Options<PostApiV1RecipesIdInstructionsOptions, ThrowOnError>,
): Promise<RequestResult<PostApiV1RecipesIdInstructionsResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options;

  return request({
    method: "POST",
    url: "/api/v1/recipes/{id}/instructions",
    ...config,
  }) as Promise<RequestResult<PostApiV1RecipesIdInstructionsResponses, ThrowOnError>>;
}
