/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Options, RequestResult } from "../.kubb/client";
import type {
  PostApiV1RecipesIdIngredientsOptions,
  PostApiV1RecipesIdIngredientsResponses,
} from "../types/PostApiV1RecipesIdIngredients";
import { client } from "../.kubb/client";

/**
 * @summary Create recipe ingredient
 * {@link /api/v1/recipes/:id/ingredients}
 */
export function postApiV1RecipesIdIngredients<ThrowOnError extends boolean = true>(
  options: Options<PostApiV1RecipesIdIngredientsOptions, ThrowOnError>,
): Promise<RequestResult<PostApiV1RecipesIdIngredientsResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options;

  return request({ method: "POST", url: "/api/v1/recipes/{id}/ingredients", ...config }) as Promise<
    RequestResult<PostApiV1RecipesIdIngredientsResponses, ThrowOnError>
  >;
}
