/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Options, RequestResult } from "../.kubb/client";
import type { PostApiV1RecipesOptions, PostApiV1RecipesResponses } from "../types/PostApiV1Recipes";
import { client } from "../.kubb/client";

/**
 * @summary Create recipe
 * {@link /api/v1/recipes}
 */
export function postApiV1Recipes<ThrowOnError extends boolean = true>(
  options: Options<PostApiV1RecipesOptions, ThrowOnError>,
): Promise<RequestResult<PostApiV1RecipesResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options;

  return request({ method: "POST", url: "/api/v1/recipes", ...config }) as Promise<
    RequestResult<PostApiV1RecipesResponses, ThrowOnError>
  >;
}
