/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Options, RequestResult } from "../.kubb/client";
import type {
  PutApiV1RecipesIdIngredientOptions,
  PutApiV1RecipesIdIngredientResponses,
} from "../types/PutApiV1RecipesIdIngredient";
import { client } from "../.kubb/client";

/**
 * @summary Update recipe ingredient
 * {@link /api/v1/recipes/:id/ingredient}
 */
export function putApiV1RecipesIdIngredient<ThrowOnError extends boolean = true>(
  options: Options<PutApiV1RecipesIdIngredientOptions, ThrowOnError>,
): Promise<RequestResult<PutApiV1RecipesIdIngredientResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options;

  return request({ method: "PUT", url: "/api/v1/recipes/{id}/ingredient", ...config }) as Promise<
    RequestResult<PutApiV1RecipesIdIngredientResponses, ThrowOnError>
  >;
}
