/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Options, RequestResult } from "../.kubb/client";
import type {
  PutApiV1RecipesIdInstructionOptions,
  PutApiV1RecipesIdInstructionResponses,
} from "../types/PutApiV1RecipesIdInstruction";
import { client } from "../.kubb/client";

/**
 * @summary Update recipe instruction
 * {@link /api/v1/recipes/:id/instruction}
 */
export function putApiV1RecipesIdInstruction<ThrowOnError extends boolean = true>(
  options: Options<PutApiV1RecipesIdInstructionOptions, ThrowOnError>,
): Promise<RequestResult<PutApiV1RecipesIdInstructionResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options;

  return request({ method: "PUT", url: "/api/v1/recipes/{id}/instruction", ...config }) as Promise<
    RequestResult<PutApiV1RecipesIdInstructionResponses, ThrowOnError>
  >;
}
