/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Options, RequestResult } from "../.kubb/client";
import type {
  PutApiV1RecipesIdOptions,
  PutApiV1RecipesIdResponses,
} from "../types/PutApiV1RecipesId";
import { client } from "../.kubb/client";

/**
 * @summary Update recipe
 * {@link /api/v1/recipes/:id}
 */
export function putApiV1RecipesId<ThrowOnError extends boolean = true>(
  options: Options<PutApiV1RecipesIdOptions, ThrowOnError>,
): Promise<RequestResult<PutApiV1RecipesIdResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options;

  return request({ method: "PUT", url: "/api/v1/recipes/{id}", ...config }) as Promise<
    RequestResult<PutApiV1RecipesIdResponses, ThrowOnError>
  >;
}
