/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Options, RequestResult } from "../.kubb/client";
import type {
  UpdateRecipeInstructionOptions,
  UpdateRecipeInstructionResponses,
} from "../types/UpdateRecipeInstruction";
import { client } from "../.kubb/client";

/**
 * @summary Update recipe instruction
 * {@link /api/v1/recipes/:id/instruction}
 */
export function updateRecipeInstruction<ThrowOnError extends boolean = true>(
  options: Options<UpdateRecipeInstructionOptions, ThrowOnError>,
): Promise<RequestResult<UpdateRecipeInstructionResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options;

  return request({ method: "PUT", url: "/api/v1/recipes/{id}/instruction", ...config }) as Promise<
    RequestResult<UpdateRecipeInstructionResponses, ThrowOnError>
  >;
}
