/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Options, RequestResult } from "../.kubb/client";
import type {
  UpdateRecipeIngredientOptions,
  UpdateRecipeIngredientResponses,
} from "../types/UpdateRecipeIngredient";
import { client } from "../.kubb/client";

/**
 * @summary Update recipe ingredient
 * {@link /api/v1/recipes/:id/ingredient}
 */
export function updateRecipeIngredient<ThrowOnError extends boolean = true>(
  options: Options<UpdateRecipeIngredientOptions, ThrowOnError>,
): Promise<RequestResult<UpdateRecipeIngredientResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options;

  return request({ method: "PUT", url: "/api/v1/recipes/{id}/ingredient", ...config }) as Promise<
    RequestResult<UpdateRecipeIngredientResponses, ThrowOnError>
  >;
}
