/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Options, RequestResult } from "../.kubb/client";
import type { UpdateRecipeOptions, UpdateRecipeResponses } from "../types/UpdateRecipe";
import { client } from "../.kubb/client";

/**
 * @summary Update recipe
 * {@link /api/v1/recipes/:id}
 */
export function updateRecipe<ThrowOnError extends boolean = true>(
  options: Options<UpdateRecipeOptions, ThrowOnError>,
): Promise<RequestResult<UpdateRecipeResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options;

  return request({ method: "PUT", url: "/api/v1/recipes/{id}", ...config }) as Promise<
    RequestResult<UpdateRecipeResponses, ThrowOnError>
  >;
}
