/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from "zod";

export const githubComDomicileappDomicileInternalDbListRecipeIngredientsRowSchema = z.object({
  group_name: z.string().optional(),
  id: z.int().optional(),
  ingredient_name: z.string().optional(),
  parse_status: z.string().optional(),
  preparation: z.string().optional(),
  quantity: z.number().optional(),
  raw_text: z.string().optional(),
  recipe_id: z.int().optional(),
  sort_order: z.number().optional(),
  unit: z.string().optional(),
});
