/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from "zod";

export const githubComDomicileappDomicileInternalDbRecipeInstructionSchema = z.object({
  content: z.string().optional(),
  created_at: z.string().optional(),
  group_name: z.string().optional(),
  id: z.int().optional(),
  recipe_id: z.int().optional(),
  sort_order: z.number().optional(),
  updated_at: z.string().optional(),
});
