/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from "zod";

export const githubComDomicileappDomicileInternalDbRecipeSchema = z.object({
  cook_time: z.string().optional(),
  created_at: z.string().optional(),
  deleted_at: z.string().optional(),
  id: z.int().optional(),
  name: z.string().optional(),
  notes: z.string().optional(),
  nutrition: z.string().optional(),
  photo_url: z.string().optional(),
  prep_time: z.string().optional(),
  servings: z.string().optional(),
  short_description: z.string().optional(),
  source: z.string().optional(),
  updated_at: z.string().optional(),
});
