"""latest

Revision ID: c77b3e866175
Revises: 7de186b1ab3f
Create Date: 2023-07-28 20:54:16.183146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c77b3e866175"
down_revision = "7de186b1ab3f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
