"""latest

Revision ID: 7de186b1ab3f
Revises: c309234f0c07
Create Date: 2023-07-28 20:51:57.463962

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7de186b1ab3f"
down_revision = "c309234f0c07"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("is_admin", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "is_admin")
    # ### end Alembic commands ###
