// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "components": {
        "schemas": {
            "github_com_domicileapp_domicile_internal_db.ListRecipeIngredientsRow": {
                "properties": {
                    "group_name": {
                        "type": "string"
                    },
                    "id": {
                        "type": "integer"
                    },
                    "ingredient_name": {
                        "type": "string"
                    },
                    "parse_status": {
                        "type": "string"
                    },
                    "preparation": {
                        "type": "string"
                    },
                    "quantity": {
                        "type": "number"
                    },
                    "raw_text": {
                        "type": "string"
                    },
                    "recipe_id": {
                        "type": "integer"
                    },
                    "sort_order": {
                        "type": "number"
                    },
                    "unit": {
                        "type": "string"
                    }
                },
                "type": "object"
            },
            "github_com_domicileapp_domicile_internal_db.ListRecipeInstructionsRow": {
                "properties": {
                    "content": {
                        "type": "string"
                    },
                    "group_name": {
                        "type": "string"
                    },
                    "id": {
                        "type": "integer"
                    },
                    "recipe_id": {
                        "type": "integer"
                    },
                    "sort_order": {
                        "type": "number"
                    }
                },
                "type": "object"
            },
            "github_com_domicileapp_domicile_internal_db.Recipe": {
                "properties": {
                    "cook_time": {
                        "type": "string"
                    },
                    "created_at": {
                        "type": "string"
                    },
                    "deleted_at": {
                        "type": "string"
                    },
                    "id": {
                        "type": "integer"
                    },
                    "name": {
                        "type": "string"
                    },
                    "notes": {
                        "type": "string"
                    },
                    "nutrition": {
                        "type": "string"
                    },
                    "prep_time": {
                        "type": "string"
                    },
                    "servings": {
                        "type": "string"
                    },
                    "short_description": {
                        "type": "string"
                    },
                    "source": {
                        "type": "string"
                    },
                    "updated_at": {
                        "type": "string"
                    }
                },
                "type": "object"
            },
            "github_com_domicileapp_domicile_internal_db.RecipeIngredient": {
                "properties": {
                    "created_at": {
                        "type": "string"
                    },
                    "group_name": {
                        "type": "string"
                    },
                    "id": {
                        "type": "integer"
                    },
                    "ingredient_name": {
                        "type": "string"
                    },
                    "parse_status": {
                        "type": "string"
                    },
                    "parsed_at": {
                        "type": "string"
                    },
                    "preparation": {
                        "type": "string"
                    },
                    "quantity": {
                        "type": "number"
                    },
                    "raw_text": {
                        "type": "string"
                    },
                    "recipe_id": {
                        "type": "integer"
                    },
                    "sort_order": {
                        "type": "number"
                    },
                    "unit": {
                        "type": "string"
                    },
                    "updated_at": {
                        "type": "string"
                    }
                },
                "type": "object"
            },
            "github_com_domicileapp_domicile_internal_db.RecipeInstruction": {
                "properties": {
                    "content": {
                        "type": "string"
                    },
                    "created_at": {
                        "type": "string"
                    },
                    "group_name": {
                        "type": "string"
                    },
                    "id": {
                        "type": "integer"
                    },
                    "recipe_id": {
                        "type": "integer"
                    },
                    "sort_order": {
                        "type": "number"
                    },
                    "updated_at": {
                        "type": "string"
                    }
                },
                "type": "object"
            },
            "internal_recipes.RecipeResponse": {
                "properties": {
                    "cook_time": {
                        "type": "string"
                    },
                    "created_at": {
                        "type": "string"
                    },
                    "deleted_at": {
                        "type": "string"
                    },
                    "id": {
                        "type": "integer"
                    },
                    "ingredients": {
                        "items": {
                            "$ref": "#/components/schemas/github_com_domicileapp_domicile_internal_db.ListRecipeIngredientsRow"
                        },
                        "type": "array",
                        "uniqueItems": false
                    },
                    "instructions": {
                        "items": {
                            "$ref": "#/components/schemas/github_com_domicileapp_domicile_internal_db.ListRecipeInstructionsRow"
                        },
                        "type": "array",
                        "uniqueItems": false
                    },
                    "name": {
                        "type": "string"
                    },
                    "notes": {
                        "type": "string"
                    },
                    "nutrition": {
                        "type": "string"
                    },
                    "prep_time": {
                        "type": "string"
                    },
                    "servings": {
                        "type": "string"
                    },
                    "short_description": {
                        "type": "string"
                    },
                    "source": {
                        "type": "string"
                    },
                    "updated_at": {
                        "type": "string"
                    }
                },
                "type": "object"
            },
            "internal_recipes.createIngredientRequest": {
                "properties": {
                    "group_name": {
                        "type": "string"
                    },
                    "raw_text": {
                        "type": "string"
                    },
                    "sort_order": {
                        "type": "number"
                    }
                },
                "type": "object"
            },
            "internal_recipes.createInstructionRequest": {
                "properties": {
                    "content": {
                        "type": "string"
                    },
                    "group_name": {
                        "type": "string"
                    },
                    "sort_order": {
                        "type": "number"
                    }
                },
                "type": "object"
            },
            "internal_recipes.createRecipeRequest": {
                "properties": {
                    "name": {
                        "type": "string"
                    },
                    "short_description": {
                        "type": "string"
                    }
                },
                "type": "object"
            },
            "internal_recipes.updateIngredientRequest": {
                "properties": {
                    "raw_text": {
                        "type": "string"
                    },
                    "sort_order": {
                        "type": "number"
                    }
                },
                "type": "object"
            },
            "internal_recipes.updateInstructionRequest": {
                "properties": {
                    "content": {
                        "type": "string"
                    },
                    "sort_order": {
                        "type": "number"
                    }
                },
                "type": "object"
            },
            "internal_recipes.updateRecipeRequest": {
                "properties": {
                    "name": {
                        "type": "string"
                    },
                    "short_description": {
                        "type": "string"
                    }
                },
                "type": "object"
            }
        }
    },
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "version": "{{.Version}}"
    },
    "externalDocs": {
        "description": "",
        "url": ""
    },
    "paths": {
        "/api/v1/recipes": {
            "delete": {
                "parameters": [
                    {
                        "description": "Recipe ID",
                        "in": "path",
                        "name": "id",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object"
                            }
                        }
                    }
                },
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                },
                "summary": "Delete recipe",
                "tags": [
                    "recipes"
                ]
            },
            "get": {
                "description": "Get list of all recipes",
                "operationId": "list-recipes",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "items": {
                                        "$ref": "#/components/schemas/github_com_domicileapp_domicile_internal_db.Recipe"
                                    },
                                    "type": "array"
                                }
                            }
                        },
                        "description": "OK"
                    }
                },
                "summary": "List recipes",
                "tags": [
                    "recipes"
                ]
            },
            "post": {
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "oneOf": [
                                    {
                                        "type": "object"
                                    },
                                    {
                                        "$ref": "#/components/schemas/internal_recipes.createRecipeRequest",
                                        "summary": "message",
                                        "description": "Recipe data"
                                    }
                                ]
                            }
                        }
                    },
                    "description": "Recipe data",
                    "required": true
                },
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/github_com_domicileapp_domicile_internal_db.Recipe"
                                }
                            }
                        },
                        "description": "OK"
                    }
                },
                "summary": "Create recipe",
                "tags": [
                    "recipes"
                ]
            }
        },
        "/api/v1/recipes/{id}": {
            "get": {
                "parameters": [
                    {
                        "description": "Recipe ID",
                        "in": "path",
                        "name": "id",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/internal_recipes.RecipeResponse"
                                }
                            }
                        },
                        "description": "OK"
                    }
                },
                "summary": "Get recipe by ID",
                "tags": [
                    "recipes"
                ]
            },
            "put": {
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "oneOf": [
                                    {
                                        "type": "object"
                                    },
                                    {
                                        "$ref": "#/components/schemas/internal_recipes.updateRecipeRequest",
                                        "summary": "message",
                                        "description": "Recipe data"
                                    }
                                ]
                            }
                        }
                    },
                    "description": "Recipe data",
                    "required": true
                },
                "responses": {
                    "204": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/github_com_domicileapp_domicile_internal_db.Recipe"
                                }
                            }
                        },
                        "description": "No Content"
                    }
                },
                "summary": "Update recipe",
                "tags": [
                    "recipes"
                ]
            }
        },
        "/api/v1/recipes/{id}/ingredient": {
            "delete": {
                "parameters": [
                    {
                        "description": "Recipe ID",
                        "in": "path",
                        "name": "id",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object"
                            }
                        }
                    }
                },
                "responses": {
                    "204": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/github_com_domicileapp_domicile_internal_db.Recipe"
                                }
                            }
                        },
                        "description": "No Content"
                    }
                },
                "summary": "Delete recipe ingredient",
                "tags": [
                    "recipes",
                    "ingredients"
                ]
            },
            "put": {
                "parameters": [
                    {
                        "description": "Recipe ID",
                        "in": "path",
                        "name": "id",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "oneOf": [
                                    {
                                        "type": "object"
                                    },
                                    {
                                        "$ref": "#/components/schemas/internal_recipes.updateIngredientRequest",
                                        "summary": "message",
                                        "description": "Ingredient data"
                                    }
                                ]
                            }
                        }
                    },
                    "description": "Ingredient data",
                    "required": true
                },
                "responses": {
                    "201": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/github_com_domicileapp_domicile_internal_db.Recipe"
                                }
                            }
                        },
                        "description": "Created"
                    }
                },
                "summary": "Update recipe ingredient",
                "tags": [
                    "recipes",
                    "ingredients"
                ]
            }
        },
        "/api/v1/recipes/{id}/ingredients": {
            "post": {
                "parameters": [
                    {
                        "description": "Recipe ID",
                        "in": "path",
                        "name": "id",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "oneOf": [
                                    {
                                        "type": "object"
                                    },
                                    {
                                        "$ref": "#/components/schemas/internal_recipes.createIngredientRequest",
                                        "summary": "message",
                                        "description": "Ingredient data"
                                    }
                                ]
                            }
                        }
                    },
                    "description": "Ingredient data",
                    "required": true
                },
                "responses": {
                    "201": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/github_com_domicileapp_domicile_internal_db.RecipeIngredient"
                                }
                            }
                        },
                        "description": "Created"
                    }
                },
                "summary": "Create recipe ingredient",
                "tags": [
                    "recipes",
                    "ingredients"
                ]
            }
        },
        "/api/v1/recipes/{id}/instruction": {
            "delete": {
                "parameters": [
                    {
                        "description": "Recipe ID",
                        "in": "path",
                        "name": "id",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object"
                            }
                        }
                    }
                },
                "responses": {
                    "204": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/github_com_domicileapp_domicile_internal_db.Recipe"
                                }
                            }
                        },
                        "description": "No Content"
                    }
                },
                "summary": "Delete recipe instruction",
                "tags": [
                    "recipes",
                    "instructions"
                ]
            },
            "put": {
                "parameters": [
                    {
                        "description": "Recipe ID",
                        "in": "path",
                        "name": "id",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "oneOf": [
                                    {
                                        "type": "object"
                                    },
                                    {
                                        "$ref": "#/components/schemas/internal_recipes.updateInstructionRequest",
                                        "summary": "message",
                                        "description": "Instruction data"
                                    }
                                ]
                            }
                        }
                    },
                    "description": "Instruction data",
                    "required": true
                },
                "responses": {
                    "201": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/github_com_domicileapp_domicile_internal_db.Recipe"
                                }
                            }
                        },
                        "description": "Created"
                    }
                },
                "summary": "Update recipe instruction",
                "tags": [
                    "recipes",
                    "instructions"
                ]
            }
        },
        "/api/v1/recipes/{id}/instructions": {
            "post": {
                "parameters": [
                    {
                        "description": "Recipe ID",
                        "in": "path",
                        "name": "id",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "oneOf": [
                                    {
                                        "type": "object"
                                    },
                                    {
                                        "$ref": "#/components/schemas/internal_recipes.createInstructionRequest",
                                        "summary": "message",
                                        "description": "Instruction data"
                                    }
                                ]
                            }
                        }
                    },
                    "description": "Instruction data",
                    "required": true
                },
                "responses": {
                    "201": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/github_com_domicileapp_domicile_internal_db.RecipeInstruction"
                                }
                            }
                        },
                        "description": "Created"
                    }
                },
                "summary": "Create recipe instruction",
                "tags": [
                    "recipes",
                    "instructions"
                ]
            }
        }
    },
    "openapi": "3.1.0"
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1",
	Title:            "Domicile API",
	Description:      "Domicile's REST API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
