// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/recipes": {
            "get": {
                "description": "Get list of all recipes",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "recipes"
                ],
                "summary": "List recipes",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_domicileapp_domicile_internal_db.Recipe"
                            }
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "recipes"
                ],
                "summary": "Create recipe",
                "parameters": [
                    {
                        "description": "Recipe data",
                        "name": "message",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/recipes.createRecipeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_domicileapp_domicile_internal_db.Recipe"
                        }
                    }
                }
            }
        },
        "/api/v1/recipes/{id}": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "recipes"
                ],
                "summary": "Get recipe by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Recipe ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/recipes.RecipeResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_domicileapp_domicile_internal_db.ListRecipeIngredientsRow": {
            "type": "object",
            "properties": {
                "group_name": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "ingredient_name": {
                    "type": "string"
                },
                "parse_status": {
                    "type": "string"
                },
                "preparation": {
                    "type": "string"
                },
                "quantity": {
                    "type": "number"
                },
                "raw_text": {
                    "type": "string"
                },
                "recipe_id": {
                    "type": "integer"
                },
                "sort_order": {
                    "type": "number"
                },
                "unit": {
                    "type": "string"
                }
            }
        },
        "github_com_domicileapp_domicile_internal_db.ListRecipeInstructionsRow": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "group_name": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "recipe_id": {
                    "type": "integer"
                },
                "sort_order": {
                    "type": "number"
                }
            }
        },
        "github_com_domicileapp_domicile_internal_db.Recipe": {
            "type": "object",
            "properties": {
                "cook_time": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "deleted_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "notes": {
                    "type": "string"
                },
                "nutrition": {
                    "type": "string"
                },
                "prep_time": {
                    "type": "string"
                },
                "servings": {
                    "type": "string"
                },
                "short_description": {
                    "type": "string"
                },
                "source": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "recipes.RecipeResponse": {
            "type": "object",
            "properties": {
                "cook_time": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "deleted_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "ingredients": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_domicileapp_domicile_internal_db.ListRecipeIngredientsRow"
                    }
                },
                "instructions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_domicileapp_domicile_internal_db.ListRecipeInstructionsRow"
                    }
                },
                "name": {
                    "type": "string"
                },
                "notes": {
                    "type": "string"
                },
                "nutrition": {
                    "type": "string"
                },
                "prep_time": {
                    "type": "string"
                },
                "servings": {
                    "type": "string"
                },
                "short_description": {
                    "type": "string"
                },
                "source": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "recipes.createRecipeRequest": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "short_description": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Domicile API",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
