// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"
)

type Recipe struct {
	ID               int64      `json:"id"`
	Name             string     `json:"name"`
	ShortDescription *string    `json:"short_description"`
	Servings         *string    `json:"servings"`
	PrepTime         *string    `json:"prep_time"`
	CookTime         *string    `json:"cook_time"`
	Notes            *string    `json:"notes"`
	Nutrition        *string    `json:"nutrition"`
	Source           *string    `json:"source"`
	CreatedAt        time.Time  `json:"created_at"`
	UpdatedAt        time.Time  `json:"updated_at"`
	DeletedAt        *time.Time `json:"deleted_at"`
	PhotoUrl         *string    `json:"photo_url"`
}

type RecipeIngredient struct {
	ID             int64      `json:"id"`
	RecipeID       int64      `json:"recipe_id"`
	GroupName      *string    `json:"group_name"`
	SortOrder      float64    `json:"sort_order"`
	RawText        string     `json:"raw_text"`
	Quantity       *float64   `json:"quantity"`
	Unit           *string    `json:"unit"`
	IngredientName *string    `json:"ingredient_name"`
	Preparation    *string    `json:"preparation"`
	ParseStatus    string     `json:"parse_status"`
	ParsedAt       *time.Time `json:"parsed_at"`
	CreatedAt      time.Time  `json:"created_at"`
	UpdatedAt      time.Time  `json:"updated_at"`
}

type RecipeInstruction struct {
	ID        int64     `json:"id"`
	RecipeID  int64     `json:"recipe_id"`
	GroupName *string   `json:"group_name"`
	SortOrder float64   `json:"sort_order"`
	Content   string    `json:"content"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}
