// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Recipe struct {
	ID               int64              `json:"id"`
	Name             string             `json:"name"`
	ShortDescription pgtype.Text        `json:"short_description"`
	Servings         pgtype.Text        `json:"servings"`
	PrepTime         pgtype.Text        `json:"prep_time"`
	CookTime         pgtype.Text        `json:"cook_time"`
	Notes            pgtype.Text        `json:"notes"`
	Nutrition        pgtype.Text        `json:"nutrition"`
	Source           pgtype.Text        `json:"source"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	DeletedAt        pgtype.Timestamptz `json:"deleted_at"`
}

type RecipeIngredient struct {
	ID             int64              `json:"id"`
	RecipeID       int64              `json:"recipe_id"`
	GroupName      pgtype.Text        `json:"group_name"`
	SortOrder      float64            `json:"sort_order"`
	RawText        string             `json:"raw_text"`
	Quantity       pgtype.Numeric     `json:"quantity"`
	Unit           pgtype.Text        `json:"unit"`
	IngredientName pgtype.Text        `json:"ingredient_name"`
	Preparation    pgtype.Text        `json:"preparation"`
	ParseStatus    string             `json:"parse_status"`
	ParsedAt       pgtype.Timestamptz `json:"parsed_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type RecipeInstruction struct {
	ID        int64              `json:"id"`
	RecipeID  int64              `json:"recipe_id"`
	GroupName pgtype.Text        `json:"group_name"`
	SortOrder float64            `json:"sort_order"`
	Content   string             `json:"content"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
