// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package db

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockQuerier creates a new instance of MockQuerier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQuerier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQuerier {
	mock := &MockQuerier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockQuerier is an autogenerated mock type for the Querier type
type MockQuerier struct {
	mock.Mock
}

type MockQuerier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockQuerier) EXPECT() *MockQuerier_Expecter {
	return &MockQuerier_Expecter{mock: &_m.Mock}
}

// CreateRecipe provides a mock function for the type MockQuerier
func (_mock *MockQuerier) CreateRecipe(ctx context.Context, arg CreateRecipeParams) (Recipe, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateRecipe")
	}

	var r0 Recipe
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, CreateRecipeParams) (Recipe, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, CreateRecipeParams) Recipe); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Get(0).(Recipe)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, CreateRecipeParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_CreateRecipe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRecipe'
type MockQuerier_CreateRecipe_Call struct {
	*mock.Call
}

// CreateRecipe is a helper method to define mock.On call
//   - ctx context.Context
//   - arg CreateRecipeParams
func (_e *MockQuerier_Expecter) CreateRecipe(ctx any, arg any) *MockQuerier_CreateRecipe_Call {
	return &MockQuerier_CreateRecipe_Call{Call: _e.mock.On("CreateRecipe", ctx, arg)}
}

func (_c *MockQuerier_CreateRecipe_Call) Run(run func(ctx context.Context, arg CreateRecipeParams)) *MockQuerier_CreateRecipe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 CreateRecipeParams
		if args[1] != nil {
			arg1 = args[1].(CreateRecipeParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_CreateRecipe_Call) Return(recipe Recipe, err error) *MockQuerier_CreateRecipe_Call {
	_c.Call.Return(recipe, err)
	return _c
}

func (_c *MockQuerier_CreateRecipe_Call) RunAndReturn(run func(ctx context.Context, arg CreateRecipeParams) (Recipe, error)) *MockQuerier_CreateRecipe_Call {
	_c.Call.Return(run)
	return _c
}

// CreateRecipeIngredient provides a mock function for the type MockQuerier
func (_mock *MockQuerier) CreateRecipeIngredient(ctx context.Context, arg CreateRecipeIngredientParams) (RecipeIngredient, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateRecipeIngredient")
	}

	var r0 RecipeIngredient
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, CreateRecipeIngredientParams) (RecipeIngredient, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, CreateRecipeIngredientParams) RecipeIngredient); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Get(0).(RecipeIngredient)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, CreateRecipeIngredientParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_CreateRecipeIngredient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRecipeIngredient'
type MockQuerier_CreateRecipeIngredient_Call struct {
	*mock.Call
}

// CreateRecipeIngredient is a helper method to define mock.On call
//   - ctx context.Context
//   - arg CreateRecipeIngredientParams
func (_e *MockQuerier_Expecter) CreateRecipeIngredient(ctx any, arg any) *MockQuerier_CreateRecipeIngredient_Call {
	return &MockQuerier_CreateRecipeIngredient_Call{Call: _e.mock.On("CreateRecipeIngredient", ctx, arg)}
}

func (_c *MockQuerier_CreateRecipeIngredient_Call) Run(run func(ctx context.Context, arg CreateRecipeIngredientParams)) *MockQuerier_CreateRecipeIngredient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 CreateRecipeIngredientParams
		if args[1] != nil {
			arg1 = args[1].(CreateRecipeIngredientParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_CreateRecipeIngredient_Call) Return(recipeIngredient RecipeIngredient, err error) *MockQuerier_CreateRecipeIngredient_Call {
	_c.Call.Return(recipeIngredient, err)
	return _c
}

func (_c *MockQuerier_CreateRecipeIngredient_Call) RunAndReturn(run func(ctx context.Context, arg CreateRecipeIngredientParams) (RecipeIngredient, error)) *MockQuerier_CreateRecipeIngredient_Call {
	_c.Call.Return(run)
	return _c
}

// CreateRecipeInstruction provides a mock function for the type MockQuerier
func (_mock *MockQuerier) CreateRecipeInstruction(ctx context.Context, arg CreateRecipeInstructionParams) (RecipeInstruction, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateRecipeInstruction")
	}

	var r0 RecipeInstruction
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, CreateRecipeInstructionParams) (RecipeInstruction, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, CreateRecipeInstructionParams) RecipeInstruction); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Get(0).(RecipeInstruction)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, CreateRecipeInstructionParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_CreateRecipeInstruction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRecipeInstruction'
type MockQuerier_CreateRecipeInstruction_Call struct {
	*mock.Call
}

// CreateRecipeInstruction is a helper method to define mock.On call
//   - ctx context.Context
//   - arg CreateRecipeInstructionParams
func (_e *MockQuerier_Expecter) CreateRecipeInstruction(ctx any, arg any) *MockQuerier_CreateRecipeInstruction_Call {
	return &MockQuerier_CreateRecipeInstruction_Call{Call: _e.mock.On("CreateRecipeInstruction", ctx, arg)}
}

func (_c *MockQuerier_CreateRecipeInstruction_Call) Run(run func(ctx context.Context, arg CreateRecipeInstructionParams)) *MockQuerier_CreateRecipeInstruction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 CreateRecipeInstructionParams
		if args[1] != nil {
			arg1 = args[1].(CreateRecipeInstructionParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_CreateRecipeInstruction_Call) Return(recipeInstruction RecipeInstruction, err error) *MockQuerier_CreateRecipeInstruction_Call {
	_c.Call.Return(recipeInstruction, err)
	return _c
}

func (_c *MockQuerier_CreateRecipeInstruction_Call) RunAndReturn(run func(ctx context.Context, arg CreateRecipeInstructionParams) (RecipeInstruction, error)) *MockQuerier_CreateRecipeInstruction_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteRecipe provides a mock function for the type MockQuerier
func (_mock *MockQuerier) DeleteRecipe(ctx context.Context, id int64) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRecipe")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockQuerier_DeleteRecipe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteRecipe'
type MockQuerier_DeleteRecipe_Call struct {
	*mock.Call
}

// DeleteRecipe is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockQuerier_Expecter) DeleteRecipe(ctx any, id any) *MockQuerier_DeleteRecipe_Call {
	return &MockQuerier_DeleteRecipe_Call{Call: _e.mock.On("DeleteRecipe", ctx, id)}
}

func (_c *MockQuerier_DeleteRecipe_Call) Run(run func(ctx context.Context, id int64)) *MockQuerier_DeleteRecipe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_DeleteRecipe_Call) Return(err error) *MockQuerier_DeleteRecipe_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockQuerier_DeleteRecipe_Call) RunAndReturn(run func(ctx context.Context, id int64) error) *MockQuerier_DeleteRecipe_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteRecipeIngredient provides a mock function for the type MockQuerier
func (_mock *MockQuerier) DeleteRecipeIngredient(ctx context.Context, id int64) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRecipeIngredient")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockQuerier_DeleteRecipeIngredient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteRecipeIngredient'
type MockQuerier_DeleteRecipeIngredient_Call struct {
	*mock.Call
}

// DeleteRecipeIngredient is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockQuerier_Expecter) DeleteRecipeIngredient(ctx any, id any) *MockQuerier_DeleteRecipeIngredient_Call {
	return &MockQuerier_DeleteRecipeIngredient_Call{Call: _e.mock.On("DeleteRecipeIngredient", ctx, id)}
}

func (_c *MockQuerier_DeleteRecipeIngredient_Call) Run(run func(ctx context.Context, id int64)) *MockQuerier_DeleteRecipeIngredient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_DeleteRecipeIngredient_Call) Return(err error) *MockQuerier_DeleteRecipeIngredient_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockQuerier_DeleteRecipeIngredient_Call) RunAndReturn(run func(ctx context.Context, id int64) error) *MockQuerier_DeleteRecipeIngredient_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteRecipeInstruction provides a mock function for the type MockQuerier
func (_mock *MockQuerier) DeleteRecipeInstruction(ctx context.Context, id int64) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRecipeInstruction")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockQuerier_DeleteRecipeInstruction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteRecipeInstruction'
type MockQuerier_DeleteRecipeInstruction_Call struct {
	*mock.Call
}

// DeleteRecipeInstruction is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockQuerier_Expecter) DeleteRecipeInstruction(ctx any, id any) *MockQuerier_DeleteRecipeInstruction_Call {
	return &MockQuerier_DeleteRecipeInstruction_Call{Call: _e.mock.On("DeleteRecipeInstruction", ctx, id)}
}

func (_c *MockQuerier_DeleteRecipeInstruction_Call) Run(run func(ctx context.Context, id int64)) *MockQuerier_DeleteRecipeInstruction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_DeleteRecipeInstruction_Call) Return(err error) *MockQuerier_DeleteRecipeInstruction_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockQuerier_DeleteRecipeInstruction_Call) RunAndReturn(run func(ctx context.Context, id int64) error) *MockQuerier_DeleteRecipeInstruction_Call {
	_c.Call.Return(run)
	return _c
}

// GetRecipe provides a mock function for the type MockQuerier
func (_mock *MockQuerier) GetRecipe(ctx context.Context, id int64) (Recipe, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetRecipe")
	}

	var r0 Recipe
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (Recipe, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) Recipe); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(Recipe)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_GetRecipe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRecipe'
type MockQuerier_GetRecipe_Call struct {
	*mock.Call
}

// GetRecipe is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockQuerier_Expecter) GetRecipe(ctx any, id any) *MockQuerier_GetRecipe_Call {
	return &MockQuerier_GetRecipe_Call{Call: _e.mock.On("GetRecipe", ctx, id)}
}

func (_c *MockQuerier_GetRecipe_Call) Run(run func(ctx context.Context, id int64)) *MockQuerier_GetRecipe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_GetRecipe_Call) Return(recipe Recipe, err error) *MockQuerier_GetRecipe_Call {
	_c.Call.Return(recipe, err)
	return _c
}

func (_c *MockQuerier_GetRecipe_Call) RunAndReturn(run func(ctx context.Context, id int64) (Recipe, error)) *MockQuerier_GetRecipe_Call {
	_c.Call.Return(run)
	return _c
}

// ListRecipeIngredients provides a mock function for the type MockQuerier
func (_mock *MockQuerier) ListRecipeIngredients(ctx context.Context, dollar_1 []int64) ([]ListRecipeIngredientsRow, error) {
	ret := _mock.Called(ctx, dollar_1)

	if len(ret) == 0 {
		panic("no return value specified for ListRecipeIngredients")
	}

	var r0 []ListRecipeIngredientsRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []int64) ([]ListRecipeIngredientsRow, error)); ok {
		return returnFunc(ctx, dollar_1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []int64) []ListRecipeIngredientsRow); ok {
		r0 = returnFunc(ctx, dollar_1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ListRecipeIngredientsRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []int64) error); ok {
		r1 = returnFunc(ctx, dollar_1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_ListRecipeIngredients_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListRecipeIngredients'
type MockQuerier_ListRecipeIngredients_Call struct {
	*mock.Call
}

// ListRecipeIngredients is a helper method to define mock.On call
//   - ctx context.Context
//   - dollar_1 []int64
func (_e *MockQuerier_Expecter) ListRecipeIngredients(ctx any, dollar_1 any) *MockQuerier_ListRecipeIngredients_Call {
	return &MockQuerier_ListRecipeIngredients_Call{Call: _e.mock.On("ListRecipeIngredients", ctx, dollar_1)}
}

func (_c *MockQuerier_ListRecipeIngredients_Call) Run(run func(ctx context.Context, dollar_1 []int64)) *MockQuerier_ListRecipeIngredients_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []int64
		if args[1] != nil {
			arg1 = args[1].([]int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_ListRecipeIngredients_Call) Return(listRecipeIngredientsRows []ListRecipeIngredientsRow, err error) *MockQuerier_ListRecipeIngredients_Call {
	_c.Call.Return(listRecipeIngredientsRows, err)
	return _c
}

func (_c *MockQuerier_ListRecipeIngredients_Call) RunAndReturn(run func(ctx context.Context, dollar_1 []int64) ([]ListRecipeIngredientsRow, error)) *MockQuerier_ListRecipeIngredients_Call {
	_c.Call.Return(run)
	return _c
}

// ListRecipeInstructions provides a mock function for the type MockQuerier
func (_mock *MockQuerier) ListRecipeInstructions(ctx context.Context, dollar_1 []int64) ([]ListRecipeInstructionsRow, error) {
	ret := _mock.Called(ctx, dollar_1)

	if len(ret) == 0 {
		panic("no return value specified for ListRecipeInstructions")
	}

	var r0 []ListRecipeInstructionsRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []int64) ([]ListRecipeInstructionsRow, error)); ok {
		return returnFunc(ctx, dollar_1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []int64) []ListRecipeInstructionsRow); ok {
		r0 = returnFunc(ctx, dollar_1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ListRecipeInstructionsRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []int64) error); ok {
		r1 = returnFunc(ctx, dollar_1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_ListRecipeInstructions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListRecipeInstructions'
type MockQuerier_ListRecipeInstructions_Call struct {
	*mock.Call
}

// ListRecipeInstructions is a helper method to define mock.On call
//   - ctx context.Context
//   - dollar_1 []int64
func (_e *MockQuerier_Expecter) ListRecipeInstructions(ctx any, dollar_1 any) *MockQuerier_ListRecipeInstructions_Call {
	return &MockQuerier_ListRecipeInstructions_Call{Call: _e.mock.On("ListRecipeInstructions", ctx, dollar_1)}
}

func (_c *MockQuerier_ListRecipeInstructions_Call) Run(run func(ctx context.Context, dollar_1 []int64)) *MockQuerier_ListRecipeInstructions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []int64
		if args[1] != nil {
			arg1 = args[1].([]int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_ListRecipeInstructions_Call) Return(listRecipeInstructionsRows []ListRecipeInstructionsRow, err error) *MockQuerier_ListRecipeInstructions_Call {
	_c.Call.Return(listRecipeInstructionsRows, err)
	return _c
}

func (_c *MockQuerier_ListRecipeInstructions_Call) RunAndReturn(run func(ctx context.Context, dollar_1 []int64) ([]ListRecipeInstructionsRow, error)) *MockQuerier_ListRecipeInstructions_Call {
	_c.Call.Return(run)
	return _c
}

// ListRecipes provides a mock function for the type MockQuerier
func (_mock *MockQuerier) ListRecipes(ctx context.Context) ([]ListRecipesRow, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListRecipes")
	}

	var r0 []ListRecipesRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]ListRecipesRow, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []ListRecipesRow); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ListRecipesRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_ListRecipes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListRecipes'
type MockQuerier_ListRecipes_Call struct {
	*mock.Call
}

// ListRecipes is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockQuerier_Expecter) ListRecipes(ctx any) *MockQuerier_ListRecipes_Call {
	return &MockQuerier_ListRecipes_Call{Call: _e.mock.On("ListRecipes", ctx)}
}

func (_c *MockQuerier_ListRecipes_Call) Run(run func(ctx context.Context)) *MockQuerier_ListRecipes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockQuerier_ListRecipes_Call) Return(listRecipesRows []ListRecipesRow, err error) *MockQuerier_ListRecipes_Call {
	_c.Call.Return(listRecipesRows, err)
	return _c
}

func (_c *MockQuerier_ListRecipes_Call) RunAndReturn(run func(ctx context.Context) ([]ListRecipesRow, error)) *MockQuerier_ListRecipes_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateRecipe provides a mock function for the type MockQuerier
func (_mock *MockQuerier) UpdateRecipe(ctx context.Context, arg UpdateRecipeParams) (Recipe, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRecipe")
	}

	var r0 Recipe
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, UpdateRecipeParams) (Recipe, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, UpdateRecipeParams) Recipe); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Get(0).(Recipe)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, UpdateRecipeParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_UpdateRecipe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateRecipe'
type MockQuerier_UpdateRecipe_Call struct {
	*mock.Call
}

// UpdateRecipe is a helper method to define mock.On call
//   - ctx context.Context
//   - arg UpdateRecipeParams
func (_e *MockQuerier_Expecter) UpdateRecipe(ctx any, arg any) *MockQuerier_UpdateRecipe_Call {
	return &MockQuerier_UpdateRecipe_Call{Call: _e.mock.On("UpdateRecipe", ctx, arg)}
}

func (_c *MockQuerier_UpdateRecipe_Call) Run(run func(ctx context.Context, arg UpdateRecipeParams)) *MockQuerier_UpdateRecipe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 UpdateRecipeParams
		if args[1] != nil {
			arg1 = args[1].(UpdateRecipeParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_UpdateRecipe_Call) Return(recipe Recipe, err error) *MockQuerier_UpdateRecipe_Call {
	_c.Call.Return(recipe, err)
	return _c
}

func (_c *MockQuerier_UpdateRecipe_Call) RunAndReturn(run func(ctx context.Context, arg UpdateRecipeParams) (Recipe, error)) *MockQuerier_UpdateRecipe_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateRecipeIngredientParsed provides a mock function for the type MockQuerier
func (_mock *MockQuerier) UpdateRecipeIngredientParsed(ctx context.Context, arg UpdateRecipeIngredientParsedParams) error {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRecipeIngredientParsed")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, UpdateRecipeIngredientParsedParams) error); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockQuerier_UpdateRecipeIngredientParsed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateRecipeIngredientParsed'
type MockQuerier_UpdateRecipeIngredientParsed_Call struct {
	*mock.Call
}

// UpdateRecipeIngredientParsed is a helper method to define mock.On call
//   - ctx context.Context
//   - arg UpdateRecipeIngredientParsedParams
func (_e *MockQuerier_Expecter) UpdateRecipeIngredientParsed(ctx any, arg any) *MockQuerier_UpdateRecipeIngredientParsed_Call {
	return &MockQuerier_UpdateRecipeIngredientParsed_Call{Call: _e.mock.On("UpdateRecipeIngredientParsed", ctx, arg)}
}

func (_c *MockQuerier_UpdateRecipeIngredientParsed_Call) Run(run func(ctx context.Context, arg UpdateRecipeIngredientParsedParams)) *MockQuerier_UpdateRecipeIngredientParsed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 UpdateRecipeIngredientParsedParams
		if args[1] != nil {
			arg1 = args[1].(UpdateRecipeIngredientParsedParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_UpdateRecipeIngredientParsed_Call) Return(err error) *MockQuerier_UpdateRecipeIngredientParsed_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockQuerier_UpdateRecipeIngredientParsed_Call) RunAndReturn(run func(ctx context.Context, arg UpdateRecipeIngredientParsedParams) error) *MockQuerier_UpdateRecipeIngredientParsed_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateRecipeIngredientSortOrder provides a mock function for the type MockQuerier
func (_mock *MockQuerier) UpdateRecipeIngredientSortOrder(ctx context.Context, arg UpdateRecipeIngredientSortOrderParams) error {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRecipeIngredientSortOrder")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, UpdateRecipeIngredientSortOrderParams) error); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockQuerier_UpdateRecipeIngredientSortOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateRecipeIngredientSortOrder'
type MockQuerier_UpdateRecipeIngredientSortOrder_Call struct {
	*mock.Call
}

// UpdateRecipeIngredientSortOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - arg UpdateRecipeIngredientSortOrderParams
func (_e *MockQuerier_Expecter) UpdateRecipeIngredientSortOrder(ctx any, arg any) *MockQuerier_UpdateRecipeIngredientSortOrder_Call {
	return &MockQuerier_UpdateRecipeIngredientSortOrder_Call{Call: _e.mock.On("UpdateRecipeIngredientSortOrder", ctx, arg)}
}

func (_c *MockQuerier_UpdateRecipeIngredientSortOrder_Call) Run(run func(ctx context.Context, arg UpdateRecipeIngredientSortOrderParams)) *MockQuerier_UpdateRecipeIngredientSortOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 UpdateRecipeIngredientSortOrderParams
		if args[1] != nil {
			arg1 = args[1].(UpdateRecipeIngredientSortOrderParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_UpdateRecipeIngredientSortOrder_Call) Return(err error) *MockQuerier_UpdateRecipeIngredientSortOrder_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockQuerier_UpdateRecipeIngredientSortOrder_Call) RunAndReturn(run func(ctx context.Context, arg UpdateRecipeIngredientSortOrderParams) error) *MockQuerier_UpdateRecipeIngredientSortOrder_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateRecipeInstructionContent provides a mock function for the type MockQuerier
func (_mock *MockQuerier) UpdateRecipeInstructionContent(ctx context.Context, arg UpdateRecipeInstructionContentParams) error {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRecipeInstructionContent")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, UpdateRecipeInstructionContentParams) error); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockQuerier_UpdateRecipeInstructionContent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateRecipeInstructionContent'
type MockQuerier_UpdateRecipeInstructionContent_Call struct {
	*mock.Call
}

// UpdateRecipeInstructionContent is a helper method to define mock.On call
//   - ctx context.Context
//   - arg UpdateRecipeInstructionContentParams
func (_e *MockQuerier_Expecter) UpdateRecipeInstructionContent(ctx any, arg any) *MockQuerier_UpdateRecipeInstructionContent_Call {
	return &MockQuerier_UpdateRecipeInstructionContent_Call{Call: _e.mock.On("UpdateRecipeInstructionContent", ctx, arg)}
}

func (_c *MockQuerier_UpdateRecipeInstructionContent_Call) Run(run func(ctx context.Context, arg UpdateRecipeInstructionContentParams)) *MockQuerier_UpdateRecipeInstructionContent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 UpdateRecipeInstructionContentParams
		if args[1] != nil {
			arg1 = args[1].(UpdateRecipeInstructionContentParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_UpdateRecipeInstructionContent_Call) Return(err error) *MockQuerier_UpdateRecipeInstructionContent_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockQuerier_UpdateRecipeInstructionContent_Call) RunAndReturn(run func(ctx context.Context, arg UpdateRecipeInstructionContentParams) error) *MockQuerier_UpdateRecipeInstructionContent_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateRecipeInstructionSortOrder provides a mock function for the type MockQuerier
func (_mock *MockQuerier) UpdateRecipeInstructionSortOrder(ctx context.Context, arg UpdateRecipeInstructionSortOrderParams) error {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRecipeInstructionSortOrder")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, UpdateRecipeInstructionSortOrderParams) error); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockQuerier_UpdateRecipeInstructionSortOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateRecipeInstructionSortOrder'
type MockQuerier_UpdateRecipeInstructionSortOrder_Call struct {
	*mock.Call
}

// UpdateRecipeInstructionSortOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - arg UpdateRecipeInstructionSortOrderParams
func (_e *MockQuerier_Expecter) UpdateRecipeInstructionSortOrder(ctx any, arg any) *MockQuerier_UpdateRecipeInstructionSortOrder_Call {
	return &MockQuerier_UpdateRecipeInstructionSortOrder_Call{Call: _e.mock.On("UpdateRecipeInstructionSortOrder", ctx, arg)}
}

func (_c *MockQuerier_UpdateRecipeInstructionSortOrder_Call) Run(run func(ctx context.Context, arg UpdateRecipeInstructionSortOrderParams)) *MockQuerier_UpdateRecipeInstructionSortOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 UpdateRecipeInstructionSortOrderParams
		if args[1] != nil {
			arg1 = args[1].(UpdateRecipeInstructionSortOrderParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_UpdateRecipeInstructionSortOrder_Call) Return(err error) *MockQuerier_UpdateRecipeInstructionSortOrder_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockQuerier_UpdateRecipeInstructionSortOrder_Call) RunAndReturn(run func(ctx context.Context, arg UpdateRecipeInstructionSortOrderParams) error) *MockQuerier_UpdateRecipeInstructionSortOrder_Call {
	_c.Call.Return(run)
	return _c
}
