// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	CountRecipes(ctx context.Context, search string) (int64, error)
	CreateFullRecipe(ctx context.Context, arg CreateFullRecipeParams) (Recipe, error)
	CreateRecipe(ctx context.Context, arg CreateRecipeParams) (Recipe, error)
	CreateRecipeIngredient(ctx context.Context, arg CreateRecipeIngredientParams) (RecipeIngredient, error)
	CreateRecipeInstruction(ctx context.Context, arg CreateRecipeInstructionParams) (RecipeInstruction, error)
	DeleteRecipe(ctx context.Context, id int64) error
	DeleteRecipeIngredient(ctx context.Context, id int64) error
	DeleteRecipeInstruction(ctx context.Context, id int64) error
	GetRecipe(ctx context.Context, id int64) (Recipe, error)
	ListRecipeIngredients(ctx context.Context, dollar_1 []int64) ([]ListRecipeIngredientsRow, error)
	ListRecipeInstructions(ctx context.Context, dollar_1 []int64) ([]ListRecipeInstructionsRow, error)
	ListRecipes(ctx context.Context, arg ListRecipesParams) ([]ListRecipesRow, error)
	UpdateRecipe(ctx context.Context, arg UpdateRecipeParams) (Recipe, error)
	UpdateRecipeIngredient(ctx context.Context, arg UpdateRecipeIngredientParams) error
	UpdateRecipeInstruction(ctx context.Context, arg UpdateRecipeInstructionParams) error
}

var _ Querier = (*Queries)(nil)
