// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	CreateRecipe(ctx context.Context, arg CreateRecipeParams) (Recipe, error)
	CreateRecipeIngredient(ctx context.Context, arg CreateRecipeIngredientParams) (RecipeIngredient, error)
	CreateRecipeInstruction(ctx context.Context, arg CreateRecipeInstructionParams) (RecipeInstruction, error)
	DeleteRecipe(ctx context.Context, id int64) error
	DeleteRecipeIngredient(ctx context.Context, id int64) error
	DeleteRecipeInstruction(ctx context.Context, id int64) error
	GetRecipe(ctx context.Context, id int64) (Recipe, error)
	ListRecipeIngredients(ctx context.Context, dollar_1 []int64) ([]ListRecipeIngredientsRow, error)
	ListRecipeInstructions(ctx context.Context, dollar_1 []int64) ([]ListRecipeInstructionsRow, error)
	ListRecipes(ctx context.Context) ([]ListRecipesRow, error)
	UpdateRecipe(ctx context.Context, arg UpdateRecipeParams) (Recipe, error)
	UpdateRecipeIngredientParsed(ctx context.Context, arg UpdateRecipeIngredientParsedParams) error
	UpdateRecipeIngredientSortOrder(ctx context.Context, arg UpdateRecipeIngredientSortOrderParams) error
	UpdateRecipeInstructionContent(ctx context.Context, arg UpdateRecipeInstructionContentParams) error
	UpdateRecipeInstructionSortOrder(ctx context.Context, arg UpdateRecipeInstructionSortOrderParams) error
}

var _ Querier = (*Queries)(nil)
