// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: recipes.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRecipe = `-- name: CreateRecipe :one
insert into recipes (
    name,
    short_description
)
values ($1, $2)
returning id, name, short_description, servings, prep_time, cook_time, notes, nutrition, source, created_at, updated_at, deleted_at
`

type CreateRecipeParams struct {
	Name             string      `json:"name"`
	ShortDescription pgtype.Text `json:"short_description"`
}

func (q *Queries) CreateRecipe(ctx context.Context, arg CreateRecipeParams) (Recipe, error) {
	row := q.db.QueryRow(ctx, createRecipe, arg.Name, arg.ShortDescription)
	var i Recipe
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ShortDescription,
		&i.Servings,
		&i.PrepTime,
		&i.CookTime,
		&i.Notes,
		&i.Nutrition,
		&i.Source,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteRecipe = `-- name: DeleteRecipe :exec
delete from recipes
where id = $1
`

func (q *Queries) DeleteRecipe(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteRecipe, id)
	return err
}

const getRecipe = `-- name: GetRecipe :one
select id, name, short_description, servings, prep_time, cook_time, notes, nutrition, source, created_at, updated_at, deleted_at from recipes
where id = $1 limit 1
`

func (q *Queries) GetRecipe(ctx context.Context, id int64) (Recipe, error) {
	row := q.db.QueryRow(ctx, getRecipe, id)
	var i Recipe
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ShortDescription,
		&i.Servings,
		&i.PrepTime,
		&i.CookTime,
		&i.Notes,
		&i.Nutrition,
		&i.Source,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listRecipeIngredients = `-- name: ListRecipeIngredients :many
select
    id,
    recipe_id,
    sort_order,
    content
from recipes_ingredients
where recipe_id = $1
order by recipe_id, sort_order
`

func (q *Queries) ListRecipeIngredients(ctx context.Context, recipeID pgtype.Int8) ([]RecipesIngredient, error) {
	rows, err := q.db.Query(ctx, listRecipeIngredients, recipeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RecipesIngredient
	for rows.Next() {
		var i RecipesIngredient
		if err := rows.Scan(
			&i.ID,
			&i.RecipeID,
			&i.SortOrder,
			&i.Content,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecipeInstructions = `-- name: ListRecipeInstructions :many
select
    id,
    recipe_id,
    sort_order,
    content
from recipes_ingredients
where recipe_id = $1
order by recipe_id, sort_order
`

func (q *Queries) ListRecipeInstructions(ctx context.Context, recipeID pgtype.Int8) ([]RecipesIngredient, error) {
	rows, err := q.db.Query(ctx, listRecipeInstructions, recipeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RecipesIngredient
	for rows.Next() {
		var i RecipesIngredient
		if err := rows.Scan(
			&i.ID,
			&i.RecipeID,
			&i.SortOrder,
			&i.Content,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecipes = `-- name: ListRecipes :many
select 
    id,
    name,
    short_description,
    servings,
    prep_time,
    cook_time,
    notes,
    nutrition,
    source,
    created_at,
    updated_at
from recipes
where deleted_at is null
order by updated_at desc
`

type ListRecipesRow struct {
	ID               int64              `json:"id"`
	Name             string             `json:"name"`
	ShortDescription pgtype.Text        `json:"short_description"`
	Servings         pgtype.Text        `json:"servings"`
	PrepTime         pgtype.Text        `json:"prep_time"`
	CookTime         pgtype.Text        `json:"cook_time"`
	Notes            pgtype.Text        `json:"notes"`
	Nutrition        pgtype.Text        `json:"nutrition"`
	Source           pgtype.Text        `json:"source"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListRecipes(ctx context.Context) ([]ListRecipesRow, error) {
	rows, err := q.db.Query(ctx, listRecipes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecipesRow
	for rows.Next() {
		var i ListRecipesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ShortDescription,
			&i.Servings,
			&i.PrepTime,
			&i.CookTime,
			&i.Notes,
			&i.Nutrition,
			&i.Source,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRecipe = `-- name: UpdateRecipe :one
update recipes
set 
    name = $2,
    short_description = $3,
    updated_at = now()
where id = $1
returning id, name, short_description, servings, prep_time, cook_time, notes, nutrition, source, created_at, updated_at, deleted_at
`

type UpdateRecipeParams struct {
	ID               int64       `json:"id"`
	Name             string      `json:"name"`
	ShortDescription pgtype.Text `json:"short_description"`
}

func (q *Queries) UpdateRecipe(ctx context.Context, arg UpdateRecipeParams) (Recipe, error) {
	row := q.db.QueryRow(ctx, updateRecipe, arg.ID, arg.Name, arg.ShortDescription)
	var i Recipe
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ShortDescription,
		&i.Servings,
		&i.PrepTime,
		&i.CookTime,
		&i.Notes,
		&i.Nutrition,
		&i.Source,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
