name: docs

on:
  release:
    types: [published]

permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: set up python
        uses: actions/setup-python@v1
        with:
          version: '3.11'
      - name: set release note tags
        run: |
          export RELEASE_TAG_VERSION=${{ github.event.release.tag_name }}
          echo "RELEASE_TAG_VERSION=${RELEASE_TAG_VERSION:1}" >> $GITHUB_ENV
      - name: release docs
        run: |
          poetry run mike deploy --push --update-aliases ${RELEASE_TAG_VERSION} latest
          poetry run mike set-default --push latest
