name: github

on:
  pull_request:

jobs:
  label:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
    - uses: actions/labeler@v4
      with:
        configuration-path: .github/labeler.yaml
        repo-token: "${{ secrets.TOKEN }}"
        sync-labels: true
