name: github

on:
  pull_request:
  push:
  issues:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  sync-labels:
    runs-on: ubuntu-latest
    steps:
      - uses: EndBug/label-sync@v2
        with:
          config-file: ./.github/labels.yml
          delete-other-labels: true
          dry-run: false
          token: ${{ secrets.GITHUB_TOKEN }}
  add-labels-to-prs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v4
        with:
          sync-labels: true
          repo-token: ${{ secrets.GITHUB_TOKEN }}
