name: release
on:
  push:
    branches:
      - main
      - next
  workflow_dispatch:
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Get token
        id: get_token
        uses: tibdex/github-app-token@0914d50df753bbc42180d982a6550f195390069f # v2
        with:
          app_id: ${{ secrets.DOMICILEBOT_APP_ID }}
          private_key: ${{ secrets.DOMICILEBOT_PRIVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: yarn install

      - name: Release
        env:
          GITHUB_TOKEN: '${{ steps.get_token.outputs.token }}'
          GIT_AUTHOR_NAME: '@domicilebot-bot'
          GIT_AUTHOR_EMAIL: '266197+domicilebot[bot]@users.noreply.github.com'
        run: yarn semantic-release
