name: Release
on:
  push:
    branches:
      - main
      - next
      - dev
permissions:
  contents: write
  id-token: write
  issues: write
  pull-requests: write
  packages: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
      - name: setup semantic-release
        run: npm install -g semantic-release @semantic-release/git @semantic-release/changelog -D
      - name: release
        run: npx semantic-release
