name: release

on:
  push:
    branches: [ dev ]

  workflow_dispatch:
  
jobs:
  create-pr:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          command: manifest
          default-branch: dev