// orval.config.ts
import { defineConfig } from 'orval'

export default defineConfig({
  reactQuery: {
    input: {
      target: '../docs/swagger.json',
    },
    output: {
      mode: 'tags-split',
      target: './src/api/client',
      schemas: './src/api/schemas',
      client: 'react-query',
      httpClient: 'axios',
      mock: true,
      clean: ['./src/api/client/**', './src/api/schemas/**'],
      urlEncodeParameters: true,
      propertySortOrder: 'Alphabetical',
      override: {
        query: {
          signal: true,
        },
        header: (info): string[] => [
          `Generated by Orval`,
          `Do not edit manually.`,
          ...(info.title ? [info.title] : []),
          ...(info.description ? [info.description] : []),
        ],
      },
    },
  },
  zod: {
    input: {
      target: '../docs/swagger.json',
    },
    output: {
      mode: 'tags-split',
      clean: ['./src/api/zod/**'],
      target: './src/api/zod',
      client: 'zod',
      override: {
        header: (info): string[] => [
          `Generated by Orval`,
          `Do not edit manually.`,
          ...(info.title ? [info.title] : []),
          ...(info.description ? [info.description] : []),
        ],
      },
    },
  },
})
